/*
  # Seed Support FAQs - Part 1 (Llogaria & Hyrja, Kompania, Depo)

  Adds ~100 FAQ entries covering:
  - Account & Login issues
  - Company management
  - Depot operations
*/

INSERT INTO support_faqs (category, question, answer, keywords, priority) VALUES

-- LLOGARIA & HYRJA (Account & Login) - 30 entries
('Llogaria', 'Si mund te ndryshoj fjalekalimin?', 'Per te ndryshuar fjalekalimin, shkoni te Profili juaj dhe klikoni "Ndrysho Fjalekalimin". Vendosni fjalekalimin aktual dhe ate te ri. Fjalekalimi duhet te kete te pakten 6 karaktere.', ARRAY['fjalkalim', 'password', 'ndrysho', 'ndryshoj', 'fjalekalimi', 'fjalekalimin', 'hyrje', 'kyc'], 10),
('Llogaria', 'Kam harruar fjalekalimin, si ta rikuperoj?', 'Ne faqen e hyrjes, klikoni "Keni harruar fjalekalimin?" dhe vendosni email-in tuaj. Do te merrni nje email me linkun per ta rivendosur fjalekalimin.', ARRAY['harruar', 'harrova', 'fjalekalim', 'rikupero', 'rivendos', 'nuk', 'mbaj', 'mend'], 10),
('Llogaria', 'Nuk mund te hyj ne llogari, cfare te bej?', 'Sigurohuni qe po perdorni email-in e sakte. Kontrolloni nese Caps Lock eshte aktivizuar. Nese problemi vazhdon, provoni te rivendosni fjalekalimin ose kontaktoni administratorin e kompanise.', ARRAY['hyj', 'hyrje', 'nuk', 'mundem', 'gabim', 'login', 'llogari', 'problem'], 10),
('Llogaria', 'Si ta ndryshoj emrin tim ne profil?', 'Aktualisht ndryshimi i emrit behet nga administratori i kompanise. Kontaktoni administratorin tuaj per te bere ndryshimin.', ARRAY['emri', 'emrin', 'ndrysho', 'ndryshoj', 'profil', 'profili'], 5),
('Llogaria', 'Si te ngarkoj nje foto profili?', 'Shkoni te Chat dhe klikoni ikonene e kameres prane fotos suaj te profilit. Zgjidhni nje foto nga pajisja juaj dhe ajo do te ngarkohet automatikisht.', ARRAY['foto', 'profil', 'profili', 'ngarkoj', 'avatar', 'imazh', 'fotografi'], 7),
('Llogaria', 'A mund te kem dy llogari?', 'Jo, secili perdorues ka nje llogari te vetme qe eshte e lidhur me email-in e tij. Nese keni nevoje per role te ndryshme, kontaktoni administratorin.', ARRAY['dy', 'llogari', 'dyte', 'shtese', 'tjeter'], 3),
('Llogaria', 'Si te shkycem nga platforma?', 'Klikoni butonin "Dil" qe ndodhet ne fund te menus anesore ose ne krahun e djathte te headerit.', ARRAY['shkyc', 'dil', 'largo', 'dilni', 'logout', 'dalje'], 8),
('Llogaria', 'Pse me shkyc automatikisht?', 'Sesioni juaj skadon pas nje periudhe joaktiviteti per arsye sigurie. Kjo eshte normale - thjesht hyni perseri me kredencialet tuaja.', ARRAY['shkyc', 'automatik', 'sesion', 'skadon', 'skaduese', 'kohezgjatje'], 6),
('Llogaria', 'Si te ndryshoj emailin?', 'Ndryshimi i emailit behet nga administratori i kompanise ose super admini. Kontaktoni ata per ndihme.', ARRAY['email', 'ndrysho', 'ndryshoj', 'emailin'], 5),
('Llogaria', 'Cfare roli kam une ne sistem?', 'Roli juaj shfaqet ne panelin e majte nen emrin tuaj. Rolet e mundshme jane: Admin Kompani, Punetor Depoje, dhe Shofer. Secili rol ka lejet e veta.', ARRAY['rol', 'roli', 'role', 'leje', 'akses'], 6),
('Llogaria', 'A eshte e sigurt llogaria ime?', 'Po, platforma perdor enkriptim te avancuar per te mbrojtur te dhenat tuaja. Fjalekalimi juaj ruhet i enkriptuar dhe sesionet mbyllen automatikisht.', ARRAY['sigurt', 'siguri', 'enkriptim', 'mbrojtje', 'hack', 'sigurise'], 7),
('Llogaria', 'Si te shoh aktivitetin e llogarise?', 'Aktualisht historia e aktivitetit eshte e disponueshme vetem per administratoret. Kontaktoni administratorin per informacione rreth aktivitetit tuaj.', ARRAY['aktivitet', 'histori', 'log', 'veprime'], 3),
('Llogaria', 'Kush mund te shoh informacionet e mia?', 'Vetem administratori i kompanise suaj dhe super admini kane akses ne informacionet tuaja te plota. Kolegete mund te shohin vetem emrin dhe foton tuaj te profilit ne chat.', ARRAY['informacion', 'privatesise', 'privatesi', 'shoh', 'akses', 'te dhena'], 7),
('Llogaria', 'Si te shtoj numer telefoni ne profil?', 'Numri i telefonit shtohet nga administratori i kompanise kur krijon llogarine tuaj. Per ndryshime, kontaktoni administratorin.', ARRAY['telefon', 'numer', 'tel', 'celular', 'shtoj'], 4),
('Llogaria', 'Nuk marr email konfirmimi, cfare te bej?', 'Kontrolloni dosjen Spam/Junk te emailit tuaj. Nese nuk e gjeni, provoni te regjistroheni perseri ose kontaktoni suportin.', ARRAY['email', 'konfirmim', 'nuk', 'marr', 'spam', 'junk'], 8),
('Llogaria', 'A mund te perdor platformen nga telefoni?', 'Po, platforma eshte e optimizuar per pajisje mobile. Hapni shfletuesin e telefonit tuaj dhe shkoni ne adresen e platformes.', ARRAY['telefon', 'celular', 'mobile', 'smartphone', 'tablet', 'pajisje'], 8),
('Llogaria', 'Si funksionon sistemi i njoftimeve?', 'Njoftimet shfaqen ne ikonen e ziles ne krye te faqes. Do te njoftoheni per mesazhe te reja, fletedergesa, dhe ndryshime te rendesishme.', ARRAY['njoftim', 'njoftimet', 'notifikim', 'zile', 'alarm'], 6),
('Llogaria', 'Cfare ndodh nese e fshij llogarime?', 'Fshirja e llogarise behet vetem nga administratori. Te dhenat tuaja ruhen per nje periudhe te caktuar sipas ligjit perpara se te fshihen perfundimisht.', ARRAY['fshij', 'fshirje', 'llogari', 'mbyll', 'elimino'], 4),
('Llogaria', 'Si te ndryshoj gjuhen e platformes?', 'Aktualisht platforma eshte vetem ne gjuhen shqipe. Gjuhe te reja do te shtohen ne te ardhmen.', ARRAY['gjuhe', 'gjuha', 'shqip', 'anglisht', 'language'], 3),
('Llogaria', 'A mund te shoh kush eshte online?', 'Aktualisht nuk ka tregues te statusit online. Mund te shihni nese dikush eshte aktiv nga koha e mesazhit te fundit ne chat.', ARRAY['online', 'aktiv', 'status', 'prezent', 'konektuar'], 4),
('Llogaria', 'Si ta di nese llogaria ime eshte aktive?', 'Nese mund te hyni ne sistem, llogaria juaj eshte aktive. Nese merrni gabim, mund te jete caktivizuar - kontaktoni administratorin.', ARRAY['aktive', 'llogari', 'caktivizuar', 'bllokuar', 'pezulluar'], 6),
('Llogaria', 'Cfare shfletuesi duhet te perdor?', 'Platforma funksionon me te gjithe shfletuesit modern: Chrome, Firefox, Safari, Edge. Rekomandojme Chrome ose Firefox per pervoje me te mire.', ARRAY['shfletues', 'browser', 'chrome', 'firefox', 'safari', 'edge'], 5),
('Llogaria', 'Pse duket ndryshe ne telefonin tim?', 'Platforma pershtatet automatikisht sipas madhesise se ekranit. Ne telefon, menuja shfaqet si ikone hamburger ne krye te faqes.', ARRAY['telefon', 'mobile', 'ndryshe', 'pamje', 'ekran', 'layout'], 5),
('Llogaria', 'A ka aplikacion per telefon?', 'Aktualisht nuk ka aplikacion te dedikuar, por platforma eshte plotesisht funksionale permes shfletuesit te telefonit. Mund ta shtoni si shortcut ne ekranin kryesor.', ARRAY['aplikacion', 'app', 'download', 'shkarko', 'install'], 6),
('Llogaria', 'Si te raportoj nje problem teknik?', 'Perdorni chat-in e suportit per te raportuar problemin tuaj. Pershkruani problemin sa me qarte qe te jete e mundur, perfshire hapat qe cuan ne problem.', ARRAY['raportoj', 'problem', 'teknik', 'gabim', 'bug', 'defekt'], 9),
('Llogaria', 'Pse nuk shfaqen te dhenat e mia?', 'Provoni te rifreskoni faqen (F5 ose terhiq-posht ne telefon). Nese problemi vazhdon, pastroni cache-in e shfletuesit ose provoni nje shfletues tjeter.', ARRAY['te dhena', 'shfaq', 'nuk', 'mungojne', 'bosh', 'zbrazet'], 7),
('Llogaria', 'Si funksionon fjalekalimi i sigurt?', 'Nje fjalekalim i sigurt ka te pakten 6 karaktere, perfshin shkronja te medha dhe te vogla, numra, dhe simbole. Mos perdorni informacione personale.', ARRAY['fjalekalim', 'sigurt', 'forte', 'karaktere', 'siguri'], 5),
('Llogaria', 'A mund te kem akses ne dy kompani?', 'Jo, secila llogari eshte e lidhur me nje kompani te vetme. Per kompani te ndryshme nevojiten llogari te ndryshme me email te ndryshem.', ARRAY['dy', 'kompani', 'shtese', 'akses', 'shume'], 4),
('Llogaria', 'Kush eshte administratori im?', 'Administratori i kompanise eshte personi qe krijoi llogarine e kompanise ne platform. Zakonisht eshte menaxheri ose pronari i kompanise.', ARRAY['administrator', 'admin', 'kush', 'menaxher'], 5),
('Llogaria', 'Si te kontaktoj suportin teknik?', 'Perdorni butonin e chat-it te suportit qe gjendet ne te gjitha faqet e platformes. Mund te shkruani pyetjen tuaj dhe do te merrni pergjigje automatike ose ndihme nga ekipi yne.', ARRAY['suport', 'kontakt', 'ndihme', 'help', 'support', 'asistence'], 10),

-- KOMPANIA (Company Management) - 35 entries
('Kompania', 'Si te shtoj nje depo te re?', 'Shkoni te menuja "Depoiste" dhe klikoni butonin "+ Shto Depo". Plotesoni emrin, adresen, dhe caktoni nje menaxher nese deshironi.', ARRAY['depo', 'shtoj', 'krijo', 'ri', 'reja', 'depot', 'depoist'], 9),
('Kompania', 'Si te shtoj nje shofer te ri?', 'Shkoni te menuja "Shoferet" dhe klikoni "+ Shto Shofer". Plotesoni emrin, emailin, fjalekalimin, dhe numrin e telefonit. Shoferi do te kete akses menjehere.', ARRAY['shofer', 'shtoj', 'krijo', 'ri', 'driver', 'shofere'], 9),
('Kompania', 'Si te fshij nje shofer?', 'Nuk rekomandojme fshirjen e shofereve per arsye te ruajtjes se historikut. Ne vend te fshirjes, mund ta caktivizoni shoferin qe te mos kete me akses.', ARRAY['fshij', 'shofer', 'largo', 'hiq', 'elimino'], 7),
('Kompania', 'Si te ndryshoj te dhenat e kompanise?', 'Shkoni te cilesimet e kompanise (ikona e rrotulles). Aty mund te ndryshoni emrin, adresen, numrin e telefonit, dhe logon e kompanise.', ARRAY['kompani', 'ndrysho', 'te dhena', 'emri', 'adresa', 'cilesime'], 7),
('Kompania', 'Sa depo mund te kem?', 'Numri i depove varet nga plani juaj i abonimit. Plani Standard lejon deri ne 5 depo, ndersa plani Premium nuk ka kufizim.', ARRAY['sa', 'depo', 'maksimum', 'limit', 'kufizim', 'plan'], 6),
('Kompania', 'Sa shofere mund te kem?', 'Numri i shofereve varet nga plani juaj. Plani Standard lejon deri ne 10 shofere, ndersa plani Premium lejon shofere te pakufizuar.', ARRAY['sa', 'shofere', 'maksimum', 'limit', 'kufizim', 'plan'], 6),
('Kompania', 'Si te menaxhoj kategorite e produkteve?', 'Shkoni te "Kategorite" ne menu. Mund te shtoni kategori te reja, ndryshoni emrat, ose fshini kategorite qe nuk perdoren me.', ARRAY['kategori', 'produkt', 'menaxho', 'shtoj', 'ndrysho'], 7),
('Kompania', 'Si te shoh raportet e kompanise?', 'Shkoni te "Raportet" ne menu. Aty do te gjeni statistika per stokun, dergesa, dhe performancen e shofereve.', ARRAY['raport', 'statistik', 'performanc', 'analiz'], 7),
('Kompania', 'Cfare eshte fletedergesa?', 'Fletedergesa eshte dokumenti qe percjell mallin gjate transportit. Permban informacione per derguesin, marresin, sasite, dhe gjendjen e mallit.', ARRAY['fletedergesa', 'dokument', 'transport', 'mall', 'dergese'], 8),
('Kompania', 'Si te krijoj nje fletedergese?', 'Shkoni te "Fletedergesat" dhe klikoni "+ Krijo Fletedergese". Plotesoni adresen e mbledhjes/dergeses, shtoni artikujt, dhe caktoni shoferin.', ARRAY['fletedergese', 'krijo', 'shtoj', 'reja'], 9),
('Kompania', 'Si te caktoj nje shofer per fletedergesen?', 'Kur krijoni ose ndryshoni nje fletedergese, zgjidhni shoferin nga lista rrenese "Shoferi i Caktuar". Shoferi do te njoftohet automatikisht.', ARRAY['cakto', 'shofer', 'fletedergese', 'dergese'], 8),
('Kompania', 'Si te shoh statusin e nje fletedergese?', 'Ne listen e fletedergesave, secila ka nje etiketim me ngjyre qe tregon statusin: Draft (gri), Derguar (blu), Ne Tranzit (portokalli), Dorezuar (jeshil).', ARRAY['status', 'fletedergese', 'gjendja', 'progres', 'ndjek'], 8),
('Kompania', 'Si te menaxhoj stokun?', 'Shkoni te "Stoku" ne menu. Aty shihni sasine aktuale per cdo kategori ne cdo depo. Mund te filtroni sipas deposese ose kategorise.', ARRAY['stok', 'menaxho', 'sasi', 'inventar', 'gjendje'], 8),
('Kompania', 'Pse stoku im nuk perditsohet?', 'Stoku perditsohet automatikisht kur regjistrohen levizje ne depo (pranim, dergese, riparim). Sigurohuni qe punetoret e depove po regjistrojne levizjet sakte.', ARRAY['stok', 'perditsoj', 'nuk', 'gabim', 'problem', 'sasi'], 7),
('Kompania', 'Si te dergoj dokumente?', 'Shkoni te "Dokumentet" ne menu. Klikoni "+ Dergo Dokument", zgjidhni skedarin, plotesoni titullin, dhe zgjidhni marresit.', ARRAY['dokument', 'dergo', 'skedar', 'file', 'ngarko'], 8),
('Kompania', 'Kush mund te shoh dokumentet e mia?', 'Dokumentet shihen vetem nga derguesit dhe marresit e caktuar. Askush tjeter nuk ka akses ne dokumentet tuaja.', ARRAY['dokument', 'shoh', 'akses', 'privatesi', 'kush'], 6),
('Kompania', 'Si te caktivizoj nje punetor depoje?', 'Shkoni te "Depoiste", zgjidhni depon, dhe ne listen e punetoreve gjeni punetorin. Klikoni butonin e caktivizimit prane emrit te tij.', ARRAY['caktivizo', 'punetor', 'depo', 'largo', 'hiq'], 6),
('Kompania', 'Si te shoh historikun e levizjeve te stokut?', 'Ne faqen e Stokut, klikoni mbi nje kategori per te pare historikun e plote te levizjeve: hyrje, dalje, dhe riparime.', ARRAY['historik', 'levizje', 'stok', 'hyrje', 'dalje'], 6),
('Kompania', 'A mund te eksportoj raportet?', 'Aktualisht raportet mund te shihen ne platform. Funksioni i eksportimit ne PDF/Excel do te shtohet se shpejti.', ARRAY['eksporto', 'raport', 'pdf', 'excel', 'shkarko', 'printo'], 5),
('Kompania', 'Si te ndryshoj menaxherin e nje depoje?', 'Shkoni te "Depoiste", klikoni mbi depon, dhe ne cilesimet e depoje ndryshoni menaxherin nga lista e punetoreve.', ARRAY['menaxher', 'depo', 'ndrysho', 'cakto'], 6),
('Kompania', 'Cfare ndodh kur skadon abonimim?', 'Kur skadon abonimi, llogaria kalon ne gjendje te kufizuar. Mund te shihni te dhenat por nuk mund te shtoni te reja. Rinovoni abonimin per akses te plote.', ARRAY['abonim', 'skadon', 'skaduese', 'rinovim', 'plan'], 8),
('Kompania', 'Si te rinovoj abonimin?', 'Shkoni te Cilesimet e llogarise dhe zgjidhni "Abonimi". Aty mund te rinovoni ose ndryshoni planin tuaj te abonimit.', ARRAY['rinovoj', 'abonim', 'plan', 'pages', 'vazhdo'], 8),
('Kompania', 'Cfare plani me duhet?', 'Plani Free Trial eshte per te provuar platformen. Standard eshte per kompani te vogla (deri 5 depo, 10 shofere). Premium eshte per kompani te medha pa kufizime.', ARRAY['plan', 'abonim', 'cili', 'zgjedh', 'dallim', 'krahaso'], 7),
('Kompania', 'A mund te kaloj nga nje plan ne tjetrin?', 'Po, mund te ndryshoni planin ne cdo kohe. Nese kaloni ne nje plan me te larte, diferenca e pageses llogaritet proportionalisht.', ARRAY['plan', 'kalo', 'ndrysho', 'upgrade', 'downgrade'], 6),
('Kompania', 'Si te fshij nje kategori produkti?', 'Shkoni te "Kategorite", gjeni kategorine, dhe klikoni butonin e fshirjes. Kujdes: nuk mund te fshini kategori qe kane stok aktiv.', ARRAY['fshij', 'kategori', 'produkt', 'hiq', 'elimino'], 6),
('Kompania', 'Si te kontrolloj sasine e paletave ne depo?', 'Shkoni te "Stoku" dhe filtroni sipas depoje. Do te shihni sasine aktuale per cdo kategori paletash ne ate depo specifike.', ARRAY['sasi', 'paletave', 'paleta', 'depo', 'kontroll', 'stok'], 8),
('Kompania', 'A mund te perdor platformen per produkte te tjera pervec paletave?', 'Platforma eshte projektuar kryesisht per menaxhimin e paletave, por mund te krijoni kategori per cdo lloj produkti qe transportoni.', ARRAY['produkt', 'tjeter', 'paleta', 'lloj', 'kategori'], 5),
('Kompania', 'Si funksionon chat-i i kompanise?', 'Chat-i lejon komunikimin mes te gjithe stafit te kompanise: administratoret, punetoret e depove, dhe shoferet. Mund te krijoni biseda private ose grupe.', ARRAY['chat', 'bisede', 'komunikim', 'mesazh'], 8),
('Kompania', 'Si te shtoj nje punetor ne depo?', 'Punetoret e depove shtohen nga administratori i kompanise. Shkoni te "Depoiste", zgjidhni depon, dhe klikoni "Shto Punetor".', ARRAY['punetor', 'depo', 'shtoj', 'krijo'], 8),
('Kompania', 'A mund te kam disa administratore?', 'Aktualisht cdo kompani ka nje administrator kryesor. Per nevoja specifike, kontaktoni suportin teknik.', ARRAY['disa', 'administrator', 'shume', 'admin'], 5),
('Kompania', 'Si te shoh faturat e pageses?', 'Faturat e pageses jane te disponueshme ne seksionin e abonimit ne cilesimet e llogarise. Mund ti shkarkoni ne format PDF.', ARRAY['fature', 'pages', 'fatura', 'shkarko', 'pdf'], 6),
('Kompania', 'Cfare eshte prova falas?', 'Prova falas ju lejon te perdorni platformen per 14 dite pa pagese. Pas ketij afati, duhet te zgjidhni nje plan me pagese per te vazhduar.', ARRAY['prove', 'falas', 'trial', 'dite', 'afat'], 8),
('Kompania', 'A humbasin te dhenat kur skadon prova falas?', 'Jo, te dhenat tuaja ruhen edhe pas skadimit te proves falas. Kur aktivizoni nje plan me pagese, do te keni akses ne te gjitha te dhenat e meparshme.', ARRAY['te dhena', 'humb', 'prove', 'skadon', 'ruaj'], 8),
('Kompania', 'Si te ngarkoj logon e kompanise?', 'Shkoni te Cilesimet e kompanise dhe klikoni mbi zonen e logos. Zgjidhni nje imazh ne format PNG ose JPG. Logo do te shfaqet ne te gjitha dokumentet.', ARRAY['logo', 'ngarko', 'imazh', 'kompani', 'fotografi'], 5),
('Kompania', 'A mund te fshij kompanine?', 'Fshirja e kompanise behet vetem nga super admini. Kontaktoni suportin teknik per kete kerkese. Te dhenat do te ruhen per 30 dite perpara fshirjes perfundimtare.', ARRAY['fshij', 'kompani', 'mbyll', 'elimino', 'largo'], 5)
ON CONFLICT DO NOTHING;