/*
  # Expand location catalog: EU + Balkans countries and major cities

  1. Data
    - Insert ~34 additional European/Balkan countries (idempotent via NOT EXISTS).
    - Insert major cities per country (top capital + 5–7 large cities per country).
    - All inserts use NOT EXISTS guards so re-running is safe and the existing 12
      countries / 62 cities are preserved without duplication.

  2. Coverage
    - Existing: AL, AT, BE, CH, DE, FR, HR, IT, MK, NL, RS, XK
    - Added: AD, BA, BG, BY, CY, CZ, DK, EE, ES, FI, GB, GR, HU, IE, IS, LI, LT,
      LU, LV, MC, MD, ME, MT, NO, PL, PT, RO, SE, SI, SK, SM, TR, UA, RU
    - For existing countries, additional major cities are added where missing.

  3. Security
    - No schema changes; tables already have RLS enabled with public read.
*/

-- 1. Countries (insert only when missing)
INSERT INTO countries (name, code, flag_emoji, region)
SELECT v.name, v.code, v.flag_emoji, v.region
FROM (VALUES
  ('Andorra', 'AD', '🇦🇩', 'Western Europe'),
  ('Bosnia and Herzegovina', 'BA', '🇧🇦', 'Balkans'),
  ('Bulgaria', 'BG', '🇧🇬', 'Eastern Europe'),
  ('Belarus', 'BY', '🇧🇾', 'Eastern Europe'),
  ('Cyprus', 'CY', '🇨🇾', 'Southern Europe'),
  ('Czech Republic', 'CZ', '🇨🇿', 'Central Europe'),
  ('Denmark', 'DK', '🇩🇰', 'Northern Europe'),
  ('Estonia', 'EE', '🇪🇪', 'Northern Europe'),
  ('Spain', 'ES', '🇪🇸', 'Southern Europe'),
  ('Finland', 'FI', '🇫🇮', 'Northern Europe'),
  ('United Kingdom', 'GB', '🇬🇧', 'Western Europe'),
  ('Greece', 'GR', '🇬🇷', 'Southern Europe'),
  ('Hungary', 'HU', '🇭🇺', 'Central Europe'),
  ('Ireland', 'IE', '🇮🇪', 'Western Europe'),
  ('Iceland', 'IS', '🇮🇸', 'Northern Europe'),
  ('Liechtenstein', 'LI', '🇱🇮', 'Western Europe'),
  ('Lithuania', 'LT', '🇱🇹', 'Northern Europe'),
  ('Luxembourg', 'LU', '🇱🇺', 'Western Europe'),
  ('Latvia', 'LV', '🇱🇻', 'Northern Europe'),
  ('Monaco', 'MC', '🇲🇨', 'Western Europe'),
  ('Moldova', 'MD', '🇲🇩', 'Eastern Europe'),
  ('Montenegro', 'ME', '🇲🇪', 'Balkans'),
  ('Malta', 'MT', '🇲🇹', 'Southern Europe'),
  ('Norway', 'NO', '🇳🇴', 'Northern Europe'),
  ('Poland', 'PL', '🇵🇱', 'Central Europe'),
  ('Portugal', 'PT', '🇵🇹', 'Southern Europe'),
  ('Romania', 'RO', '🇷🇴', 'Eastern Europe'),
  ('Russia', 'RU', '🇷🇺', 'Eastern Europe'),
  ('Sweden', 'SE', '🇸🇪', 'Northern Europe'),
  ('Slovenia', 'SI', '🇸🇮', 'Central Europe'),
  ('Slovakia', 'SK', '🇸🇰', 'Central Europe'),
  ('San Marino', 'SM', '🇸🇲', 'Southern Europe'),
  ('Turkey', 'TR', '🇹🇷', 'Southern Europe'),
  ('Ukraine', 'UA', '🇺🇦', 'Eastern Europe')
) AS v(name, code, flag_emoji, region)
WHERE NOT EXISTS (SELECT 1 FROM countries c WHERE upper(c.code) = upper(v.code));

-- 2. Cities (insert only when missing per country)
INSERT INTO cities (country_id, name, admin_area)
SELECT c.id, v.name, v.admin_area
FROM countries c
JOIN (VALUES
  -- Germany (extra major hubs)
  ('DE', 'Stuttgart', 'Baden-Württemberg'),
  ('DE', 'Düsseldorf', 'Nordrhein-Westfalen'),
  ('DE', 'Leipzig', 'Sachsen'),
  ('DE', 'Hannover', 'Niedersachsen'),
  ('DE', 'Nürnberg', 'Bayern'),
  ('DE', 'Bremen', 'Bremen'),
  ('DE', 'Dortmund', 'Nordrhein-Westfalen'),
  ('DE', 'Essen', 'Nordrhein-Westfalen'),
  ('DE', 'Dresden', 'Sachsen'),
  -- Austria extras
  ('AT', 'Innsbruck', 'Tirol'),
  ('AT', 'Klagenfurt', 'Kärnten'),
  -- Switzerland extras
  ('CH', 'Lausanne', 'Vaud'),
  ('CH', 'Lugano', 'Ticino'),
  -- France extras
  ('FR', 'Bordeaux', 'Nouvelle-Aquitaine'),
  ('FR', 'Nantes', 'Pays de la Loire'),
  ('FR', 'Strasbourg', 'Grand Est'),
  -- Italy extras
  ('IT', 'Bologna', 'Emilia-Romagna'),
  ('IT', 'Florence', 'Toscana'),
  -- Netherlands extras
  ('NL', 'Eindhoven', 'Noord-Brabant'),
  ('NL', 'Groningen', 'Groningen'),
  -- Belgium extras
  ('BE', 'Liège', 'Wallonia'),
  ('BE', 'Bruges', 'Flanders'),
  -- Albania extras
  ('AL', 'Berat', 'Berat'),
  ('AL', 'Korçë', 'Korçë'),
  -- Kosovo extras
  ('XK', 'Mitrovicë', 'Mitrovicë'),
  ('XK', 'Pejë', 'Pejë'),
  -- North Macedonia extras
  ('MK', 'Tetovo', 'Tetovo'),
  -- Croatia extras
  ('HR', 'Zadar', 'Zadar'),
  -- Serbia extras
  ('RS', 'Subotica', 'Vojvodina'),
  -- New countries
  ('AD', 'Andorra la Vella', 'Andorra la Vella'),
  ('AD', 'Escaldes-Engordany', 'Escaldes-Engordany'),
  ('AD', 'Encamp', 'Encamp'),
  ('BA', 'Sarajevo', 'Federation of BiH'),
  ('BA', 'Banja Luka', 'Republika Srpska'),
  ('BA', 'Tuzla', 'Federation of BiH'),
  ('BA', 'Mostar', 'Federation of BiH'),
  ('BA', 'Zenica', 'Federation of BiH'),
  ('BG', 'Sofia', 'Sofia City'),
  ('BG', 'Plovdiv', 'Plovdiv'),
  ('BG', 'Varna', 'Varna'),
  ('BG', 'Burgas', 'Burgas'),
  ('BG', 'Ruse', 'Ruse'),
  ('BY', 'Minsk', 'Minsk'),
  ('BY', 'Gomel', 'Gomel'),
  ('BY', 'Brest', 'Brest'),
  ('BY', 'Vitebsk', 'Vitebsk'),
  ('CY', 'Nicosia', 'Nicosia'),
  ('CY', 'Limassol', 'Limassol'),
  ('CY', 'Larnaca', 'Larnaca'),
  ('CY', 'Paphos', 'Paphos'),
  ('CZ', 'Prague', 'Prague'),
  ('CZ', 'Brno', 'South Moravia'),
  ('CZ', 'Ostrava', 'Moravian-Silesian'),
  ('CZ', 'Plzeň', 'Plzeň'),
  ('CZ', 'Liberec', 'Liberec'),
  ('DK', 'Copenhagen', 'Capital'),
  ('DK', 'Aarhus', 'Central Jutland'),
  ('DK', 'Odense', 'Southern Denmark'),
  ('DK', 'Aalborg', 'North Jutland'),
  ('DK', 'Esbjerg', 'Southern Denmark'),
  ('EE', 'Tallinn', 'Harju'),
  ('EE', 'Tartu', 'Tartu'),
  ('EE', 'Narva', 'Ida-Viru'),
  ('EE', 'Pärnu', 'Pärnu'),
  ('ES', 'Madrid', 'Madrid'),
  ('ES', 'Barcelona', 'Catalonia'),
  ('ES', 'Valencia', 'Valencia'),
  ('ES', 'Seville', 'Andalusia'),
  ('ES', 'Zaragoza', 'Aragon'),
  ('ES', 'Málaga', 'Andalusia'),
  ('ES', 'Bilbao', 'Basque Country'),
  ('FI', 'Helsinki', 'Uusimaa'),
  ('FI', 'Espoo', 'Uusimaa'),
  ('FI', 'Tampere', 'Pirkanmaa'),
  ('FI', 'Turku', 'Southwest Finland'),
  ('FI', 'Oulu', 'North Ostrobothnia'),
  ('GB', 'London', 'England'),
  ('GB', 'Manchester', 'England'),
  ('GB', 'Birmingham', 'England'),
  ('GB', 'Edinburgh', 'Scotland'),
  ('GB', 'Glasgow', 'Scotland'),
  ('GB', 'Liverpool', 'England'),
  ('GB', 'Cardiff', 'Wales'),
  ('GB', 'Belfast', 'Northern Ireland'),
  ('GR', 'Athens', 'Attica'),
  ('GR', 'Thessaloniki', 'Central Macedonia'),
  ('GR', 'Patras', 'Western Greece'),
  ('GR', 'Heraklion', 'Crete'),
  ('GR', 'Larissa', 'Thessaly'),
  ('HU', 'Budapest', 'Budapest'),
  ('HU', 'Debrecen', 'Hajdú-Bihar'),
  ('HU', 'Szeged', 'Csongrád'),
  ('HU', 'Miskolc', 'Borsod-Abaúj-Zemplén'),
  ('HU', 'Pécs', 'Baranya'),
  ('IE', 'Dublin', 'Leinster'),
  ('IE', 'Cork', 'Munster'),
  ('IE', 'Galway', 'Connacht'),
  ('IE', 'Limerick', 'Munster'),
  ('IE', 'Waterford', 'Munster'),
  ('IS', 'Reykjavík', 'Capital Region'),
  ('IS', 'Akureyri', 'Northeast'),
  ('IS', 'Hafnarfjörður', 'Capital Region'),
  ('LI', 'Vaduz', 'Vaduz'),
  ('LI', 'Schaan', 'Schaan'),
  ('LT', 'Vilnius', 'Vilnius'),
  ('LT', 'Kaunas', 'Kaunas'),
  ('LT', 'Klaipėda', 'Klaipėda'),
  ('LT', 'Šiauliai', 'Šiauliai'),
  ('LU', 'Luxembourg City', 'Luxembourg'),
  ('LU', 'Esch-sur-Alzette', 'Esch-sur-Alzette'),
  ('LU', 'Differdange', 'Esch-sur-Alzette'),
  ('LV', 'Riga', 'Riga'),
  ('LV', 'Daugavpils', 'Latgale'),
  ('LV', 'Liepāja', 'Kurzeme'),
  ('LV', 'Jelgava', 'Zemgale'),
  ('MC', 'Monaco', 'Monaco'),
  ('MC', 'Monte Carlo', 'Monaco'),
  ('MD', 'Chișinău', 'Chișinău'),
  ('MD', 'Tiraspol', 'Transnistria'),
  ('MD', 'Bălți', 'Bălți'),
  ('ME', 'Podgorica', 'Podgorica'),
  ('ME', 'Nikšić', 'Nikšić'),
  ('ME', 'Herceg Novi', 'Herceg Novi'),
  ('ME', 'Budva', 'Budva'),
  ('MT', 'Valletta', 'Malta'),
  ('MT', 'Birkirkara', 'Malta'),
  ('MT', 'Sliema', 'Malta'),
  ('MT', 'Victoria', 'Gozo'),
  ('NO', 'Oslo', 'Oslo'),
  ('NO', 'Bergen', 'Vestland'),
  ('NO', 'Trondheim', 'Trøndelag'),
  ('NO', 'Stavanger', 'Rogaland'),
  ('NO', 'Tromsø', 'Troms'),
  ('PL', 'Warsaw', 'Mazovia'),
  ('PL', 'Kraków', 'Lesser Poland'),
  ('PL', 'Łódź', 'Łódź'),
  ('PL', 'Wrocław', 'Lower Silesia'),
  ('PL', 'Poznań', 'Greater Poland'),
  ('PL', 'Gdańsk', 'Pomerania'),
  ('PL', 'Katowice', 'Silesia'),
  ('PT', 'Lisbon', 'Lisbon'),
  ('PT', 'Porto', 'Porto'),
  ('PT', 'Braga', 'Braga'),
  ('PT', 'Coimbra', 'Coimbra'),
  ('PT', 'Faro', 'Algarve'),
  ('RO', 'Bucharest', 'Bucharest'),
  ('RO', 'Cluj-Napoca', 'Cluj'),
  ('RO', 'Timișoara', 'Timiș'),
  ('RO', 'Iași', 'Iași'),
  ('RO', 'Constanța', 'Constanța'),
  ('RO', 'Brașov', 'Brașov'),
  ('RU', 'Moscow', 'Moscow'),
  ('RU', 'Saint Petersburg', 'Saint Petersburg'),
  ('RU', 'Novosibirsk', 'Novosibirsk'),
  ('RU', 'Yekaterinburg', 'Sverdlovsk'),
  ('RU', 'Kazan', 'Tatarstan'),
  ('SE', 'Stockholm', 'Stockholm'),
  ('SE', 'Gothenburg', 'Västra Götaland'),
  ('SE', 'Malmö', 'Skåne'),
  ('SE', 'Uppsala', 'Uppsala'),
  ('SE', 'Västerås', 'Västmanland'),
  ('SI', 'Ljubljana', 'Central Slovenia'),
  ('SI', 'Maribor', 'Drava'),
  ('SI', 'Celje', 'Savinja'),
  ('SI', 'Kranj', 'Upper Carniola'),
  ('SK', 'Bratislava', 'Bratislava'),
  ('SK', 'Košice', 'Košice'),
  ('SK', 'Prešov', 'Prešov'),
  ('SK', 'Žilina', 'Žilina'),
  ('SM', 'San Marino', 'San Marino'),
  ('SM', 'Serravalle', 'Serravalle'),
  ('TR', 'Istanbul', 'Istanbul'),
  ('TR', 'Ankara', 'Ankara'),
  ('TR', 'Izmir', 'Izmir'),
  ('TR', 'Bursa', 'Bursa'),
  ('TR', 'Antalya', 'Antalya'),
  ('TR', 'Adana', 'Adana'),
  ('UA', 'Kyiv', 'Kyiv'),
  ('UA', 'Kharkiv', 'Kharkiv'),
  ('UA', 'Odesa', 'Odesa'),
  ('UA', 'Dnipro', 'Dnipropetrovsk'),
  ('UA', 'Lviv', 'Lviv')
) AS v(country_code, name, admin_area)
  ON upper(c.code) = upper(v.country_code)
WHERE NOT EXISTS (
  SELECT 1 FROM cities x WHERE x.country_id = c.id AND lower(x.name) = lower(v.name)
);
