/*
  # Seed Support FAQs - Part 4 (Additional entries to reach ~300)

  Adds 30 more FAQ entries for edge cases and common scenarios
*/

INSERT INTO support_faqs (category, question, answer, keywords, priority) VALUES
('Platforma', 'Si te shoh numrin total te paletave?', 'Ne Dashboard shfaqet numri total i paletave per te gjithe depote. Per detaje, shkoni te "Stoku" ku ndahen sipas kategorise dhe depoje.', ARRAY['total', 'paleta', 'numri', 'sasi', 'stok', 'gjithe'], 7),
('Platforma', 'A mund te kerkoj ne te gjithe platformen?', 'Cdo seksion ka funksionin e vet te kerkimit. Perdorni filtrat ne secilen faqe per te gjetur informacionin qe kerkoni.', ARRAY['kerko', 'gjej', 'filtro', 'platforma', 'gjithe'], 5),
('Kompania', 'Si te gjurmoj nje dergese ne kohe reale?', 'Statusin e dergeses e shihni ne "Fletedergesat". Kur shoferi ndryshon statusin (Ne Tranzit, Dorezuar), ju njoftoheni menjehere.', ARRAY['gjurmo', 'dergese', 'reale', 'kohe', 'ndjek', 'live'], 8),
('Kompania', 'A mund te caktoj disa shofere per nje dergese?', 'Aktualisht secila fletedergese caktohet per nje shofer. Per dergesa te medha, krijoni fletedergesa te ndara per cdo shofer.', ARRAY['disa', 'shofere', 'dergese', 'fletedergese', 'cakto'], 5),
('Kompania', 'Si te shoh kush ka akses ne cfare?', 'Cdo rol ka leje te percaktuara: Adminit i sheh gjithe, punetorit depoje vetem depon e tij, shoferit vetem dergesat e tij.', ARRAY['akses', 'leje', 'rol', 'kush', 'shoh'], 6),
('Depo', 'Si te bej inventarizim ne depo?', 'Krahasoni stokun ne sistem me stokun fizik ne depo. Nese ka ndryshime, njoftoni administratorin per korrigjim.', ARRAY['inventarizim', 'numrim', 'kontroll', 'depo', 'fizik', 'stok'], 7),
('Depo', 'Cfare te bej kur marr paleta te padokezuara?', 'Kontaktoni menjehere administratorin permes chat-it. Mos i pranoni paletat pa konfirmim nga administratori. Dokumentoni me foto.', ARRAY['padokezuar', 'paleta', 'papritur', 'gabim', 'njoftoj'], 8),
('Shoferet', 'Si te verifikoj identitetin e marresit?', 'Kerkoni dokumentin e identifikimit ose numrin e porosise nga marresi. Krahasoni me informacionin ne fletedergese.', ARRAY['identitet', 'marresi', 'verifiko', 'kontroll', 'dokument'], 7),
('Shoferet', 'Cfare dokumentesh duhet te kem me vete?', 'Gjithmone keni me vete: patenten, lejen e qarkullimit, sigurimin, dhe kopjen e fletedergeses qe po transportoni.', ARRAY['dokument', 'kem', 'patent', 'leje', 'sigurim', 'shofer'], 7),
('Shoferet', 'Si te njoftoj per vonese te shkaktuar nga moti?', 'Njoftoni administratorin permes chat-it per situaten e motit. Mos rrezikoni sigurine tuaj - eshte me mire te vonoheni sesa te keni aksident.', ARRAY['mot', 'vonese', 'shi', 'bore', 'rruge', 'siguri'], 8),
('Teknike', 'Pse nuk me ngarkohet dashboard-i?', 'Provoni: 1) Rifreskoni (F5), 2) Pastroni cache, 3) Kontrolloni internetin. Dashboard kerkon lidhje aktive per te shfaqur te dhenat ne kohe reale.', ARRAY['dashboard', 'ngarko', 'nuk', 'problem', 'zbrazet'], 8),
('Teknike', 'Si te korrigjoj gabimin "Network Error"?', 'Ky gabim tregon problem me lidhjen e internetit. Kontrolloni Wi-Fi/te dhenat celulare. Nese interneti funksionon, provoni perseri pas disa minutave.', ARRAY['network', 'error', 'gabim', 'rrjet', 'lidhje', 'internet'], 8),
('Pagesa', 'A mund te ndryshoj planin gjate proves falas?', 'Po, mund te zgjidhni nje plan tjeter gjate proves falas. Pagesa do te filloje vetem kur te perfundoje periudha falas.', ARRAY['ndrysho', 'plan', 'prove', 'falas', 'trial', 'gjate'], 6),
('Pagesa', 'A ka garanci kthimi parash?', 'Po, ofrojme garanci kthimi parash per 30 ditet e para pas abonimit me pagese. Kontaktoni suportin per te filluar procesin.', ARRAY['garanci', 'kthim', 'para', 'rimbursim', '30', 'dite'], 7),
('Siguria', 'Si te njoh nje email mashtrues (phishing)?', 'Emailet mashtrues zakonisht: kane gabime drejtshkrimores, kerkojne fjalekalimin, kane linke te dyshimta. Platforma jone nuk kerkon kurre fjalekalimin me email.', ARRAY['phishing', 'mashtrues', 'email', 'njoh', 'dallohi', 'rreme'], 8),
('Siguria', 'A mund te perdor te njejtin fjalekalim per llogari te tjera?', 'Nuk rekomandohet. Perdorni fjalekalim unik per platformen. Nese nje llogari tjeter kompromentohet, platforma juaj mbetet e sigurt.', ARRAY['njejt', 'fjalekalim', 'tjeter', 'llogari', 'unik', 'i njejte'], 6),
('Llogaria', 'Si te shoh profilet e kolegeve?', 'Ne Chat, mund te shihni foton dhe emrin e kolegeve. Per informacion me te detajuar, kontaktoni administratorin.', ARRAY['profil', 'kolege', 'shoh', 'informacion', 'staf'], 4),
('Llogaria', 'A mund te ndryshoj rolin tim?', 'Jo, rolet caktohen nga administratori i kompanise. Nese mendoni se keni rolin e gabuar, kontaktoni administratorin per korrigjim.', ARRAY['rol', 'ndrysho', 'ndryshoj', 'cakto', 'gabuar'], 5),
('Kompania', 'Si te importoj te dhena ekzistuese?', 'Aktualisht importimi i te dhenave behet manualisht. Per sasi te medha te dhenash, kontaktoni suportin teknik per ndihme.', ARRAY['importo', 'te dhena', 'ekzistues', 'migro', 'transfero', 'ngarko'], 5),
('Kompania', 'A mund te shoh aktivitetin e shofereve?', 'Ne seksionin "Shoferet" shihni statusin aktual te secilit shofer. Ne "Fletedergesat" shihni historikun e plotete dergesave te tyre.', ARRAY['aktivitet', 'shofer', 'ndjek', 'gjurmo', 'status'], 7),
('Depo', 'A mund te pranoj paleta jashtë orarit?', 'Pranimet mund te regjistrohen ne cdo kohe ne sistem. Sigurohuni qe regjistroni sasine dhe gjendjen saktesisht pavaresisht ores.', ARRAY['orar', 'jashte', 'pranim', 'kohe', 'nate', 'fundavje'], 5),
('Depo', 'Si te menaxhoj kthimet e paletave?', 'Kthimet regjistrohen si pranim i ri ne depo. Shenoni ne fushen e shenimeve qe behet fjale per kthim dhe nga kush erdhen.', ARRAY['kthim', 'paleta', 'rikthim', 'pranoj', 'regjistro'], 7),
('Chat', 'A ruhen mesazhet e fshira?', 'Mesazhet e fshira shenohen si "te fshira" por nuk zhduken plotesisht nga sistemi per arsye kontrolli. Pala te tjera shohin "Mesazh i fshire".', ARRAY['ruaj', 'fshij', 'mesazh', 'fshire', 'arkiv'], 5),
('Chat', 'Si te dergoj lokacionin ne chat?', 'Aktualisht nuk ka mundesi per te derguar lokacionin direkt ne chat. Mund te shkruani adresen si mesazh tekst ose te dergoni screenshot te hartes.', ARRAY['lokacion', 'vendndodhje', 'harte', 'gps', 'dergo', 'chat'], 4),
('Teknike', 'Pse shoh faqe te bardhe kur hyj?', 'Provoni: 1) Pastroni cache, 2) Caktivizoni shtesa te shfletuesit, 3) Provoni shfletues tjeter. Nese vazhdon, kontaktoni suportin.', ARRAY['bardhe', 'faqe', 'bosh', 'zbrazet', 'nuk', 'ngarko'], 9),
('Teknike', 'Si te di nese ka nderprerje te sherbimit?', 'Nderprerjene njoftohen permes emailit dhe njoftimeve ne platforme. Gjithashtu mund te kontrolloni chat-in e suportit per informata.', ARRAY['nderprerje', 'sherbim', 'offline', 'pushim', 'problem'], 6),
('Platforma', 'A mund te perdor platformen per transport nderkombetar?', 'Po, platforma suporton cdo lloj transporti paletash. Kategorizoni dergjesat nderkombetare me shenime te pershtatura.', ARRAY['nderkombetar', 'transport', 'eksport', 'import', 'jashte'], 5),
('Platforma', 'Si te mesoj me shpejt funksionet e platformes?', 'Filloni me funksionet baze: shikoni stokun, krijoni fletedergese, perdorni chat-in. Chat-i i suportit pergjigjet per cdo pyetje specifike.', ARRAY['mesoj', 'shpejt', 'filloj', 'baze', 'tutorial', 'ndihme'], 7),
('Platforma', 'A ka mundesi per brende te personalizuar?', 'Mund te ngarkoni logon e kompanise qe shfaqet ne platform. Per personalizim te avancuar, kontaktoni ekipin tone.', ARRAY['brende', 'personalizo', 'logo', 'dizajn', 'ngjyre'], 4),
('Platforma', 'Si te kontaktoj ekipin e zhvillimit?', 'Perdorni chat-in e suportit per cdo sugjerim ose kerkese. Mesazhet qe kerkojne nderhyrje te ekipit percillen automatikisht.', ARRAY['kontakt', 'zhvillim', 'ekip', 'sugjerim', 'kerkese', 'developer'], 5);
