/*
  # Seed Default Email Templates

  Mbush `email_templates` me 12 template-t e ngurta ekzistuese (marre nga
  send-email/index.ts), ne tri gjuhet sq/de/en. Te gjitha shenohen me
  is_system=true per te mbrojtur nga fshirja aksidentale.
*/

INSERT INTO public.email_templates (
  code, category, name, description, is_system, is_active,
  preheader_sq, preheader_de, preheader_en,
  subject_sq, subject_de, subject_en,
  heading_sq, heading_de, heading_en,
  intro_sq, intro_de, intro_en,
  body_html_sq, body_html_de, body_html_en,
  cta_label_sq, cta_label_de, cta_label_en,
  cta_url, variables
) VALUES
(
  'welcome_company', 'transactional', 'Mireseerdhje - Kompani e re',
  'Dergohet kur krijohet nje kompani e re dhe admini i pare.', true, true,
  'Llogaria per {{company_name}} u krijua me sukses.',
  'Konto fur {{company_name}} wurde erstellt.',
  'Account for {{company_name}} has been created.',
  'Mireseerdhet ne {{brand_name}}',
  'Willkommen bei {{brand_name}}',
  'Welcome to {{brand_name}}',
  'Mireseerdhet, {{full_name}}!',
  'Willkommen, {{full_name}}!',
  'Welcome, {{full_name}}!',
  'Llogaria per <strong>{{company_name}}</strong> u krijua me sukses. Mund te kyceni dhe te nisni punen menjehere.',
  'Das Konto fur <strong>{{company_name}}</strong> wurde erfolgreich angelegt.',
  'Your account for <strong>{{company_name}}</strong> is ready.',
  '<p>Ekipi juaj tani ka akses ne: panelin e kompanise, menaxhim shoferesh, dergesa, depot dhe raporte.</p>',
  '<p>Ihr Team hat nun Zugriff auf das Dashboard, Fahrer-Management, Lieferungen und mehr.</p>',
  '<p>Your team now has access to the dashboard, driver management, deliveries, depots and reports.</p>',
  'Hap panelin', 'Dashboard offnen', 'Open dashboard',
  '{{app_base_url}}/',
  '["full_name","company_name","brand_name","app_base_url"]'::jsonb
),
(
  'invite_user', 'transactional', 'Ftese perdoruesi',
  'Dergohet kur admini shton nje perdorues te ri ne kompani.', true, true,
  'Vendosni fjalekalimin per te hyre.',
  'Legen Sie Ihr Passwort fest.',
  'Set your password to sign in.',
  '{{inviter_name}} ju ftoi ne {{company_name}}',
  '{{inviter_name}} hat Sie zu {{company_name}} eingeladen',
  '{{inviter_name}} invited you to {{company_name}}',
  'Ju jeni ftuar ne {{brand_name}}',
  'Sie wurden eingeladen',
  'You have been invited',
  'Pershendetje {{full_name}}, {{inviter_name}} ju ftoi si <strong>{{role_label}}</strong> ne {{company_name}}.',
  'Hallo {{full_name}}, {{inviter_name}} hat Sie als <strong>{{role_label}}</strong> zu {{company_name}} eingeladen.',
  'Hi {{full_name}}, {{inviter_name}} invited you to {{company_name}} as <strong>{{role_label}}</strong>.',
  '<p>Klikoni butonin me poshte per te vendosur fjalekalimin tuaj dhe per te hyre.</p>',
  '<p>Klicken Sie unten, um Ihr Passwort festzulegen.</p>',
  '<p>Click below to set your password and sign in.</p>',
  'Vendos fjalekalimin', 'Passwort festlegen', 'Set password',
  '{{setup_url}}',
  '["full_name","company_name","role_label","inviter_name","setup_url","brand_name"]'::jsonb
),
(
  'password_reset', 'transactional', 'Rivendosje fjalekalimi',
  'Link per rivendosje fjalekalimi.', true, true,
  'Link per te rivendosur fjalekalimin.',
  'Link zum Zurucksetzen des Passworts.',
  'Link to reset your password.',
  'Rivendosni fjalekalimin', 'Passwort zurucksetzen', 'Reset your password',
  'Rivendosje fjalekalimi', 'Passwort zurucksetzen', 'Reset password',
  'Morem nje kerkese per te rivendosur fjalekalimin tuaj.',
  'Wir haben eine Anfrage zum Zurucksetzen Ihres Passworts erhalten.',
  'We received a request to reset your password.',
  '<p>Klikoni butonin me poshte. Linku skadon per 60 minuta.</p><p>Nese nuk e keni kerkuar ju, injoroje kete email.</p>',
  '<p>Der Link ist 60 Minuten gultig.</p>',
  '<p>This link expires in 60 minutes.</p>',
  'Rivendos fjalekalimin', 'Passwort zurucksetzen', 'Reset password',
  '{{reset_url}}',
  '["reset_url"]'::jsonb
),
(
  'invoice_issued', 'transactional', 'Fature e re',
  'Dergohet kur nje fature i dergohet klientit.', true, true,
  'Totali {{total_formatted}}, afat {{due_date}}.',
  'Summe {{total_formatted}}, Fallig {{due_date}}.',
  'Total {{total_formatted}}, due {{due_date}}.',
  'Fatura {{invoice_number}}', 'Rechnung {{invoice_number}}', 'Invoice {{invoice_number}}',
  'Fatura {{invoice_number}}', 'Rechnung {{invoice_number}}', 'Invoice {{invoice_number}}',
  'Ju dergojme faturen <strong>{{invoice_number}}</strong>.',
  'Ihre Rechnung <strong>{{invoice_number}}</strong>.',
  'Your invoice <strong>{{invoice_number}}</strong>.',
  '<p><strong>Totali:</strong> {{total_formatted}}<br/><strong>Afati i pageses:</strong> {{due_date}}</p>',
  '<p><strong>Summe:</strong> {{total_formatted}}<br/><strong>Fallig:</strong> {{due_date}}</p>',
  '<p><strong>Total:</strong> {{total_formatted}}<br/><strong>Due:</strong> {{due_date}}</p>',
  'Shiko faturen', 'Rechnung ansehen', 'View invoice',
  '{{invoice_url}}',
  '["invoice_number","total_formatted","due_date","invoice_url"]'::jsonb
),
(
  'invoice_paid', 'transactional', 'Fature e paguar',
  'Konfirmim kur fatura shenohet si e paguar.', true, true,
  'Fatura {{invoice_number}} u pagua.',
  'Rechnung {{invoice_number}} wurde bezahlt.',
  'Invoice {{invoice_number}} was paid.',
  'Fatura {{invoice_number}} u pagua',
  'Rechnung {{invoice_number}} bezahlt',
  'Invoice {{invoice_number}} paid',
  'Fature e paguar', 'Rechnung bezahlt', 'Invoice paid',
  'Fatura <strong>{{invoice_number}}</strong> ({{total_formatted}}) u regjistrua si e paguar.',
  'Die Rechnung <strong>{{invoice_number}}</strong> ({{total_formatted}}) wurde als bezahlt verbucht.',
  'Invoice <strong>{{invoice_number}}</strong> ({{total_formatted}}) has been marked as paid.',
  '<p>Faleminderit per bashkepunimin.</p>',
  '<p>Vielen Dank.</p>',
  '<p>Thank you.</p>',
  'Shiko detajet', 'Details ansehen', 'View details',
  '{{invoice_url}}',
  '["invoice_number","total_formatted","invoice_url"]'::jsonb
),
(
  'invoice_overdue', 'transactional', 'Rikujtese fature e vonuar',
  'Dergohet kur fatura kalon afatin e pageses.', true, true,
  '{{days_overdue}} dite pas afatit.',
  '{{days_overdue}} Tage uberfallig.',
  '{{days_overdue}} days past due.',
  'Rikujtese: Fatura {{invoice_number}} eshte e vonuar',
  'Erinnerung: Rechnung {{invoice_number}} uberfallig',
  'Reminder: Invoice {{invoice_number}} overdue',
  'Fature e vonuar', 'Uberfallige Rechnung', 'Invoice overdue',
  'Fatura <strong>{{invoice_number}}</strong> me total {{total_formatted}} eshte <strong>{{days_overdue}} dite</strong> pas afatit.',
  'Die Rechnung <strong>{{invoice_number}}</strong> ({{total_formatted}}) ist seit <strong>{{days_overdue}} Tagen</strong> uberfallig.',
  'Invoice <strong>{{invoice_number}}</strong> for {{total_formatted}} is <strong>{{days_overdue}} days</strong> overdue.',
  '<p>Ju lutemi procedoni me pagesen sa me shpejt.</p>',
  '<p>Bitte begleichen Sie die Zahlung.</p>',
  '<p>Please process the payment as soon as possible.</p>',
  'Shiko faturen', 'Rechnung ansehen', 'View invoice',
  '{{invoice_url}}',
  '["invoice_number","total_formatted","days_overdue","invoice_url"]'::jsonb
),
(
  'compliance_expiring', 'transactional', 'Dokument compliance skadon',
  'Rikujtese per dokumentet qe skadojne (TUV, licenca, sigurim, etj).', true, true,
  '{{subject_label}} - afat {{expiry_date}}.',
  '{{subject_label}} - {{expiry_date}}.',
  '{{subject_label}} - {{expiry_date}}.',
  '{{type_label}} skadon per {{days_remaining}} dite - {{subject_label}}',
  '{{type_label}} lauft in {{days_remaining}} Tagen ab',
  '{{type_label}} expires in {{days_remaining}} days',
  '{{type_label}} skadon', '{{type_label}} lauft ab', '{{type_label}} expiring soon',
  '<strong>{{subject_label}}</strong>: {{type_label}} ka afat <strong>{{expiry_date}}</strong>.',
  '<strong>{{subject_label}}</strong>: {{type_label}} - <strong>{{expiry_date}}</strong>.',
  '<strong>{{subject_label}}</strong>: {{type_label}} on <strong>{{expiry_date}}</strong>.',
  '<p>Ju lutemi perditesoni dokumentin para skadimit per te shmangur nderprerjet.</p>',
  '<p>Bitte aktualisieren Sie das Dokument.</p>',
  '<p>Please update the document to avoid disruption.</p>',
  'Shko tek dokumenti', 'Zum Dokument', 'Open document',
  '{{app_base_url}}/compliance',
  '["type_label","subject_label","days_remaining","expiry_date","app_base_url"]'::jsonb
),
(
  'delivery_assigned', 'transactional', 'Dergese e caktuar',
  'Shoferi merr email kur i caktohet nje dergese e re.', true, true,
  'Ju eshte caktuar {{note_number}}.',
  'Ihnen wurde {{note_number}} zugewiesen.',
  'You were assigned {{note_number}}.',
  'Dergese e re: {{note_number}}', 'Neue Lieferung: {{note_number}}', 'New delivery: {{note_number}}',
  'Dergese e re', 'Neue Lieferung', 'New delivery',
  'Ju eshte caktuar dergesa <strong>{{note_number}}</strong>.',
  'Sie wurden der Lieferung <strong>{{note_number}}</strong> zugewiesen.',
  'You have been assigned delivery <strong>{{note_number}}</strong>.',
  '<p>Hapni aplikacionin per te pare detajet.</p>',
  '<p>Offnen Sie die App fur Details.</p>',
  '<p>Open the app to see details.</p>',
  'Shiko dergesen', 'Lieferung ansehen', 'View delivery',
  '{{app_base_url}}/driver',
  '["note_number","app_base_url"]'::jsonb
),
(
  'subscription_activated', 'transactional', 'Abonim i aktivizuar',
  'Dergohet kur plani aktivizohet per kompanine.', true, true,
  'Plani {{plan_name}}.', 'Plan {{plan_name}}.', 'Plan {{plan_name}}.',
  'Abonimi u aktivizua: {{plan_name}}',
  'Abonnement aktiv: {{plan_name}}',
  'Subscription active: {{plan_name}}',
  'Abonim i aktivizuar', 'Abonnement aktiv', 'Subscription active',
  'Plani <strong>{{plan_name}}</strong> eshte aktivizuar per kompanine tuaj.',
  'Der Plan <strong>{{plan_name}}</strong> ist aktiviert.',
  'Your <strong>{{plan_name}}</strong> plan is now active.',
  '<p>Faleminderit per besimin.</p>', '<p>Vielen Dank.</p>', '<p>Thank you.</p>',
  'Menaxho abonimin', 'Abonnement verwalten', 'Manage subscription',
  '{{app_base_url}}/company/settings',
  '["plan_name","app_base_url"]'::jsonb
),
(
  'trial_ending_soon', 'transactional', 'Periudha provuese po perfundon',
  'Paralajmerim perpara skadimit te trial-it.', true, true,
  '{{days_remaining}} dite te mbetura.',
  '{{days_remaining}} Tage verbleibend.',
  '{{days_remaining}} days remaining.',
  'Periudha provuese perfundon per {{days_remaining}} dite',
  'Testphase endet in {{days_remaining}} Tagen',
  'Trial ends in {{days_remaining}} days',
  'Periudha provuese po perfundon',
  'Testphase endet bald',
  'Trial ending soon',
  'Periudha provuese e {{brand_name}} perfundon per <strong>{{days_remaining}} dite</strong>.',
  'Ihre Testphase endet in <strong>{{days_remaining}} Tagen</strong>.',
  'Your trial of {{brand_name}} ends in <strong>{{days_remaining}} days</strong>.',
  '<p>Zgjidhni nje plan per te vazhduar pa nderprerje.</p>',
  '<p>Wahlen Sie einen Plan.</p>',
  '<p>Choose a plan to continue without interruption.</p>',
  'Zgjidh planin', 'Plan wahlen', 'Choose plan',
  '{{app_base_url}}/company/settings',
  '["days_remaining","brand_name","app_base_url"]'::jsonb
),
(
  'fleet_doc_rejected', 'transactional', 'Dokument flote u refuzua',
  'Njoftim per refuzim te skanimit te dokumentit te mjetit/shoferit.', true, true,
  '{{reason}}', '{{reason}}', '{{reason}}',
  'Dokumenti u refuzua: {{doc_type}}',
  'Dokument abgelehnt: {{doc_type}}',
  'Document rejected: {{doc_type}}',
  'Dokument i refuzuar', 'Dokument abgelehnt', 'Document rejected',
  'Dokumenti <strong>{{doc_type}}</strong> u refuzua.',
  'Das Dokument <strong>{{doc_type}}</strong> wurde abgelehnt.',
  'Document <strong>{{doc_type}}</strong> was rejected.',
  '<p><strong>Arsyeja:</strong> {{reason}}</p>',
  '<p><strong>Grund:</strong> {{reason}}</p>',
  '<p><strong>Reason:</strong> {{reason}}</p>',
  'Ringarko dokumentin', 'Erneut hochladen', 'Re-upload document',
  '{{app_base_url}}/compliance',
  '["doc_type","reason","app_base_url"]'::jsonb
),
(
  'admin_broadcast', 'marketing', 'Njoftim i pergjithshem',
  'Template i lire per njoftime dhe fushata marketingu te personalizueshme.', true, true,
  '{{preheader}}', '{{preheader}}', '{{preheader}}',
  '{{subject}}', '{{subject}}', '{{subject}}',
  '{{heading}}', '{{heading}}', '{{heading}}',
  '{{intro}}', '{{intro}}', '{{intro}}',
  '{{body_html}}', '{{body_html}}', '{{body_html}}',
  '{{cta_label}}', '{{cta_label}}', '{{cta_label}}',
  '{{cta_url}}',
  '["subject","preheader","heading","intro","body_html","cta_label","cta_url"]'::jsonb
)
ON CONFLICT (code) DO NOTHING;
