/*
  # Mbulim i plotë për qytetet dhe komunat e Ballkanit

  1. Ndryshime
    - Shton të gjitha 38 komunat e Kosovës (XK)
    - Shton 61 bashkitë e Shqipërisë (AL)
    - Shton komunat kryesore të Maqedonisë së Veriut (MK), Malit të Zi (ME),
      Bosnjës (BA), Serbisë (RS), Kroacisë (HR), Sllovenisë (SI), Bullgarisë (BG)
    - Shton kode postare reprezentative për secilin qytet të ri

  2. Siguria
    - Tabelat `cities` dhe `postal_codes` tashmë kanë RLS të aktivizuar
    - Nuk ka politika të reja sepse shkrimi mbahet i mbyllur (service_role only)

  3. Shënime
    - I gjithë inserti përdor `WHERE NOT EXISTS` për idempotencë
    - Qytetet me emra identikë në shtete të ndryshme ruhen nëse indeksi unik i
      tabelës `cities` (country_id, lower(name)) lejon shtim
*/

INSERT INTO cities (country_id, name, admin_area)
SELECT c.id, v.name, v.admin_area
FROM (VALUES
  -- Kosovo: 38 komunat
  ('XK','Podujevë','Prishtinë'),
  ('XK','Fushë Kosovë','Prishtinë'),
  ('XK','Lipjan','Prishtinë'),
  ('XK','Obiliq','Prishtinë'),
  ('XK','Graçanicë','Prishtinë'),
  ('XK','Drenas','Prishtinë'),
  ('XK','Vushtrri','Mitrovicë'),
  ('XK','Skenderaj','Mitrovicë'),
  ('XK','Leposaviq','Mitrovicë'),
  ('XK','Zubin Potok','Mitrovicë'),
  ('XK','Zveçan','Mitrovicë'),
  ('XK','Mitrovicë e Veriut','Mitrovicë'),
  ('XK','Istog','Pejë'),
  ('XK','Klinë','Pejë'),
  ('XK','Deçan','Pejë'),
  ('XK','Junik','Pejë'),
  ('XK','Suharekë','Prizren'),
  ('XK','Rahovec','Prizren'),
  ('XK','Malishevë','Prizren'),
  ('XK','Dragash','Prizren'),
  ('XK','Mamushë','Prizren'),
  ('XK','Shtërpcë','Ferizaj'),
  ('XK','Shtime','Ferizaj'),
  ('XK','Kaçanik','Ferizaj'),
  ('XK','Hani i Elezit','Ferizaj'),
  ('XK','Viti','Gjilan'),
  ('XK','Kamenicë','Gjilan'),
  ('XK','Novobërdë','Gjilan'),
  ('XK','Ranillug','Gjilan'),
  ('XK','Partesh','Gjilan'),
  ('XK','Kllokot','Gjilan'),

  -- Albania: bashkitë kryesore + qytete
  ('AL','Lushnjë','Fier'),
  ('AL','Kavajë','Tiranë'),
  ('AL','Pogradec','Korçë'),
  ('AL','Gjirokastër','Gjirokastër'),
  ('AL','Sarandë','Vlorë'),
  ('AL','Lezhë','Lezhë'),
  ('AL','Kukës','Kukës'),
  ('AL','Tropojë','Kukës'),
  ('AL','Has','Kukës'),
  ('AL','Malësi e Madhe','Shkodër'),
  ('AL','Vau i Dejës','Shkodër'),
  ('AL','Pukë','Shkodër'),
  ('AL','Mirditë','Lezhë'),
  ('AL','Kurbin','Lezhë'),
  ('AL','Mat','Dibër'),
  ('AL','Dibër','Dibër'),
  ('AL','Klos','Dibër'),
  ('AL','Bulqizë','Dibër'),
  ('AL','Krujë','Durrës'),
  ('AL','Vorë','Tiranë'),
  ('AL','Rrogozhinë','Tiranë'),
  ('AL','Peqin','Elbasan'),
  ('AL','Librazhd','Elbasan'),
  ('AL','Prrenjas','Elbasan'),
  ('AL','Belsh','Elbasan'),
  ('AL','Gramsh','Elbasan'),
  ('AL','Cërrik','Elbasan'),
  ('AL','Divjakë','Fier'),
  ('AL','Roskovec','Fier'),
  ('AL','Mallakastër','Fier'),
  ('AL','Patos','Fier'),
  ('AL','Selenicë','Vlorë'),
  ('AL','Himarë','Vlorë'),
  ('AL','Finiq','Vlorë'),
  ('AL','Konispol','Vlorë'),
  ('AL','Delvinë','Vlorë'),
  ('AL','Libohovë','Gjirokastër'),
  ('AL','Tepelenë','Gjirokastër'),
  ('AL','Memaliaj','Gjirokastër'),
  ('AL','Përmet','Gjirokastër'),
  ('AL','Këlcyrë','Gjirokastër'),
  ('AL','Ersekë','Korçë'),
  ('AL','Bilisht','Korçë'),
  ('AL','Pustec','Korçë'),
  ('AL','Maliq','Korçë'),
  ('AL','Skrapar','Berat'),
  ('AL','Poliçan','Berat'),
  ('AL','Ura Vajgurore','Berat'),
  ('AL','Kuçovë','Berat'),

  -- North Macedonia
  ('MK','Tetovo','Polog'),
  ('MK','Kumanovo','Northeast'),
  ('MK','Prilep','Pelagonia'),
  ('MK','Ohrid','Southwest'),
  ('MK','Veles','Vardar'),
  ('MK','Štip','East'),
  ('MK','Struga','Southwest'),
  ('MK','Gostivar','Polog'),
  ('MK','Strumica','Southeast'),
  ('MK','Kavadarci','Vardar'),
  ('MK','Kočani','East'),
  ('MK','Kičevo','Southwest'),
  ('MK','Kriva Palanka','Northeast'),
  ('MK','Debar','Southwest'),
  ('MK','Radoviš','Southeast'),
  ('MK','Gevgelija','Southeast'),
  ('MK','Negotino','Vardar'),
  ('MK','Delčevo','East'),
  ('MK','Sveti Nikole','Vardar'),
  ('MK','Resen','Pelagonia'),
  ('MK','Berovo','East'),
  ('MK','Vinica','East'),
  ('MK','Probištip','East'),
  ('MK','Kratovo','Northeast'),
  ('MK','Makedonski Brod','Southwest'),
  ('MK','Demir Hisar','Pelagonia'),
  ('MK','Valandovo','Southeast'),
  ('MK','Bogdanci','Southeast'),
  ('MK','Krivogashtani','Pelagonia'),

  -- Montenegro
  ('ME','Nikšić',''),
  ('ME','Herceg Novi',''),
  ('ME','Bar',''),
  ('ME','Bijelo Polje',''),
  ('ME','Berane',''),
  ('ME','Ulcinj',''),
  ('ME','Cetinje',''),
  ('ME','Tivat',''),
  ('ME','Kotor',''),
  ('ME','Kolašin',''),
  ('ME','Žabljak',''),
  ('ME','Pljevlja',''),
  ('ME','Rožaje',''),
  ('ME','Plav',''),
  ('ME','Mojkovac',''),
  ('ME','Danilovgrad',''),
  ('ME','Andrijevica',''),
  ('ME','Šavnik',''),
  ('ME','Plužine',''),
  ('ME','Gusinje',''),
  ('ME','Petnjica',''),
  ('ME','Tuzi',''),

  -- Bosnia and Herzegovina
  ('BA','Banja Luka','Republika Srpska'),
  ('BA','Tuzla','FBiH'),
  ('BA','Zenica','FBiH'),
  ('BA','Mostar','FBiH'),
  ('BA','Bihać','FBiH'),
  ('BA','Brčko','Brčko'),
  ('BA','Bijeljina','Republika Srpska'),
  ('BA','Prijedor','Republika Srpska'),
  ('BA','Trebinje','Republika Srpska'),
  ('BA','Doboj','Republika Srpska'),
  ('BA','Zvornik','Republika Srpska'),
  ('BA','Gradiška','Republika Srpska'),
  ('BA','Cazin','FBiH'),
  ('BA','Sanski Most','FBiH'),
  ('BA','Travnik','FBiH'),
  ('BA','Livno','FBiH'),
  ('BA','Konjic','FBiH'),
  ('BA','Jajce','FBiH'),
  ('BA','Visoko','FBiH'),
  ('BA','Gračanica','FBiH'),
  ('BA','Tešanj','FBiH'),
  ('BA','Goražde','FBiH'),
  ('BA','Široki Brijeg','FBiH'),
  ('BA','Ljubuški','FBiH'),

  -- Serbia
  ('RS','Niš','Nišava'),
  ('RS','Kragujevac','Šumadija'),
  ('RS','Subotica','North Bačka'),
  ('RS','Čačak','Moravica'),
  ('RS','Kraljevo','Raška'),
  ('RS','Leskovac','Jablanica'),
  ('RS','Smederevo','Podunavlje'),
  ('RS','Valjevo','Kolubara'),
  ('RS','Kruševac','Rasina'),
  ('RS','Vranje','Pčinja'),
  ('RS','Šabac','Mačva'),
  ('RS','Užice','Zlatibor'),
  ('RS','Sombor','West Bačka'),
  ('RS','Pančevo','South Banat'),
  ('RS','Zrenjanin','Central Banat'),
  ('RS','Jagodina','Pomoravlje'),
  ('RS','Pirot','Pirot'),
  ('RS','Zaječar','Zaječar'),
  ('RS','Loznica','Mačva'),
  ('RS','Prokuplje','Toplica'),
  ('RS','Bor','Bor'),
  ('RS','Negotin','Bor'),
  ('RS','Sremska Mitrovica','Srem'),
  ('RS','Vrbas','South Bačka'),
  ('RS','Ruma','Srem'),
  ('RS','Bečej','South Bačka'),
  ('RS','Inđija','Srem'),
  ('RS','Novi Pazar','Raška'),
  ('RS','Kikinda','North Banat'),

  -- Croatia
  ('HR','Zadar','Zadar'),
  ('HR','Pula','Istria'),
  ('HR','Slavonski Brod','Brod-Posavina'),
  ('HR','Karlovac','Karlovac'),
  ('HR','Varaždin','Varaždin'),
  ('HR','Šibenik','Šibenik-Knin'),
  ('HR','Sisak','Sisak-Moslavina'),
  ('HR','Vinkovci','Vukovar-Srijem'),
  ('HR','Vukovar','Vukovar-Srijem'),
  ('HR','Dubrovnik','Dubrovnik-Neretva'),
  ('HR','Bjelovar','Bjelovar-Bilogora'),
  ('HR','Koprivnica','Koprivnica-Križevci'),
  ('HR','Požega','Požega-Slavonia'),
  ('HR','Samobor','Zagreb County'),
  ('HR','Velika Gorica','Zagreb County'),
  ('HR','Makarska','Split-Dalmatia'),
  ('HR','Trogir','Split-Dalmatia'),
  ('HR','Rovinj','Istria'),
  ('HR','Poreč','Istria'),
  ('HR','Umag','Istria'),
  ('HR','Čakovec','Međimurje'),
  ('HR','Đakovo','Osijek-Baranja'),

  -- Slovenia
  ('SI','Kranj','Upper Carniola'),
  ('SI','Celje','Savinja'),
  ('SI','Koper','Coastal–Karst'),
  ('SI','Novo Mesto','Southeast Slovenia'),
  ('SI','Velenje','Savinja'),
  ('SI','Nova Gorica','Gorizia'),
  ('SI','Murska Sobota','Mura'),
  ('SI','Ptuj','Drava'),
  ('SI','Jesenice','Upper Carniola'),
  ('SI','Domžale','Central Slovenia'),
  ('SI','Škofja Loka','Upper Carniola'),
  ('SI','Izola','Coastal–Karst'),
  ('SI','Piran','Coastal–Karst'),
  ('SI','Portorož','Coastal–Karst'),
  ('SI','Bled','Upper Carniola'),
  ('SI','Slovenj Gradec','Carinthia'),
  ('SI','Trbovlje','Central Sava'),
  ('SI','Krško','Posavje'),
  ('SI','Brežice','Posavje'),

  -- Bulgaria
  ('BG','Burgas','Burgas'),
  ('BG','Ruse','Ruse'),
  ('BG','Stara Zagora','Stara Zagora'),
  ('BG','Pleven','Pleven'),
  ('BG','Sliven','Sliven'),
  ('BG','Dobrich','Dobrich'),
  ('BG','Shumen','Shumen'),
  ('BG','Pernik','Pernik'),
  ('BG','Haskovo','Haskovo'),
  ('BG','Yambol','Yambol'),
  ('BG','Pazardzhik','Pazardzhik'),
  ('BG','Blagoevgrad','Blagoevgrad'),
  ('BG','Veliko Tarnovo','Veliko Tarnovo'),
  ('BG','Vratsa','Vratsa'),
  ('BG','Gabrovo','Gabrovo'),
  ('BG','Kazanlak','Stara Zagora'),
  ('BG','Asenovgrad','Plovdiv'),
  ('BG','Vidin','Vidin'),
  ('BG','Kyustendil','Kyustendil'),
  ('BG','Montana','Montana'),
  ('BG','Targovishte','Targovishte'),
  ('BG','Lovech','Lovech'),
  ('BG','Razgrad','Razgrad'),
  ('BG','Silistra','Silistra'),
  ('BG','Kardzhali','Kardzhali'),
  ('BG','Smolyan','Smolyan'),
  ('BG','Sandanski','Blagoevgrad'),
  ('BG','Petrich','Blagoevgrad')
) AS v(country_code, name, admin_area)
JOIN countries c ON upper(c.code) = upper(v.country_code)
WHERE NOT EXISTS (
  SELECT 1 FROM cities ci
  WHERE ci.country_id = c.id
    AND lower(ci.name) = lower(v.name)
);
