/**
 * Acceptable Use Policy (AUP)
 * Defines what customers are NOT allowed to do with the platform.
 *
 * This policy protects:
 * - The platform from abuse (spam, attacks, illegal content)
 * - Other customers from harm
 * - Our reputation and infrastructure
 * - Us from legal liability for customer actions
 *
 * Legal basis: contractual freedom under BGB §241. Violations
 * give us the right to suspend or terminate accounts immediately
 * for serious cases (GDPR-compliant if reason is documented).
 */

export const aup = {
  // ============================================================
  // ALBANIAN (SQ)
  // ============================================================
  sq: {
    shortTitle: 'Perdorimi i pranueshem',
    title: 'Politika e Perdorimit te Pranueshem (AUP)',
    subtitle: 'Cfare lejohet dhe cfare nuk lejohet ne perdorimin e platformes sone. Per te mbrojtur te gjithe perdoruesit.',
    intro: 'Kjo Politike e Perdorimit te Pranueshem ("AUP") percakton se cfare nuk lejohet te bejne perdoruesit me platformen mm-logistic. Eshte pjese e pa-ndashme e Kushteve te Pergjithshme te Perdorimit (AGB) dhe shkelja e saj mund te shkaktoje pezullim ose perfundim te llogarise. Synojme te mbajme nje mjedis te sigurte, te ligjshem dhe profesional per te gjithe klientet tane.',
    lastUpdated: '15 Maj 2026',
    version: 'Versioni 1.0',

    section1: {
      title: 'Parimet themelore',
      body: 'Perdoruesit duhet:\n\n\u2022 Te perdorin platformen vetem per qellime te ligjshme dhe biznesore\n\u2022 Te respektojne te drejtat e paleve te treta (pronesi intelektuale, privatesi, mbrojtje konsumatori)\n\u2022 Te mos demtojne platformen, perdoruesit e tjere ose infrastrukturen\n\u2022 Te mos shfrytezojne sherbimin per qellime jashte planit te abonimit\n\u2022 Te respektojne ligjet evropiane, gjermane dhe te vendit te tyre\n\nKjo AUP nuk eshte nje liste e plote e gjitha veprimeve te ndaluara, por ofron udhezime te qarta dhe shembuj. Ne rezervojme te drejten e gjykimit final per ate qe perben perdorim te papranueshem.',
    },
    section2: {
      title: 'Permbajtje e ndaluar',
      body: 'NUK LEJOHET te ngarkoni, ruani, transmetoni ose publikoni:\n\n(1) PERMBAJTJE TE PALIGJSHME\n\u2022 Materiale qe shkelin ligjet penale (terrorizem, droge, prostitucion, dhune)\n\u2022 Permbajtje qe shkel sankcione (te dhena nga vende te embargosur)\n\u2022 Materiale qe shkelin Strafgesetzbuch (kod penal gjerman)\n\n(2) PERMBAJTJE TE DEMSHME PER FEMIJET\n\u2022 Materiale qe seksualizojne te miturit (CSAM)\n\u2022 Permbajtje qe lehteson grooming ose abuzim te femijeve\n\u2022 Cdo permbajtje pornografike te paligjshme\n\nKy kategori SHKAKTON MENJEHERE perfundim te llogarise dhe raportim tek autoritetet kompetente.\n\n(3) PERMBAJTJE QE PROMOVON URREJTJE\n\u2022 Diskriminim ne baze te races, religjionit, gjinise, orientimit seksual\n\u2022 Holocaust denial dhe simbole te Volksverhetzung sipas \u00a7 130 StGB\n\u2022 Propagande terroriste ose dhune\n\u2022 Permbajtje qe nxit dhune fizike\n\n(4) PERMBAJTJE TE PA-LIGJSHME PROPRIETARE\n\u2022 Materiale qe shkelin te drejten e autorit pa licence\n\u2022 Patentime, marka tregtare ose sekrete te biznesit te paleve te treta\n\u2022 Trade secrets te marra ne menyre te paligjshme\n\n(5) PERMBAJTJE QE SHKEL PRIVATESINE\n\u2022 Te dhena personale te marra pa baze ligjore\n\u2022 Doxxing - publikim i adresave/identitetit privat\n\u2022 Material i prodhuar permes deepfake pa pelqim\n\u2022 Permbajtje intime (NCII) e publikuar pa pelqim',
    },
    section3: {
      title: 'Sjellje e ndaluar',
      body: 'NUK LEJOHET te:\n\n(1) ABUZONI SISTEMIN\n\u2022 Sulm DDoS, port scanning, exploit\n\u2022 Reverse engineering te platformes ose kodi\n\u2022 Penetration testing pa autorizim te shkruar\n\u2022 Te shfrytezoni gabime sigurie pa raport responsibel\n\u2022 Te krijoni llogari te shumefishta per te shmangur kufijte\n\n(2) ABUZONI AUTOMATIZIMIN\n\u2022 Scraping automatik pertej kufijve te API\n\u2022 Bot-e qe imitojne perdorues te vertete\n\u2022 Skripte qe kopjojne te dhenat masive\n\u2022 Crawler-e te paautorizuar\n\u2022 Headless browsers per qellime te dyshuara\n\n(3) ABUZONI E-MAILIN\n\u2022 Dergim spam-i nepermjet platformes\n\u2022 Listave email te blera ose te marra pa pelqim\n\u2022 Phishing ose mashtrim identiteti\n\u2022 Bulk email pa shenjuese te qarta\n\n(4) ABUZONI BURIMET\n\u2022 Storage abuse - perdorim si free file hosting\n\u2022 Bandwidth abuse - shfrytezim mbi planin tend\n\u2022 Database queries qe shkaktojne performance issues\n\u2022 Crypto mining nepermjet platformes\n\n(5) MASHTROJNE KLIENTET\n\u2022 False advertising te sherbimeve qe nuk i ofron\n\u2022 Mosrespektim i obligimit kontraktor me klientet finale\n\u2022 Manipulim i te dhenave per qellime ilegale\n\u2022 Falsifikim i dokumenteve te transportit',
    },
    section4: {
      title: 'Kufizimet teknike',
      body: 'PLATFORMA KA KETO KUFIZIME TEKNIKE QE NUK MUND TI SHMANGNI:\n\n(1) API RATE LIMITS\n\u2022 100 kerkesa per minute per perdorues (default)\n\u2022 1000 kerkesa per ore per organizate (default)\n\u2022 Kufizime me te larta disponueshme per plane premium\n\n(2) STORAGE QUOTAS\n\u2022 Sipas planit te abonimit (10 GB - 1 TB)\n\u2022 Skedare individual max 100 MB\n\u2022 Foto/skanim max 25 MB\n\n(3) BANDWIDTH LIMITS\n\u2022 Egress bandwidth sipas planit\n\u2022 Spike protection: 10x mesatarja te lejuar per 1 ore\n\n(4) USER LIMITS\n\u2022 Numri i perdoruesve sipas planit\n\u2022 Nuk lejohen llogari "shared" ose "service" jashte funksioneve te dedikuara\n\n(5) DATABASE QUERIES\n\u2022 Max 50 row read per query (default)\n\u2022 Max 1000 row insert/update per batch\n\u2022 Long-running queries (>30s) automatikisht ndalohen\n\nSHKELJE TE KETYRE KUFIZIMEVE:\n\u2022 Auto-throttling per shkelje te lehta\n\u2022 Suspendim i perkohshem per shkelje te perseritura\n\u2022 Suspendim i menjehershem per sulm sigurie',
    },
    section5: {
      title: 'Permbajtja qe kerkon kujdes te vecante',
      body: 'KETO LLOJE TE PERMBAJTJES KERKOJNE BAZE LIGJORE TE QARTE DHE DOKUMENTACION:\n\n(1) TE DHENA SHENDETESORE\nNese ngarkoni dokumente shoferi me te dhena shendetesore (certifikate mjekesore, etj.):\n\u2022 Duhet te kete pelqim te shoferit\n\u2022 Duhet te dokumentohet baza ligjore\n\u2022 Akses i kufizuar vetem per persona te autorizuar\n\n(2) TE DHENA PER MINORENN\nNese keni shofere ose punonjes nen 18 vjec:\n\u2022 Kerkohet pelqimi i prinderve\n\u2022 Kufizim shtese ne perpunim\n\u2022 Mund te kerkohet aprovim shtese\n\n(3) TE DHENA TE NDJESHME FINANCIARE\n\u2022 Numra te plote te kartave kreditit - perdorni Stripe direkt\n\u2022 Te dhena biometrike per autentifikim\n\u2022 Te dhena te llogarive bankare te paleve te treta\n\n(4) TE DHENA TE LOKALIZIMIT\nGPS tracking i shofereve eshte i pranueshem, por:\n\u2022 Vetem gjate orarit te punes\n\u2022 Me njoftim te qarte tek shoferi\n\u2022 Per qellime operacionale (jo monitorim total)\n\u2022 Me politike fshirjeje pas 30 ditesh\n\n(5) PERMBAJTJE QE PERFSHIN ME SHUME SUBJEKTE\nFoto ose video me persona te tjere:\n\u2022 Pelqim i te gjitha personave\n\u2022 Ose baza ligjore te qarte\n\u2022 Anonimizim kur kerkohet',
    },
    section6: {
      title: 'Aktivitete biznesi te ndaluara',
      body: 'NUK LEJOHET TE PERDORNI PLATFORMEN PER:\n\n(1) AKTIVITETE TE PALIGJSHME\n\u2022 Shitje droge, armesh, materiale eksplozive\n\u2022 Trafikim njerezish\n\u2022 Mashtrim financiar (Ponzi, pyramid schemes)\n\u2022 Pastrim parash\n\u2022 Aktivitete qe shmangin sankcionet nderkombetare\n\n(2) AKTIVITETE TE LICENSUARA PA LICENSE\n\u2022 Sherbim transporti pa license komerciale\n\u2022 Mbartje materialeve te rrezikshme (ADR) pa kualifikim\n\u2022 Operacione tatimore pa autorizim\n\n(3) MASHTRIM I KONSUMATOREVE\n\u2022 Shitje produktesh qe nuk ekzistojne\n\u2022 Mashtrim ne fatura\n\u2022 Manipulim i recensioneve ose vleresimeve\n\n(4) VEPRIMTARI E NDARSHME E LIDHUR ME GAMBLING/CRYPTO\n\u2022 Operim casino pa licence ne Gjermani\n\u2022 Trading crypto pa autorizim BaFin\n\u2022 Forex trading retail pa BaFin license\n\nNe kemi te drejten te kerkojme dokumentim te aktivitetit te biznesit ne rastet e dyshimit. Refuzimi i dokumentimit mund te shkaktoje pezullim.',
    },
    section7: {
      title: 'Komunikim me ekipin tone',
      body: 'NE KOMUNIKIMIN ME EKIPIN TONE TE MBESHTETJES:\n\nLEJOHET:\n\u2022 Pyetje teknike profesionale\n\u2022 Raportim bugs dhe veshtiresish\n\u2022 Sugjerime per permiresime\n\u2022 Feedback konstruktiv\n\nNUK LEJOHET:\n\u2022 Sjellje abusive (insulte, gjuhe e papershtatshme, racizem, etj.)\n\u2022 Kerkim i informacionit personal te stafit\n\u2022 Trysni ose kercenime\n\u2022 Kerkesa per favore te paligjshme\n\u2022 Spam ne tickete te shumefishta\n\nNE RAST SJELLJEJE ABUSIVE:\n\u2022 Paralajmerim me shkrim\n\u2022 Kufizim i kanalit te mbeshtetjes (vetem email)\n\u2022 Suspendim i llogarise per raste te renda\n\u2022 Raportim tek autoritetet ne raste te kercenimeve te drejtperdrejta',
    },
    section8: {
      title: 'Reverse engineering dhe pronesi',
      body: 'NUK LEJOHET TE:\n\n(1) REVERSE ENGINEER KODIN\n\u2022 Dekompiloj front-end code (HTML, JS, CSS)\n\u2022 Analizoj back-end API endpoints per replikim\n\u2022 Studioj algoritmin tone per kopjim\n\u2022 Krijoj sherbim te ngjashem konkurrent\n\n(2) MARRESH AVANTAZH PA LICENCE\n\u2022 Perdorim funksioneve te paguara pa pagese\n\u2022 Kopjim i kodit pa licence\n\u2022 Hosting i tij ne infrastruktur tjeter\n\u2022 Rishitje pa autorizim ekskluziv me shkrim\n\n(3) SHKELESH PRONESINE INTELEKTUALE\n\u2022 Brand spoofing - imitim i markes\n\u2022 Logo theft\n\u2022 Use of trade secrets\n\u2022 Plagiarism i dokumentacionit\n\nINTEROPERABILITY DHE DEBUGGING:\nLejohet zhvillim integrimi me API-n tone (eshte qellimi i tij), debugging te aplikacioneve qe lidhen me ne, dhe studim akademik me kushte te qarta.',
    },
    section9: {
      title: 'Pasoja te shkeljes',
      body: 'NE RAST TE SHKELJES SE AUP:\n\nNIVELI 1 - SHKELJE E LEHTE OSE E PARE:\n\u2022 Paralajmerim me shkrim per e-mail\n\u2022 Kerkese per korrigjim brenda 7 ditesh\n\u2022 Pa pezullim te sherbimit\n\nNIVELI 2 - SHKELJE TE PERSERITURA:\n\u2022 Pezullim i perkohshem (7-30 dite)\n\u2022 Akses vetem per shkarkim te te dhenave\n\u2022 Faturat vazhdojne te lëshohen normalisht\n\nNIVELI 3 - SHKELJE E RENDE:\n\u2022 Suspendim i menjehershem i llogarise\n\u2022 Akses i bllokuar plotesisht\n\u2022 Periudhe e shkurter (24 ore) per shkarkim emergjent\n\u2022 Mundesi perfundimi kontrate\n\nNIVELI 4 - SHKELJE KATASTROFIKE:\n\u2022 Suspendim i menjehershem dhe i perhershem\n\u2022 Fshirje e te dhenave (pas afatit ligjor)\n\u2022 Raportim tek autoritetet kompetente\n\u2022 Padi civile per dem\n\u2022 Forwarding tek policia ne raste kriminale\n\nKATEGORIA KATASTROFIKE PERFSHIN:\n\u2022 CSAM ose material kunder femijeve\n\u2022 Terrorizem ose propagande dhune\n\u2022 Sulm ne infrastrukturen tone\n\u2022 Mashtrim financiar masive\n\u2022 Trafikim qenieve njerezore',
    },
    section10: {
      title: 'Raportimi i shkeljeve',
      body: 'NESE NJIHNI NJE SHKELJE TE KESAJ AUP:\n\nKANALE TE RAPORTIMIT:\n\nE-mail: [abuse@kompani.de]\nPergjigje: 24-72 ore (sipas urgjences)\n\nPER RASTE EMERGJENTE:\nE-mail: [security@kompani.de]\nTelefon: +49 172 8443861 (orari i punes)\n\nPER PERMBAJTJE QE PERFSHIN FEMIJE:\nDo te raportohet menjehere tek:\n\u2022 BKA (Bundeskriminalamt) ne Gjermani\n\u2022 NCMEC (National Center for Missing & Exploited Children)\n\u2022 Interpol per raste nderkombetare\n\nINFORMACIONI I NEVOJSHEM:\n\u2022 Llogaria/perdoruesi i dyshuar\n\u2022 Pershkrim i shkeljes\n\u2022 Evidenca (screenshots, links, etj.)\n\u2022 Kontaktet tuaja (per ndjekje)\n\nNE GARANTOJME:\n\u2022 Trajtim konfidencial te raportimit\n\u2022 Mbrojtje nga whistleblower retaliation\n\u2022 Update mbi statusin e hetimit\n\u2022 Investigim profesional',
    },
    section11: {
      title: 'Mbrojtja e platformes',
      body: 'PER TE MBROJTUR PLATFORMEN NGA SHKELJET, NE PERDORIM:\n\n(1) MONITORIM AUTOMATIK\n\u2022 Anomaly detection (kerkesa abnormale, login te dyshuara)\n\u2022 Pattern recognition per spam, phishing, abuse\n\u2022 Rate limiting dhe DDoS protection\n\u2022 Hash scanning per known illegal content (PhotoDNA-like)\n\n(2) MODERIM MANUAL\n\u2022 Review i raportimeve nga perdoruesit\n\u2022 Audit periodik te llogarive te dyshuara\n\u2022 Investigim ne baze te flagjeve te brendshme\n\n(3) BASHKEPUNIM ME AUTORITETET\n\u2022 Pergjigje ndaj kerkesave ligjore te autoriteteve\n\u2022 Mbeshtetje hetimi penal kur kerkohet\n\u2022 Transparency report vjetor\n\nMASAT NUK PERFSHIJNE:\n\u2022 Leximi i te dhenave private te biznesit pa baze ligjore\n\u2022 Surveillance proaktive mbi perdoruesit\n\u2022 Analiza e te dhenave per qellime jashte sigurise\n\u2022 Profilim per qellime marketingu\n\nPRIVATESIA E KLIENTEVE MBETET PRIORITET.',
    },
    section12: {
      title: 'E drejta e apelimit',
      body: 'NESE LLOGARIA JUAJ EHTE PEZULLUAR OSE PERFUNDUAR:\n\n1. NJOFTIM\nDo te merrni nje email me arsye te qarta brenda 24 oresh nga aksioni.\n\n2. AFAT PER APELIM\nKeni 30 dite per te paraqitur apelim ne:\n[appeals@kompani.de]\n\n3. PROCESI I APELIMIT\n\u2022 Review nga ekip i pavarur (jo i njejti qe vendosi)\n\u2022 Mundesi te jepni informacion shtese ose kontekst\n\u2022 Pergjigje me shkrim brenda 14 ditesh\n\u2022 Vendim final me shpjegim\n\n4. NESE APELIMI MIRATOHET\n\u2022 Restorim i llogarise dhe te dhenave\n\u2022 Compensation per kohen e padisponueshmerise (sipas SLA)\n\u2022 Update i procedurave per te shmangur perseritjen\n\n5. NESE APELIMI REFUZOHET\n\u2022 Mundesi shkarkimi te te dhenave per 30 dite shtese\n\u2022 Pergjigje finale me arsye\n\u2022 Mundesi rishikimi gjyqesor\n\nPER PERFUNDIM KATASTROFIK (CSAM, terrorizem):\nNuk ka procedure apelimi - aksioni eshte i perhershem dhe i raportohet autoriteteve.',
    },
    section13: {
      title: 'Ndryshimet ne AUP',
      body: 'KJO AUP MUND TE NDRYSHOJE PER TE REFLEKTUAR:\n\n\u2022 Llojet e reja te abuzimit (kibernetik, ligjor)\n\u2022 Ndryshime ne ligjet (StGB, BDSG, GDPR, etj.)\n\u2022 Praktika me te mira nga industria\n\u2022 Feedback nga komuniteti i perdoruesve\n\nKOMUNIKIMI I NDRYSHIMEVE:\n\u2022 E-mail tek te gjithe perdoruesit aktive 30 dite paraprakisht\n\u2022 Banner ne platforme\n\u2022 Datestamp i perditesuar lart ne dokument\n\nPRANIMI:\n\u2022 Vazhdimi i perdorimit te sherbimit pas ndryshimeve perben pranim\n\u2022 Mund te perfundoni llogarine nese nuk pajtoni\n\nEMERGENCY UPDATES:\nNdryshime emergjente per sigurinë mund te behen pa periudhen e 30 ditesh, por do t\'ju njoftojme sapo te jete e mundur.',
    },
    section14: {
      title: 'Forca madhore dhe rrethana te jashtezakonshme',
      body: 'NE RRETHANA TE JASHTEZAKONSHME, NE MUND TE:\n\n(1) PEZULLOJME SHERBIMIN PER TE MBROJTUR SISTEMIN\n\u2022 Sulm kibernetik aktiv\n\u2022 Detektim malware\n\u2022 Critical security vulnerability\n\u2022 Forca madhore (lufta, dezastra natyrore)\n\n(2) PERFUNDOJME SHERBIMIN PER KUNDERSHTI\u00cb LIGJORE\n\u2022 Urdher gjyqesor\n\u2022 Sankione internacionale\n\u2022 Ndryshim drastik i ligjit\n\u2022 Falimentimi ose insolvenca\n\n(3) NJOFTOJME ME PARALAJMERIM MINIMAL\nPer raste emergjente, mund te ju njoftojme me afat te shkurter (1-48 ore).\n\nKOMPENSIMI:\n\u2022 Pro-rata refund per periudhen e shkurter\n\u2022 Eksport i te dhenave i lehtesuar\n\u2022 Sherbim alternativ kur te jete e mundur\n\nKETO RRETHANA JANE TE RRADHA POR JANE MUNDESI LIGJORE.',
    },
    section15: {
      title: 'Kontakti dhe pyetjet',
      body: 'PYETJE PER KETE AUP:\nE-mail: [legal@kompani.de]\nPergjigja brenda 14 ditesh.\n\nRAPORTIM SHKELJE:\nE-mail: [abuse@kompani.de]\nUrgjente: 24-72 ore\n\nINCIDENTE SIGURIE:\nE-mail: [security@kompani.de]\nTelefon: +49 172 8443861\n\nAPELIME:\nE-mail: [appeals@kompani.de]\nAfat: 30 dite nga pezullimi\n\nMBESHTETJE TE PERGJITHSHME:\nE-mail: [support@kompani.de]\n\nDPO:\nE-mail: dpo@mm-logistic.eu\n\nPOSTA ZYRTARE:\nMar Group (Genton Maliqi)\nPfädlistraße 10, 79576 Weil am Rhein, Germany\nGjermania\n\nE DREJTA E ANKESES:\nMund t\'i dorezoni ankesa tek autoritet mbikqyres si BfDI (per privatesi) ose policise (per krime).',
    },
  },

  // ============================================================
  // ENGLISH (EN)
  // ============================================================
  en: {
    shortTitle: 'Acceptable Use',
    title: 'Acceptable Use Policy (AUP)',
    subtitle: 'What is and is not allowed when using our platform. To protect all users.',
    intro: 'This Acceptable Use Policy ("AUP") defines what users are not allowed to do with the mm-logistic platform. It is an integral part of the Terms of Service (AGB) and violations may result in account suspension or termination. We aim to maintain a safe, lawful, and professional environment for all our customers.',
    lastUpdated: '15 May 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Fundamental principles',
      body: 'Users must:\n\n\u2022 Use the platform only for lawful business purposes\n\u2022 Respect rights of third parties (intellectual property, privacy, consumer protection)\n\u2022 Not harm the platform, other users, or infrastructure\n\u2022 Not exploit the service for purposes outside the subscription plan\n\u2022 Respect European, German, and their own country\'s laws\n\nThis AUP is not a complete list of all prohibited actions, but provides clear guidance and examples. We reserve the right of final judgment on what constitutes unacceptable use.',
    },
    section2: {
      title: 'Prohibited content',
      body: 'YOU MAY NOT upload, store, transmit, or publish:\n\n(1) ILLEGAL CONTENT\n\u2022 Materials violating criminal law (terrorism, drugs, prostitution, violence)\n\u2022 Content violating sanctions (data from embargoed countries)\n\u2022 Materials violating Strafgesetzbuch (German Criminal Code)\n\n(2) HARMFUL CONTENT INVOLVING CHILDREN\n\u2022 Material sexualizing minors (CSAM)\n\u2022 Content facilitating child grooming or abuse\n\u2022 Any illegal pornographic content\n\nThis category CAUSES IMMEDIATE account termination and reporting to competent authorities.\n\n(3) HATE CONTENT\n\u2022 Discrimination based on race, religion, gender, sexual orientation\n\u2022 Holocaust denial and Volksverhetzung symbols under \u00a7 130 StGB\n\u2022 Terrorist or violence propaganda\n\u2022 Content inciting physical violence\n\n(4) UNLAWFUL PROPRIETARY CONTENT\n\u2022 Materials violating copyright without license\n\u2022 Third-party patents, trademarks, or trade secrets\n\u2022 Trade secrets obtained illegally\n\n(5) PRIVACY-VIOLATING CONTENT\n\u2022 Personal data obtained without legal basis\n\u2022 Doxxing - publishing private addresses/identity\n\u2022 Deepfake material produced without consent\n\u2022 Intimate content (NCII) published without consent',
    },
    section3: {
      title: 'Prohibited behavior',
      body: 'YOU MAY NOT:\n\n(1) ABUSE THE SYSTEM\n\u2022 DDoS attacks, port scanning, exploits\n\u2022 Reverse engineering of the platform or code\n\u2022 Penetration testing without written authorization\n\u2022 Exploit security bugs without responsible disclosure\n\u2022 Create multiple accounts to circumvent limits\n\n(2) ABUSE AUTOMATION\n\u2022 Automated scraping beyond API limits\n\u2022 Bots imitating real users\n\u2022 Scripts copying mass data\n\u2022 Unauthorized crawlers\n\u2022 Headless browsers for suspicious purposes\n\n(3) ABUSE EMAIL\n\u2022 Sending spam through the platform\n\u2022 Purchased or non-consented email lists\n\u2022 Phishing or identity fraud\n\u2022 Bulk email without clear identification\n\n(4) ABUSE RESOURCES\n\u2022 Storage abuse - using as free file hosting\n\u2022 Bandwidth abuse - exceeding your plan\n\u2022 Database queries causing performance issues\n\u2022 Crypto mining through the platform\n\n(5) DEFRAUD CUSTOMERS\n\u2022 False advertising of services you don\'t provide\n\u2022 Non-fulfillment of contractual obligations to end customers\n\u2022 Data manipulation for illegal purposes\n\u2022 Falsification of transport documents',
    },
    section4: {
      title: 'Technical limits',
      body: 'THE PLATFORM HAS THESE TECHNICAL LIMITS YOU MAY NOT CIRCUMVENT:\n\n(1) API RATE LIMITS\n\u2022 100 requests per minute per user (default)\n\u2022 1000 requests per hour per organization (default)\n\u2022 Higher limits available for premium plans\n\n(2) STORAGE QUOTAS\n\u2022 According to subscription plan (10 GB - 1 TB)\n\u2022 Individual files max 100 MB\n\u2022 Photos/scans max 25 MB\n\n(3) BANDWIDTH LIMITS\n\u2022 Egress bandwidth per plan\n\u2022 Spike protection: 10x average allowed for 1 hour\n\n(4) USER LIMITS\n\u2022 User count per plan\n\u2022 No "shared" or "service" accounts outside dedicated functions\n\n(5) DATABASE QUERIES\n\u2022 Max 50 row reads per query (default)\n\u2022 Max 1000 row insert/update per batch\n\u2022 Long-running queries (>30s) automatically blocked\n\nVIOLATIONS OF THESE LIMITS:\n\u2022 Auto-throttling for minor violations\n\u2022 Temporary suspension for repeated violations\n\u2022 Immediate suspension for security attacks',
    },
    section5: {
      title: 'Content requiring special care',
      body: 'THESE TYPES OF CONTENT REQUIRE CLEAR LEGAL BASIS AND DOCUMENTATION:\n\n(1) HEALTH DATA\nIf you upload driver documents with health data (medical certificate, etc.):\n\u2022 Must have driver consent\n\u2022 Must document legal basis\n\u2022 Restricted access only to authorized persons\n\n(2) MINOR DATA\nIf you have drivers or employees under 18:\n\u2022 Parental consent required\n\u2022 Additional processing restrictions\n\u2022 May require additional approval\n\n(3) SENSITIVE FINANCIAL DATA\n\u2022 Full credit card numbers - use Stripe directly\n\u2022 Biometric authentication data\n\u2022 Third-party bank account data\n\n(4) LOCATION DATA\nGPS tracking of drivers is acceptable, but:\n\u2022 Only during work hours\n\u2022 With clear notice to the driver\n\u2022 For operational purposes (not total monitoring)\n\u2022 With deletion policy after 30 days\n\n(5) CONTENT INVOLVING MULTIPLE SUBJECTS\nPhotos or videos with other persons:\n\u2022 All persons\' consent\n\u2022 Or clear legal basis\n\u2022 Anonymization when required',
    },
    section6: {
      title: 'Prohibited business activities',
      body: 'YOU MAY NOT USE THE PLATFORM FOR:\n\n(1) ILLEGAL ACTIVITIES\n\u2022 Selling drugs, weapons, explosives\n\u2022 Human trafficking\n\u2022 Financial fraud (Ponzi, pyramid schemes)\n\u2022 Money laundering\n\u2022 Activities circumventing international sanctions\n\n(2) LICENSED ACTIVITIES WITHOUT LICENSE\n\u2022 Transport service without commercial license\n\u2022 Carrying dangerous goods (ADR) without qualification\n\u2022 Tax operations without authorization\n\n(3) CONSUMER FRAUD\n\u2022 Sale of non-existent products\n\u2022 Invoice fraud\n\u2022 Review or rating manipulation\n\n(4) DUBIOUS GAMBLING/CRYPTO ACTIVITY\n\u2022 Operating casino without license in Germany\n\u2022 Crypto trading without BaFin authorization\n\u2022 Retail forex trading without BaFin license\n\nWe have the right to request business activity documentation in cases of suspicion. Refusal to provide documentation may result in suspension.',
    },
    section7: {
      title: 'Communication with our team',
      body: 'IN COMMUNICATION WITH OUR SUPPORT TEAM:\n\nALLOWED:\n\u2022 Professional technical questions\n\u2022 Bug and difficulty reports\n\u2022 Improvement suggestions\n\u2022 Constructive feedback\n\nNOT ALLOWED:\n\u2022 Abusive behavior (insults, inappropriate language, racism, etc.)\n\u2022 Seeking personal information of staff\n\u2022 Pressure or threats\n\u2022 Requests for illegal favors\n\u2022 Spam in multiple tickets\n\nIN CASE OF ABUSIVE BEHAVIOR:\n\u2022 Written warning\n\u2022 Support channel restriction (email only)\n\u2022 Account suspension for severe cases\n\u2022 Reporting to authorities in case of direct threats',
    },
    section8: {
      title: 'Reverse engineering and ownership',
      body: 'YOU MAY NOT:\n\n(1) REVERSE ENGINEER CODE\n\u2022 Decompile front-end code (HTML, JS, CSS)\n\u2022 Analyze back-end API endpoints for replication\n\u2022 Study our algorithm for copying\n\u2022 Create similar competing service\n\n(2) TAKE ADVANTAGE WITHOUT LICENSE\n\u2022 Use paid features without payment\n\u2022 Code copying without license\n\u2022 Hosting it on other infrastructure\n\u2022 Resale without exclusive written authorization\n\n(3) VIOLATE INTELLECTUAL PROPERTY\n\u2022 Brand spoofing - imitating the brand\n\u2022 Logo theft\n\u2022 Use of trade secrets\n\u2022 Plagiarism of documentation\n\nINTEROPERABILITY AND DEBUGGING:\nIntegration development with our API (its purpose), debugging of applications connecting to us, and academic study with clear terms are allowed.',
    },
    section9: {
      title: 'Consequences of violations',
      body: 'IN CASE OF AUP VIOLATIONS:\n\nLEVEL 1 - MINOR OR FIRST VIOLATION:\n\u2022 Written email warning\n\u2022 Correction request within 7 days\n\u2022 No service suspension\n\nLEVEL 2 - REPEATED VIOLATIONS:\n\u2022 Temporary suspension (7-30 days)\n\u2022 Access only for data download\n\u2022 Invoices continue to be issued normally\n\nLEVEL 3 - SERIOUS VIOLATION:\n\u2022 Immediate account suspension\n\u2022 Access fully blocked\n\u2022 Short period (24 hours) for emergency download\n\u2022 Contract termination possibility\n\nLEVEL 4 - CATASTROPHIC VIOLATION:\n\u2022 Immediate and permanent suspension\n\u2022 Data deletion (after legal deadline)\n\u2022 Reporting to competent authorities\n\u2022 Civil lawsuit for damages\n\u2022 Forwarding to police in criminal cases\n\nCATASTROPHIC CATEGORY INCLUDES:\n\u2022 CSAM or anti-child material\n\u2022 Terrorism or violence propaganda\n\u2022 Attack on our infrastructure\n\u2022 Massive financial fraud\n\u2022 Human trafficking',
    },
    section10: {
      title: 'Reporting violations',
      body: 'IF YOU NOTICE A VIOLATION OF THIS AUP:\n\nREPORTING CHANNELS:\n\nEmail: [abuse@company.de]\nResponse: 24-72 hours (depending on urgency)\n\nFOR EMERGENCY CASES:\nEmail: [security@company.de]\nPhone: +49 172 8443861 (business hours)\n\nFOR CHILD-INVOLVED CONTENT:\nWill be reported immediately to:\n\u2022 BKA (Bundeskriminalamt) in Germany\n\u2022 NCMEC (National Center for Missing & Exploited Children)\n\u2022 Interpol for international cases\n\nREQUIRED INFORMATION:\n\u2022 Suspected account/user\n\u2022 Description of violation\n\u2022 Evidence (screenshots, links, etc.)\n\u2022 Your contact info (for follow-up)\n\nWE GUARANTEE:\n\u2022 Confidential treatment of reports\n\u2022 Protection from whistleblower retaliation\n\u2022 Update on investigation status\n\u2022 Professional investigation',
    },
    section11: {
      title: 'Platform protection',
      body: 'TO PROTECT THE PLATFORM FROM VIOLATIONS, WE USE:\n\n(1) AUTOMATIC MONITORING\n\u2022 Anomaly detection (abnormal requests, suspicious logins)\n\u2022 Pattern recognition for spam, phishing, abuse\n\u2022 Rate limiting and DDoS protection\n\u2022 Hash scanning for known illegal content (PhotoDNA-like)\n\n(2) MANUAL MODERATION\n\u2022 Review of user reports\n\u2022 Periodic audit of suspicious accounts\n\u2022 Investigation based on internal flags\n\n(3) COOPERATION WITH AUTHORITIES\n\u2022 Response to legal authority requests\n\u2022 Criminal investigation support when required\n\u2022 Annual transparency report\n\nMEASURES DO NOT INCLUDE:\n\u2022 Reading private business data without legal basis\n\u2022 Proactive user surveillance\n\u2022 Data analysis for purposes outside security\n\u2022 Profiling for marketing purposes\n\nCUSTOMER PRIVACY REMAINS A PRIORITY.',
    },
    section12: {
      title: 'Right of appeal',
      body: 'IF YOUR ACCOUNT IS SUSPENDED OR TERMINATED:\n\n1. NOTIFICATION\nYou will receive an email with clear reasons within 24 hours of the action.\n\n2. APPEAL DEADLINE\nYou have 30 days to submit an appeal to:\n[appeals@company.de]\n\n3. APPEAL PROCESS\n\u2022 Review by independent team (not the same that decided)\n\u2022 Opportunity to provide additional information or context\n\u2022 Written response within 14 days\n\u2022 Final decision with explanation\n\n4. IF APPEAL APPROVED\n\u2022 Account and data restoration\n\u2022 Compensation for downtime (per SLA)\n\u2022 Procedure update to prevent recurrence\n\n5. IF APPEAL REJECTED\n\u2022 Additional 30 days to download data\n\u2022 Final response with reasoning\n\u2022 Judicial review possibility\n\nFOR CATASTROPHIC TERMINATION (CSAM, terrorism):\nNo appeal procedure - action is permanent and reported to authorities.',
    },
    section13: {
      title: 'Changes to AUP',
      body: 'THIS AUP MAY CHANGE TO REFLECT:\n\n\u2022 New types of abuse (cyber, legal)\n\u2022 Changes in laws (StGB, BDSG, GDPR, etc.)\n\u2022 Best practices from industry\n\u2022 User community feedback\n\nCOMMUNICATION OF CHANGES:\n\u2022 Email to all active users 30 days in advance\n\u2022 Platform banner\n\u2022 Updated datestamp at top of document\n\nACCEPTANCE:\n\u2022 Continued use after changes constitutes acceptance\n\u2022 You can terminate account if you do not agree\n\nEMERGENCY UPDATES:\nEmergency security updates may be made without the 30-day period, but we will notify you as soon as possible.',
    },
    section14: {
      title: 'Force majeure and exceptional circumstances',
      body: 'IN EXCEPTIONAL CIRCUMSTANCES, WE MAY:\n\n(1) SUSPEND SERVICE TO PROTECT SYSTEM\n\u2022 Active cyber attack\n\u2022 Malware detection\n\u2022 Critical security vulnerability\n\u2022 Force majeure (war, natural disasters)\n\n(2) TERMINATE SERVICE FOR LEGAL OPPOSITION\n\u2022 Court order\n\u2022 International sanctions\n\u2022 Drastic law change\n\u2022 Bankruptcy or insolvency\n\n(3) NOTIFY WITH MINIMAL WARNING\nFor emergency cases, we may notify you on short notice (1-48 hours).\n\nCOMPENSATION:\n\u2022 Pro-rata refund for shortened period\n\u2022 Facilitated data export\n\u2022 Alternative service when possible\n\nTHESE ARE RARE CIRCUMSTANCES BUT ARE LEGAL POSSIBILITIES.',
    },
    section15: {
      title: 'Contact and questions',
      body: 'QUESTIONS ABOUT THIS AUP:\nEmail: [legal@company.de]\nResponse within 14 days.\n\nVIOLATION REPORTS:\nEmail: [abuse@company.de]\nUrgent: 24-72 hours\n\nSECURITY INCIDENTS:\nEmail: [security@company.de]\nPhone: +49 172 8443861\n\nAPPEALS:\nEmail: [appeals@company.de]\nDeadline: 30 days from suspension\n\nGENERAL SUPPORT:\nEmail: [support@company.de]\n\nDPO:\nEmail: dpo@mm-logistic.eu\n\nOFFICIAL MAIL:\nMar Group (Genton Maliqi)\nPfädlistraße 10, 79576 Weil am Rhein, Germany\nGermany\n\nRIGHT OF COMPLAINT:\nYou can file complaints with supervisory authorities such as BfDI (for privacy) or police (for crimes).',
    },
  },

  // ============================================================
  // GERMAN (DE) - canonical legal version
  // ============================================================
  de: {
    shortTitle: 'Nutzungsrichtlinien',
    title: 'Richtlinien zur akzeptablen Nutzung (AUP)',
    subtitle: 'Was bei der Nutzung unserer Plattform erlaubt und nicht erlaubt ist. Zum Schutz aller Nutzer.',
    intro: 'Diese Richtlinien zur akzeptablen Nutzung ("AUP") legen fest, was Nutzer mit der Plattform mm-logistic nicht tun d\u00fcrfen. Sie sind integraler Bestandteil der Allgemeinen Gesch\u00e4ftsbedingungen (AGB) und Verst\u00f6\u00dfe k\u00f6nnen zu Kontosuspendierung oder -beendigung f\u00fchren. Wir streben danach, eine sichere, rechtm\u00e4\u00dfige und professionelle Umgebung f\u00fcr alle unsere Kunden zu erhalten.',
    lastUpdated: '15. Mai 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Grundlegende Prinzipien',
      body: 'Nutzer m\u00fcssen:\n\n\u2022 Die Plattform nur f\u00fcr rechtm\u00e4\u00dfige Gesch\u00e4ftszwecke nutzen\n\u2022 Rechte Dritter respektieren (geistiges Eigentum, Privatsph\u00e4re, Verbraucherschutz)\n\u2022 Die Plattform, andere Nutzer oder Infrastruktur nicht sch\u00e4digen\n\u2022 Den Dienst nicht f\u00fcr Zwecke au\u00dferhalb des Abonnementplans ausnutzen\n\u2022 Europ\u00e4ische, deutsche und ihre eigenen Landesgesetze respektieren\n\nDiese AUP ist keine vollst\u00e4ndige Liste aller verbotenen Handlungen, sondern bietet klare Hinweise und Beispiele. Wir behalten uns das Recht der endg\u00fcltigen Beurteilung dar\u00fcber vor, was eine inakzeptable Nutzung darstellt.',
    },
    section2: {
      title: 'Verbotener Inhalt',
      body: 'SIE D\u00dcRFEN NICHT hochladen, speichern, \u00fcbertragen oder ver\u00f6ffentlichen:\n\n(1) ILLEGALE INHALTE\n\u2022 Materialien, die gegen Strafrecht versto\u00dfen (Terrorismus, Drogen, Prostitution, Gewalt)\n\u2022 Inhalte, die gegen Sanktionen versto\u00dfen (Daten aus eingebrannten L\u00e4ndern)\n\u2022 Materialien, die gegen das Strafgesetzbuch (StGB) versto\u00dfen\n\n(2) SCH\u00c4DLICHE INHALTE MIT KINDERN\n\u2022 Material, das Minderj\u00e4hrige sexualisiert (CSAM)\n\u2022 Inhalte, die Kindergrooming oder -missbrauch erleichtern\n\u2022 Jeder illegale pornografische Inhalt\n\nDIESE KATEGORIE BEWIRKT SOFORTIGE Kontobeendigung und Meldung an zust\u00e4ndige Beh\u00f6rden.\n\n(3) HASSINHALTE\n\u2022 Diskriminierung aufgrund von Rasse, Religion, Geschlecht, sexueller Orientierung\n\u2022 Holocaust-Leugnung und Volksverhetzungssymbole gem\u00e4\u00df \u00a7 130 StGB\n\u2022 Terrorismus- oder Gewaltpropaganda\n\u2022 Inhalte, die k\u00f6rperliche Gewalt anstiften\n\n(4) UNRECHTM\u00c4SSIGER GESCH\u00dcTZTER INHALT\n\u2022 Materialien, die Urheberrecht ohne Lizenz verletzen\n\u2022 Patente, Marken oder Gesch\u00e4ftsgeheimnisse Dritter\n\u2022 Illegal erlangte Gesch\u00e4ftsgeheimnisse\n\n(5) DATENSCHUTZ-VERLETZENDER INHALT\n\u2022 Ohne Rechtsgrundlage erhobene personenbezogene Daten\n\u2022 Doxxing - Ver\u00f6ffentlichung privater Adressen/Identit\u00e4t\n\u2022 Deepfake-Material ohne Einwilligung\n\u2022 Intime Inhalte (NCII) ohne Einwilligung ver\u00f6ffentlicht',
    },
    section3: {
      title: 'Verbotenes Verhalten',
      body: 'SIE D\u00dcRFEN NICHT:\n\n(1) DAS SYSTEM MISSBRAUCHEN\n\u2022 DDoS-Angriffe, Port-Scanning, Exploits\n\u2022 Reverse Engineering der Plattform oder des Codes\n\u2022 Penetrationstests ohne schriftliche Genehmigung\n\u2022 Sicherheitsl\u00fccken ohne verantwortliche Offenlegung ausnutzen\n\u2022 Mehrere Konten zur Umgehung der Limits erstellen\n\n(2) AUTOMATISIERUNG MISSBRAUCHEN\n\u2022 Automatisches Scraping \u00fcber API-Limits hinaus\n\u2022 Bots, die echte Nutzer imitieren\n\u2022 Skripte, die Massendaten kopieren\n\u2022 Unbefugte Crawler\n\u2022 Headless Browser f\u00fcr verd\u00e4chtige Zwecke\n\n(3) E-MAIL MISSBRAUCHEN\n\u2022 Spam-Versand \u00fcber die Plattform\n\u2022 Gekaufte oder nicht-eingewilligte E-Mail-Listen\n\u2022 Phishing oder Identit\u00e4tsbetrug\n\u2022 Massen-E-Mail ohne klare Kennzeichnung\n\n(4) RESSOURCEN MISSBRAUCHEN\n\u2022 Storage-Missbrauch - Nutzung als kostenloses Datei-Hosting\n\u2022 Bandbreiten-Missbrauch - \u00dcberschreitung Ihres Plans\n\u2022 Datenbankabfragen, die Performance-Probleme verursachen\n\u2022 Kryptow\u00e4hrungs-Mining \u00fcber die Plattform\n\n(5) KUNDEN BETR\u00dcGEN\n\u2022 Falsche Werbung von Diensten, die Sie nicht anbieten\n\u2022 Nichterf\u00fcllung vertraglicher Pflichten gegen\u00fcber Endkunden\n\u2022 Datenmanipulation zu illegalen Zwecken\n\u2022 F\u00e4lschung von Transportdokumenten',
    },
    section4: {
      title: 'Technische Grenzen',
      body: 'DIE PLATTFORM HAT DIESE TECHNISCHEN GRENZEN, DIE SIE NICHT UMGEHEN D\u00dcRFEN:\n\n(1) API-RATELIMITS\n\u2022 100 Anfragen pro Minute pro Nutzer (Standard)\n\u2022 1000 Anfragen pro Stunde pro Organisation (Standard)\n\u2022 H\u00f6here Limits f\u00fcr Premium-Pl\u00e4ne verf\u00fcgbar\n\n(2) STORAGE-KONTINGENTE\n\u2022 Gem\u00e4\u00df Abonnementplan (10 GB - 1 TB)\n\u2022 Einzelne Dateien max. 100 MB\n\u2022 Fotos/Scans max. 25 MB\n\n(3) BANDBREITENLIMITS\n\u2022 Egress-Bandbreite je Plan\n\u2022 Spike-Schutz: 10x Durchschnitt f\u00fcr 1 Stunde erlaubt\n\n(4) NUTZERLIMITS\n\u2022 Nutzeranzahl je Plan\n\u2022 Keine "geteilten" oder "Service"-Konten au\u00dferhalb dedizierter Funktionen\n\n(5) DATENBANKABFRAGEN\n\u2022 Max. 50 Zeilen Lesen pro Abfrage (Standard)\n\u2022 Max. 1000 Zeilen Insert/Update pro Batch\n\u2022 Lang laufende Abfragen (>30s) werden automatisch blockiert\n\nVERST\u00d6\u00dfE GEGEN DIESE LIMITS:\n\u2022 Auto-Throttling bei kleineren Verst\u00f6\u00dfen\n\u2022 Vor\u00fcbergehende Sperre bei wiederholten Verst\u00f6\u00dfen\n\u2022 Sofortige Sperre bei Sicherheitsangriffen',
    },
    section5: {
      title: 'Inhalte, die besondere Sorgfalt erfordern',
      body: 'DIESE INHALTSARTEN ERFORDERN KLARE RECHTSGRUNDLAGE UND DOKUMENTATION:\n\n(1) GESUNDHEITSDATEN\nWenn Sie Fahrerdokumente mit Gesundheitsdaten hochladen (\u00e4rztliches Attest usw.):\n\u2022 Fahrer-Einwilligung erforderlich\n\u2022 Rechtsgrundlage muss dokumentiert sein\n\u2022 Eingeschr\u00e4nkter Zugriff nur f\u00fcr autorisierte Personen\n\n(2) MINDERJ\u00c4HRIGEN-DATEN\nWenn Sie Fahrer oder Mitarbeiter unter 18 Jahren haben:\n\u2022 Elterliche Einwilligung erforderlich\n\u2022 Zus\u00e4tzliche Verarbeitungsbeschr\u00e4nkungen\n\u2022 Kann zus\u00e4tzliche Genehmigung erfordern\n\n(3) SENSIBLE FINANZDATEN\n\u2022 Vollst\u00e4ndige Kreditkartennummern - Stripe direkt verwenden\n\u2022 Biometrische Authentifizierungsdaten\n\u2022 Bankkontodaten Dritter\n\n(4) STANDORTDATEN\nGPS-Tracking von Fahrern ist akzeptabel, aber:\n\u2022 Nur w\u00e4hrend Arbeitszeit\n\u2022 Mit klarer Mitteilung an den Fahrer\n\u2022 F\u00fcr betriebliche Zwecke (nicht Total\u00fcberwachung)\n\u2022 Mit L\u00f6schrichtlinie nach 30 Tagen\n\n(5) INHALTE MIT MEHREREN SUBJEKTEN\nFotos oder Videos mit anderen Personen:\n\u2022 Einwilligung aller Personen\n\u2022 Oder klare Rechtsgrundlage\n\u2022 Anonymisierung wenn erforderlich',
    },
    section6: {
      title: 'Verbotene Gesch\u00e4ftsaktivit\u00e4ten',
      body: 'SIE D\u00dcRFEN DIE PLATTFORM NICHT VERWENDEN F\u00dcR:\n\n(1) ILLEGALE AKTIVIT\u00c4TEN\n\u2022 Verkauf von Drogen, Waffen, Sprengstoffen\n\u2022 Menschenhandel\n\u2022 Finanzbetrug (Ponzi, Pyramidenschemen)\n\u2022 Geldw\u00e4sche\n\u2022 Aktivit\u00e4ten, die internationale Sanktionen umgehen\n\n(2) LIZENZIERTE AKTIVIT\u00c4TEN OHNE LIZENZ\n\u2022 Transportdienst ohne Gewerbelizenz\n\u2022 Bef\u00f6rderung gef\u00e4hrlicher G\u00fcter (ADR) ohne Qualifikation\n\u2022 Steueroperationen ohne Genehmigung\n\n(3) VERBRAUCHERBETRUG\n\u2022 Verkauf nicht existierender Produkte\n\u2022 Rechnungsbetrug\n\u2022 Rezensions- oder Bewertungsmanipulation\n\n(4) ZWEIFELHAFTE GAMBLING/CRYPTO-AKTIVIT\u00c4T\n\u2022 Betrieb von Casinos ohne Lizenz in Deutschland\n\u2022 Krypto-Trading ohne BaFin-Genehmigung\n\u2022 Retail-Forex-Trading ohne BaFin-Lizenz\n\nWir haben das Recht, in Verdachtsf\u00e4llen Dokumentation der Gesch\u00e4ftsaktivit\u00e4t zu verlangen. Verweigerung kann zur Sperre f\u00fchren.',
    },
    section7: {
      title: 'Kommunikation mit unserem Team',
      body: 'IN DER KOMMUNIKATION MIT UNSEREM SUPPORT-TEAM:\n\nERLAUBT:\n\u2022 Professionelle technische Fragen\n\u2022 Bug- und Schwierigkeitsberichte\n\u2022 Verbesserungsvorschl\u00e4ge\n\u2022 Konstruktives Feedback\n\nNICHT ERLAUBT:\n\u2022 Missbr\u00e4uchliches Verhalten (Beleidigungen, unangemessene Sprache, Rassismus usw.)\n\u2022 Suche nach pers\u00f6nlichen Informationen der Mitarbeiter\n\u2022 Druck oder Drohungen\n\u2022 Anfragen f\u00fcr illegale Gef\u00e4lligkeiten\n\u2022 Spam in mehreren Tickets\n\nBEI MISSBR\u00c4UCHLICHEM VERHALTEN:\n\u2022 Schriftliche Verwarnung\n\u2022 Support-Kanal-Beschr\u00e4nkung (nur E-Mail)\n\u2022 Kontosperre f\u00fcr schwere F\u00e4lle\n\u2022 Meldung an Beh\u00f6rden bei direkten Drohungen',
    },
    section8: {
      title: 'Reverse Engineering und Eigentum',
      body: 'SIE D\u00dcRFEN NICHT:\n\n(1) CODE REVERSE ENGINEER\n\u2022 Front-End-Code dekompilieren (HTML, JS, CSS)\n\u2022 Back-End-API-Endpunkte zur Replikation analysieren\n\u2022 Unseren Algorithmus zum Kopieren studieren\n\u2022 \u00c4hnliches konkurrierendes Service erstellen\n\n(2) VORTEIL OHNE LIZENZ NEHMEN\n\u2022 Bezahlte Funktionen ohne Zahlung verwenden\n\u2022 Code-Kopieren ohne Lizenz\n\u2022 Hosting in anderer Infrastruktur\n\u2022 Wiederverkauf ohne exklusive schriftliche Genehmigung\n\n(3) GEISTIGES EIGENTUM VERLETZEN\n\u2022 Brand Spoofing - Imitation der Marke\n\u2022 Logo-Diebstahl\n\u2022 Verwendung von Gesch\u00e4ftsgeheimnissen\n\u2022 Dokumentations-Plagiat\n\nINTEROPERABILIT\u00c4T UND DEBUGGING:\nIntegrationsentwicklung mit unserer API (deren Zweck), Debugging von verbindenden Anwendungen und akademische Studien mit klaren Bedingungen sind erlaubt.',
    },
    section9: {
      title: 'Folgen von Verst\u00f6\u00dfen',
      body: 'BEI VERST\u00d6\u00dfEN GEGEN DIE AUP:\n\nEBENE 1 - KLEINERER ODER ERSTER VERSTOSS:\n\u2022 Schriftliche E-Mail-Verwarnung\n\u2022 Korrekturanfrage innerhalb von 7 Tagen\n\u2022 Keine Serviceunterbrechung\n\nEBENE 2 - WIEDERHOLTE VERST\u00d6\u00dfE:\n\u2022 Vor\u00fcbergehende Sperre (7-30 Tage)\n\u2022 Zugriff nur zum Datendownload\n\u2022 Rechnungen werden normal weiter ausgestellt\n\nEBENE 3 - SCHWERER VERSTOSS:\n\u2022 Sofortige Kontosperre\n\u2022 Vollst\u00e4ndig blockierter Zugriff\n\u2022 Kurze Frist (24 Stunden) f\u00fcr Notfall-Download\n\u2022 Vertragsk\u00fcndigungsm\u00f6glichkeit\n\nEBENE 4 - KATASTROPHALER VERSTOSS:\n\u2022 Sofortige und dauerhafte Sperre\n\u2022 Datenl\u00f6schung (nach gesetzlicher Frist)\n\u2022 Meldung an zust\u00e4ndige Beh\u00f6rden\n\u2022 Zivilklage auf Schadenersatz\n\u2022 Weiterleitung an die Polizei in Strafsachen\n\nKATASTROPHALE KATEGORIE UMFASST:\n\u2022 CSAM oder Anti-Kind-Material\n\u2022 Terrorismus oder Gewaltpropaganda\n\u2022 Angriff auf unsere Infrastruktur\n\u2022 Massiver Finanzbetrug\n\u2022 Menschenhandel',
    },
    section10: {
      title: 'Meldung von Verst\u00f6\u00dfen',
      body: 'WENN SIE EINEN VERSTOSS GEGEN DIESE AUP BEMERKEN:\n\nMELDEKAN\u00c4LE:\n\nE-Mail: [abuse@firma.de]\nAntwort: 24-72 Stunden (je nach Dringlichkeit)\n\nF\u00dcR NOTF\u00c4LLE:\nE-Mail: [security@firma.de]\nTelefon: +49 172 8443861 (Gesch\u00e4ftszeiten)\n\nF\u00dcR KINDERBEZOGENE INHALTE:\nWird sofort gemeldet an:\n\u2022 BKA (Bundeskriminalamt) in Deutschland\n\u2022 NCMEC (National Center for Missing & Exploited Children)\n\u2022 Interpol f\u00fcr internationale F\u00e4lle\n\nERFORDERLICHE INFORMATIONEN:\n\u2022 Verd\u00e4chtiges Konto/Nutzer\n\u2022 Beschreibung des Versto\u00dfes\n\u2022 Beweise (Screenshots, Links usw.)\n\u2022 Ihre Kontaktinformationen (f\u00fcr Verfolgung)\n\nWIR GARANTIEREN:\n\u2022 Vertrauliche Behandlung der Meldung\n\u2022 Schutz vor Whistleblower-Vergeltung\n\u2022 Update zum Ermittlungsstand\n\u2022 Professionelle Untersuchung',
    },
    section11: {
      title: 'Plattformschutz',
      body: 'ZUM SCHUTZ DER PLATTFORM VOR VERST\u00d6\u00dfEN VERWENDEN WIR:\n\n(1) AUTOMATISCHE \u00dcBERWACHUNG\n\u2022 Anomalie-Erkennung (ungew\u00f6hnliche Anfragen, verd\u00e4chtige Anmeldungen)\n\u2022 Mustererkennung f\u00fcr Spam, Phishing, Missbrauch\n\u2022 Rate Limiting und DDoS-Schutz\n\u2022 Hash-Scanning f\u00fcr bekannten illegalen Inhalt (PhotoDNA-\u00e4hnlich)\n\n(2) MANUELLE MODERATION\n\u2022 \u00dcberpr\u00fcfung von Nutzermeldungen\n\u2022 Periodisches Audit verd\u00e4chtiger Konten\n\u2022 Untersuchung basierend auf internen Flags\n\n(3) ZUSAMMENARBEIT MIT BEH\u00d6RDEN\n\u2022 Antwort auf rechtliche Beh\u00f6rdenanfragen\n\u2022 Unterst\u00fctzung bei Strafermittlungen bei Bedarf\n\u2022 J\u00e4hrlicher Transparenzbericht\n\nMASSNAHMEN BEINHALTEN NICHT:\n\u2022 Lesen privater Gesch\u00e4ftsdaten ohne Rechtsgrundlage\n\u2022 Proaktive Nutzer\u00fcberwachung\n\u2022 Datenanalyse f\u00fcr Zwecke au\u00dferhalb der Sicherheit\n\u2022 Profiling f\u00fcr Marketingzwecke\n\nDIE PRIVATSPH\u00c4RE DER KUNDEN BLEIBT PRIORIT\u00c4T.',
    },
    section12: {
      title: 'Einspruchsrecht',
      body: 'WENN IHR KONTO GESPERRT ODER BEENDET WIRD:\n\n1. BENACHRICHTIGUNG\nSie erhalten eine E-Mail mit klaren Gr\u00fcnden innerhalb von 24 Stunden nach der Ma\u00dfnahme.\n\n2. EINSPRUCHSFRIST\nSie haben 30 Tage Zeit, einen Einspruch einzureichen an:\n[appeals@firma.de]\n\n3. EINSPRUCHSPROZESS\n\u2022 \u00dcberpr\u00fcfung durch unabh\u00e4ngiges Team (nicht dasselbe, das entschieden hat)\n\u2022 M\u00f6glichkeit, zus\u00e4tzliche Informationen oder Kontext zu liefern\n\u2022 Schriftliche Antwort innerhalb von 14 Tagen\n\u2022 Endg\u00fcltige Entscheidung mit Erkl\u00e4rung\n\n4. BEI GENEHMIGTEM EINSPRUCH\n\u2022 Konto- und Datenwiederherstellung\n\u2022 Entsch\u00e4digung f\u00fcr Ausfallzeit (gem\u00e4\u00df SLA)\n\u2022 Verfahrensaktualisierung zur Vermeidung von Wiederholungen\n\n5. BEI ABGELEHNTEM EINSPRUCH\n\u2022 Zus\u00e4tzliche 30 Tage zum Datendownload\n\u2022 Endg\u00fcltige Antwort mit Begr\u00fcndung\n\u2022 Gerichtliche \u00dcberpr\u00fcfungsm\u00f6glichkeit\n\nF\u00dcR KATASTROPHALE BEENDIGUNG (CSAM, Terrorismus):\nKein Einspruchsverfahren - Ma\u00dfnahme ist dauerhaft und wird Beh\u00f6rden gemeldet.',
    },
    section13: {
      title: '\u00c4nderungen an der AUP',
      body: 'DIESE AUP KANN SICH \u00c4NDERN, UM FOLGENDES WIDERZUSPIEGELN:\n\n\u2022 Neue Arten von Missbrauch (Cyber, rechtlich)\n\u2022 \u00c4nderungen in Gesetzen (StGB, BDSG, DSGVO usw.)\n\u2022 Best Practices aus der Industrie\n\u2022 Feedback der Nutzergemeinschaft\n\nKOMMUNIKATION DER \u00c4NDERUNGEN:\n\u2022 E-Mail an alle aktiven Nutzer 30 Tage im Voraus\n\u2022 Plattform-Banner\n\u2022 Aktualisierter Datumsstempel oben im Dokument\n\nANNAHME:\n\u2022 Fortgesetzte Nutzung nach \u00c4nderungen gilt als Annahme\n\u2022 Sie k\u00f6nnen das Konto k\u00fcndigen, wenn Sie nicht zustimmen\n\nNOTFALLAKTUALISIERUNGEN:\nNotfall-Sicherheitsaktualisierungen k\u00f6nnen ohne die 30-Tage-Frist erfolgen, aber wir werden Sie so bald wie m\u00f6glich benachrichtigen.',
    },
    section14: {
      title: 'H\u00f6here Gewalt und au\u00dfergew\u00f6hnliche Umst\u00e4nde',
      body: 'IN AUSSERORDENTLICHEN UMST\u00c4NDEN K\u00d6NNEN WIR:\n\n(1) DIENST AUSSETZEN, UM SYSTEM ZU SCH\u00dcTZEN\n\u2022 Aktiver Cyber-Angriff\n\u2022 Malware-Erkennung\n\u2022 Kritische Sicherheitsl\u00fccke\n\u2022 H\u00f6here Gewalt (Krieg, Naturkatastrophen)\n\n(2) DIENST BEENDEN BEI RECHTLICHER OPPOSITION\n\u2022 Gerichtsbeschluss\n\u2022 Internationale Sanktionen\n\u2022 Drastische Gesetzes\u00e4nderung\n\u2022 Insolvenz oder Zahlungsunf\u00e4higkeit\n\n(3) MIT MINIMALER VORWARNUNG BENACHRICHTIGEN\nF\u00fcr Notf\u00e4lle k\u00f6nnen wir Sie kurzfristig benachrichtigen (1-48 Stunden).\n\nENTSCH\u00c4DIGUNG:\n\u2022 Pro-rata-R\u00fcckerstattung f\u00fcr verk\u00fcrzten Zeitraum\n\u2022 Erleichterte Datenexport\n\u2022 Alternativer Dienst wenn m\u00f6glich\n\nDIES SIND SELTENE UMST\u00c4NDE, ABER RECHTLICHE M\u00d6GLICHKEITEN.',
    },
    section15: {
      title: 'Kontakt und Fragen',
      body: 'FRAGEN ZU DIESER AUP:\nE-Mail: [legal@firma.de]\nAntwort innerhalb von 14 Tagen.\n\nVERSTOSS-MELDUNGEN:\nE-Mail: [abuse@firma.de]\nDringend: 24-72 Stunden\n\nSICHERHEITSVORF\u00c4LLE:\nE-Mail: [security@firma.de]\nTelefon: +49 172 8443861\n\nEINSPR\u00dcCHE:\nE-Mail: [appeals@firma.de]\nFrist: 30 Tage ab Sperrung\n\nALLGEMEINER SUPPORT:\nE-Mail: [support@firma.de]\n\nDSB:\nE-Mail: dpo@mm-logistic.eu\n\nOFFIZIELLE POST:\nMar Group (Genton Maliqi)\nPfädlistraße 10, 79576 Weil am Rhein, Germany\nDeutschland\n\nBESCHWERDERECHT:\nSie k\u00f6nnen Beschwerden bei Aufsichtsbeh\u00f6rden wie BfDI (f\u00fcr Datenschutz) oder Polizei (f\u00fcr Verbrechen) einreichen.',
    },
  },

  // ============================================================
  // FRENCH (FR)
  // ============================================================
  fr: {
    shortTitle: 'Usage acceptable',
    title: 'Politique d\'Usage Acceptable (PUA)',
    subtitle: 'Ce qui est et n\'est pas autoris\u00e9 lors de l\'utilisation de notre plateforme. Pour prot\u00e9ger tous les utilisateurs.',
    intro: 'Cette Politique d\'Usage Acceptable ("PUA") d\u00e9finit ce que les utilisateurs ne sont pas autoris\u00e9s \u00e0 faire avec la plateforme mm-logistic. Elle fait partie int\u00e9grante des Conditions G\u00e9n\u00e9rales d\'Utilisation (CGU) et les violations peuvent entra\u00eener la suspension ou la r\u00e9siliation du compte. Nous visons \u00e0 maintenir un environnement s\u00fbr, l\u00e9gal et professionnel pour tous nos clients.',
    lastUpdated: '15 mai 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Principes fondamentaux',
      body: 'Les utilisateurs doivent:\n\n\u2022 Utiliser la plateforme uniquement \u00e0 des fins commerciales l\u00e9gales\n\u2022 Respecter les droits des tiers (propri\u00e9t\u00e9 intellectuelle, vie priv\u00e9e, protection des consommateurs)\n\u2022 Ne pas nuire \u00e0 la plateforme, aux autres utilisateurs ou \u00e0 l\'infrastructure\n\u2022 Ne pas exploiter le service \u00e0 des fins en dehors du plan d\'abonnement\n\u2022 Respecter les lois europ\u00e9ennes, allemandes et de leur propre pays\n\nCette PUA n\'est pas une liste compl\u00e8te de toutes les actions interdites, mais fournit des directives claires et des exemples. Nous nous r\u00e9servons le droit de jugement final sur ce qui constitue une utilisation inacceptable.',
    },
    section2: {
      title: 'Contenu interdit',
      body: 'VOUS NE POUVEZ PAS t\u00e9l\u00e9charger, stocker, transmettre ou publier:\n\n(1) CONTENU ILL\u00c9GAL\n\u2022 Mat\u00e9riaux violant le droit p\u00e9nal (terrorisme, drogues, prostitution, violence)\n\u2022 Contenu violant les sanctions (donn\u00e9es de pays sous embargo)\n\u2022 Mat\u00e9riaux violant le Strafgesetzbuch (Code p\u00e9nal allemand)\n\n(2) CONTENU NUISIBLE IMPLIQUANT DES ENFANTS\n\u2022 Mat\u00e9riel sexualisant les mineurs (CSAM)\n\u2022 Contenu facilitant le grooming ou les abus sur enfants\n\u2022 Tout contenu pornographique ill\u00e9gal\n\nCETTE CAT\u00c9GORIE PROVOQUE LA r\u00e9siliation IMM\u00c9DIATE du compte et le signalement aux autorit\u00e9s comp\u00e9tentes.\n\n(3) CONTENU HAINEUX\n\u2022 Discrimination bas\u00e9e sur la race, religion, sexe, orientation sexuelle\n\u2022 D\u00e9ni de l\'Holocauste et symboles Volksverhetzung selon \u00a7 130 StGB\n\u2022 Propagande terroriste ou de violence\n\u2022 Contenu incitant \u00e0 la violence physique\n\n(4) CONTENU PROPRI\u00c9TAIRE ILL\u00c9GAL\n\u2022 Mat\u00e9riaux violant le droit d\'auteur sans licence\n\u2022 Brevets, marques ou secrets commerciaux de tiers\n\u2022 Secrets commerciaux obtenus ill\u00e9galement\n\n(5) CONTENU VIOLANT LA VIE PRIV\u00c9E\n\u2022 Donn\u00e9es personnelles obtenues sans base juridique\n\u2022 Doxxing - publication d\'adresses/identit\u00e9 priv\u00e9es\n\u2022 Mat\u00e9riel deepfake produit sans consentement\n\u2022 Contenu intime (NCII) publi\u00e9 sans consentement',
    },
    section3: {
      title: 'Comportement interdit',
      body: 'VOUS NE POUVEZ PAS:\n\n(1) ABUSER DU SYST\u00c8ME\n\u2022 Attaques DDoS, scan de ports, exploits\n\u2022 R\u00e9tro-ing\u00e9nierie de la plateforme ou du code\n\u2022 Tests de p\u00e9n\u00e9tration sans autorisation \u00e9crite\n\u2022 Exploiter des bugs de s\u00e9curit\u00e9 sans divulgation responsable\n\u2022 Cr\u00e9er plusieurs comptes pour contourner les limites\n\n(2) ABUSER DE L\'AUTOMATISATION\n\u2022 Scraping automatis\u00e9 au-del\u00e0 des limites API\n\u2022 Bots imitant de vrais utilisateurs\n\u2022 Scripts copiant des donn\u00e9es en masse\n\u2022 Crawlers non autoris\u00e9s\n\u2022 Navigateurs headless \u00e0 des fins suspectes\n\n(3) ABUSER DE L\'E-MAIL\n\u2022 Envoi de spam via la plateforme\n\u2022 Listes e-mail achet\u00e9es ou sans consentement\n\u2022 Phishing ou usurpation d\'identit\u00e9\n\u2022 E-mail en masse sans identification claire\n\n(4) ABUSER DES RESSOURCES\n\u2022 Abus de stockage - utilisation comme h\u00e9bergement gratuit de fichiers\n\u2022 Abus de bande passante - d\u00e9passement de votre plan\n\u2022 Requ\u00eates de base de donn\u00e9es causant des probl\u00e8mes de performance\n\u2022 Minage de cryptomonnaie via la plateforme\n\n(5) FRAUDER LES CLIENTS\n\u2022 Publicit\u00e9 mensong\u00e8re de services non fournis\n\u2022 Non-respect des obligations contractuelles envers les clients finaux\n\u2022 Manipulation de donn\u00e9es \u00e0 des fins ill\u00e9gales\n\u2022 Falsification de documents de transport',
    },
    section4: {
      title: 'Limites techniques',
      body: 'LA PLATEFORME A CES LIMITES TECHNIQUES QUE VOUS NE POUVEZ PAS CONTOURNER:\n\n(1) LIMITES DE TAUX API\n\u2022 100 requ\u00eates par minute par utilisateur (d\u00e9faut)\n\u2022 1000 requ\u00eates par heure par organisation (d\u00e9faut)\n\u2022 Limites plus \u00e9lev\u00e9es disponibles pour les plans premium\n\n(2) QUOTAS DE STOCKAGE\n\u2022 Selon le plan d\'abonnement (10 Go - 1 To)\n\u2022 Fichiers individuels max 100 Mo\n\u2022 Photos/scans max 25 Mo\n\n(3) LIMITES DE BANDE PASSANTE\n\u2022 Bande passante egress selon le plan\n\u2022 Protection contre les pics: 10x la moyenne autoris\u00e9e pendant 1 heure\n\n(4) LIMITES D\'UTILISATEURS\n\u2022 Nombre d\'utilisateurs selon le plan\n\u2022 Pas de comptes "partag\u00e9s" ou "service" en dehors des fonctions d\u00e9di\u00e9es\n\n(5) REQU\u00caTES DE BASE DE DONN\u00c9ES\n\u2022 Max 50 lignes lues par requ\u00eate (d\u00e9faut)\n\u2022 Max 1000 lignes insert/update par batch\n\u2022 Requ\u00eates de longue dur\u00e9e (>30s) automatiquement bloqu\u00e9es\n\nVIOLATIONS DE CES LIMITES:\n\u2022 Auto-limitation pour les violations mineures\n\u2022 Suspension temporaire pour les violations r\u00e9p\u00e9t\u00e9es\n\u2022 Suspension imm\u00e9diate pour les attaques de s\u00e9curit\u00e9',
    },
    section5: {
      title: 'Contenu n\u00e9cessitant un soin particulier',
      body: 'CES TYPES DE CONTENU N\u00c9CESSITENT UNE BASE JURIDIQUE CLAIRE ET UNE DOCUMENTATION:\n\n(1) DONN\u00c9ES DE SANT\u00c9\nSi vous t\u00e9l\u00e9chargez des documents de chauffeur avec donn\u00e9es de sant\u00e9 (certificat m\u00e9dical, etc.):\n\u2022 Consentement du chauffeur requis\n\u2022 Base juridique doit \u00eatre document\u00e9e\n\u2022 Acc\u00e8s restreint uniquement aux personnes autoris\u00e9es\n\n(2) DONN\u00c9ES DE MINEURS\nSi vous avez des chauffeurs ou employ\u00e9s de moins de 18 ans:\n\u2022 Consentement parental requis\n\u2022 Restrictions de traitement suppl\u00e9mentaires\n\u2022 Peut n\u00e9cessiter une approbation suppl\u00e9mentaire\n\n(3) DONN\u00c9ES FINANCI\u00c8RES SENSIBLES\n\u2022 Num\u00e9ros complets de cartes de cr\u00e9dit - utiliser Stripe directement\n\u2022 Donn\u00e9es d\'authentification biom\u00e9triques\n\u2022 Donn\u00e9es de comptes bancaires de tiers\n\n(4) DONN\u00c9ES DE LOCALISATION\nLe suivi GPS des chauffeurs est acceptable, mais:\n\u2022 Uniquement pendant les heures de travail\n\u2022 Avec notification claire au chauffeur\n\u2022 \u00c0 des fins op\u00e9rationnelles (pas de surveillance totale)\n\u2022 Avec politique de suppression apr\u00e8s 30 jours\n\n(5) CONTENU IMPLIQUANT PLUSIEURS SUJETS\nPhotos ou vid\u00e9os avec d\'autres personnes:\n\u2022 Consentement de toutes les personnes\n\u2022 Ou base juridique claire\n\u2022 Anonymisation lorsque requise',
    },
    section6: {
      title: 'Activit\u00e9s commerciales interdites',
      body: 'VOUS NE POUVEZ PAS UTILISER LA PLATEFORME POUR:\n\n(1) ACTIVIT\u00c9S ILL\u00c9GALES\n\u2022 Vente de drogues, armes, explosifs\n\u2022 Trafic humain\n\u2022 Fraude financi\u00e8re (Ponzi, sch\u00e9mas pyramidaux)\n\u2022 Blanchiment d\'argent\n\u2022 Activit\u00e9s contournant les sanctions internationales\n\n(2) ACTIVIT\u00c9S LICENCI\u00c9ES SANS LICENCE\n\u2022 Service de transport sans licence commerciale\n\u2022 Transport de marchandises dangereuses (ADR) sans qualification\n\u2022 Op\u00e9rations fiscales sans autorisation\n\n(3) FRAUDE DES CONSOMMATEURS\n\u2022 Vente de produits inexistants\n\u2022 Fraude de facturation\n\u2022 Manipulation d\'avis ou d\'\u00e9valuations\n\n(4) ACTIVIT\u00c9 DOUTEUSE GAMBLING/CRYPTO\n\u2022 Exploitation de casino sans licence en Allemagne\n\u2022 Trading crypto sans autorisation BaFin\n\u2022 Trading forex retail sans licence BaFin\n\nNous avons le droit de demander la documentation de l\'activit\u00e9 commerciale en cas de suspicion. Le refus peut entra\u00eener la suspension.',
    },
    section7: {
      title: 'Communication avec notre \u00e9quipe',
      body: 'EN COMMUNICATION AVEC NOTRE \u00c9QUIPE SUPPORT:\n\nAUTORIS\u00c9:\n\u2022 Questions techniques professionnelles\n\u2022 Rapports de bugs et difficult\u00e9s\n\u2022 Suggestions d\'am\u00e9lioration\n\u2022 Feedback constructif\n\nNON AUTORIS\u00c9:\n\u2022 Comportement abusif (insultes, langage inappropri\u00e9, racisme, etc.)\n\u2022 Recherche d\'informations personnelles du personnel\n\u2022 Pression ou menaces\n\u2022 Demandes de faveurs ill\u00e9gales\n\u2022 Spam dans plusieurs tickets\n\nEN CAS DE COMPORTEMENT ABUSIF:\n\u2022 Avertissement \u00e9crit\n\u2022 Restriction du canal support (e-mail uniquement)\n\u2022 Suspension de compte pour les cas graves\n\u2022 Signalement aux autorit\u00e9s en cas de menaces directes',
    },
    section8: {
      title: 'R\u00e9tro-ing\u00e9nierie et propri\u00e9t\u00e9',
      body: 'VOUS NE POUVEZ PAS:\n\n(1) R\u00c9TRO-ING\u00c9NIERIE DU CODE\n\u2022 D\u00e9compiler le code front-end (HTML, JS, CSS)\n\u2022 Analyser les endpoints API back-end pour r\u00e9plication\n\u2022 \u00c9tudier notre algorithme pour copier\n\u2022 Cr\u00e9er un service concurrent similaire\n\n(2) PROFITER SANS LICENCE\n\u2022 Utiliser des fonctionnalit\u00e9s payantes sans paiement\n\u2022 Copier le code sans licence\n\u2022 H\u00e9berger sur une autre infrastructure\n\u2022 Revendre sans autorisation \u00e9crite exclusive\n\n(3) VIOLER LA PROPRI\u00c9T\u00c9 INTELLECTUELLE\n\u2022 Brand spoofing - imitation de la marque\n\u2022 Vol de logo\n\u2022 Utilisation de secrets commerciaux\n\u2022 Plagiat de la documentation\n\nINTEROP\u00c9RABILIT\u00c9 ET D\u00c9BOGAGE:\nLe d\u00e9veloppement d\'int\u00e9gration avec notre API (son objectif), le d\u00e9bogage d\'applications qui se connectent \u00e0 nous, et les \u00e9tudes acad\u00e9miques avec des conditions claires sont autoris\u00e9s.',
    },
    section9: {
      title: 'Cons\u00e9quences des violations',
      body: 'EN CAS DE VIOLATIONS DE LA PUA:\n\nNIVEAU 1 - VIOLATION MINEURE OU PREMI\u00c8RE:\n\u2022 Avertissement \u00e9crit par e-mail\n\u2022 Demande de correction sous 7 jours\n\u2022 Pas de suspension du service\n\nNIVEAU 2 - VIOLATIONS R\u00c9P\u00c9T\u00c9ES:\n\u2022 Suspension temporaire (7-30 jours)\n\u2022 Acc\u00e8s uniquement pour t\u00e9l\u00e9chargement des donn\u00e9es\n\u2022 Les factures continuent normalement\n\nNIVEAU 3 - VIOLATION GRAVE:\n\u2022 Suspension imm\u00e9diate du compte\n\u2022 Acc\u00e8s totalement bloqu\u00e9\n\u2022 P\u00e9riode courte (24 heures) pour t\u00e9l\u00e9chargement d\'urgence\n\u2022 Possibilit\u00e9 de r\u00e9siliation du contrat\n\nNIVEAU 4 - VIOLATION CATASTROPHIQUE:\n\u2022 Suspension imm\u00e9diate et permanente\n\u2022 Suppression des donn\u00e9es (apr\u00e8s d\u00e9lai l\u00e9gal)\n\u2022 Signalement aux autorit\u00e9s comp\u00e9tentes\n\u2022 Action civile en dommages\n\u2022 Transmission \u00e0 la police dans les cas criminels\n\nCAT\u00c9GORIE CATASTROPHIQUE COMPREND:\n\u2022 CSAM ou mat\u00e9riel anti-enfant\n\u2022 Terrorisme ou propagande de violence\n\u2022 Attaque sur notre infrastructure\n\u2022 Fraude financi\u00e8re massive\n\u2022 Trafic humain',
    },
    section10: {
      title: 'Signalement des violations',
      body: 'SI VOUS REMARQUEZ UNE VIOLATION DE CETTE PUA:\n\nCANAUX DE SIGNALEMENT:\n\nE-mail: [abuse@entreprise.de]\nR\u00e9ponse: 24-72 heures (selon urgence)\n\nPOUR LES CAS D\'URGENCE:\nE-mail: [security@entreprise.de]\nT\u00e9l\u00e9phone: +49 172 8443861 (heures de bureau)\n\nPOUR CONTENU IMPLIQUANT DES ENFANTS:\nSera signal\u00e9 imm\u00e9diatement \u00e0:\n\u2022 BKA (Bundeskriminalamt) en Allemagne\n\u2022 NCMEC (National Center for Missing & Exploited Children)\n\u2022 Interpol pour les cas internationaux\n\nINFORMATIONS REQUISES:\n\u2022 Compte/utilisateur suspect\n\u2022 Description de la violation\n\u2022 Preuves (captures d\'\u00e9cran, liens, etc.)\n\u2022 Vos coordonn\u00e9es (pour suivi)\n\nNOUS GARANTISSONS:\n\u2022 Traitement confidentiel des signalements\n\u2022 Protection contre les repr\u00e9sailles aux whistleblowers\n\u2022 Mise \u00e0 jour sur le statut de l\'enqu\u00eate\n\u2022 Enqu\u00eate professionnelle',
    },
    section11: {
      title: 'Protection de la plateforme',
      body: 'POUR PROT\u00c9GER LA PLATEFORME CONTRE LES VIOLATIONS, NOUS UTILISONS:\n\n(1) SURVEILLANCE AUTOMATIQUE\n\u2022 D\u00e9tection d\'anomalies (requ\u00eates anormales, connexions suspectes)\n\u2022 Reconnaissance de motifs pour spam, phishing, abus\n\u2022 Limitation de d\u00e9bit et protection DDoS\n\u2022 Hash scanning pour contenu ill\u00e9gal connu (de type PhotoDNA)\n\n(2) MOD\u00c9RATION MANUELLE\n\u2022 Examen des signalements utilisateurs\n\u2022 Audit p\u00e9riodique des comptes suspects\n\u2022 Enqu\u00eate bas\u00e9e sur drapeaux internes\n\n(3) COOP\u00c9RATION AVEC LES AUTORIT\u00c9S\n\u2022 R\u00e9ponse aux demandes l\u00e9gales des autorit\u00e9s\n\u2022 Soutien aux enqu\u00eates criminelles au besoin\n\u2022 Rapport annuel de transparence\n\nLES MESURES N\'INCLUENT PAS:\n\u2022 Lecture de donn\u00e9es priv\u00e9es d\'entreprise sans base juridique\n\u2022 Surveillance proactive des utilisateurs\n\u2022 Analyse de donn\u00e9es \u00e0 des fins en dehors de la s\u00e9curit\u00e9\n\u2022 Profilage \u00e0 des fins marketing\n\nLA CONFIDENTIALIT\u00c9 DES CLIENTS RESTE UNE PRIORIT\u00c9.',
    },
    section12: {
      title: 'Droit d\'appel',
      body: 'SI VOTRE COMPTE EST SUSPENDU OU R\u00c9SILI\u00c9:\n\n1. NOTIFICATION\nVous recevrez un e-mail avec des raisons claires dans les 24 heures suivant l\'action.\n\n2. D\u00c9LAI D\'APPEL\nVous avez 30 jours pour soumettre un appel \u00e0:\n[appeals@entreprise.de]\n\n3. PROCESSUS D\'APPEL\n\u2022 Examen par une \u00e9quipe ind\u00e9pendante (pas la m\u00eame qui a d\u00e9cid\u00e9)\n\u2022 Possibilit\u00e9 de fournir des informations suppl\u00e9mentaires ou du contexte\n\u2022 R\u00e9ponse \u00e9crite dans les 14 jours\n\u2022 D\u00e9cision finale avec explication\n\n4. SI L\'APPEL EST APPROUV\u00c9\n\u2022 Restauration du compte et des donn\u00e9es\n\u2022 Compensation pour le temps d\'indisponibilit\u00e9 (selon SLA)\n\u2022 Mise \u00e0 jour de la proc\u00e9dure pour \u00e9viter la r\u00e9currence\n\n5. SI L\'APPEL EST REJET\u00c9\n\u2022 30 jours suppl\u00e9mentaires pour t\u00e9l\u00e9charger les donn\u00e9es\n\u2022 R\u00e9ponse finale avec raisonnement\n\u2022 Possibilit\u00e9 d\'examen judiciaire\n\nPOUR R\u00c9SILIATION CATASTROPHIQUE (CSAM, terrorisme):\nPas de proc\u00e9dure d\'appel - l\'action est permanente et signal\u00e9e aux autorit\u00e9s.',
    },
    section13: {
      title: 'Modifications de la PUA',
      body: 'CETTE PUA PEUT CHANGER POUR REFL\u00c9TER:\n\n\u2022 Nouveaux types d\'abus (cyber, juridique)\n\u2022 Changements dans les lois (StGB, BDSG, RGPD, etc.)\n\u2022 Meilleures pratiques de l\'industrie\n\u2022 Feedback de la communaut\u00e9 d\'utilisateurs\n\nCOMMUNICATION DES CHANGEMENTS:\n\u2022 E-mail \u00e0 tous les utilisateurs actifs 30 jours \u00e0 l\'avance\n\u2022 Banni\u00e8re sur la plateforme\n\u2022 Horodatage mis \u00e0 jour en haut du document\n\nACCEPTATION:\n\u2022 L\'utilisation continue apr\u00e8s les changements constitue l\'acceptation\n\u2022 Vous pouvez r\u00e9silier le compte si vous n\'\u00eates pas d\'accord\n\nMISES \u00c0 JOUR D\'URGENCE:\nLes mises \u00e0 jour de s\u00e9curit\u00e9 d\'urgence peuvent \u00eatre faites sans la p\u00e9riode de 30 jours, mais nous vous notifierons d\u00e8s que possible.',
    },
    section14: {
      title: 'Force majeure et circonstances exceptionnelles',
      body: 'DANS DES CIRCONSTANCES EXCEPTIONNELLES, NOUS POUVONS:\n\n(1) SUSPENDRE LE SERVICE POUR PROT\u00c9GER LE SYST\u00c8ME\n\u2022 Cyberattaque active\n\u2022 D\u00e9tection de malware\n\u2022 Vuln\u00e9rabilit\u00e9 de s\u00e9curit\u00e9 critique\n\u2022 Force majeure (guerre, catastrophes naturelles)\n\n(2) R\u00c9SILIER LE SERVICE POUR OPPOSITION L\u00c9GALE\n\u2022 Ordonnance du tribunal\n\u2022 Sanctions internationales\n\u2022 Changement de loi drastique\n\u2022 Faillite ou insolvabilit\u00e9\n\n(3) NOTIFIER AVEC AVERTISSEMENT MINIMAL\nPour les cas d\'urgence, nous pouvons vous notifier \u00e0 court terme (1-48 heures).\n\nCOMPENSATION:\n\u2022 Remboursement au prorata pour p\u00e9riode raccourcie\n\u2022 Exportation de donn\u00e9es facilit\u00e9e\n\u2022 Service alternatif lorsque possible\n\nCE SONT DES CIRCONSTANCES RARES MAIS DES POSSIBILIT\u00c9S L\u00c9GALES.',
    },
    section15: {
      title: 'Contact et questions',
      body: 'QUESTIONS SUR CETTE PUA:\nE-mail: [legal@entreprise.de]\nR\u00e9ponse dans les 14 jours.\n\nSIGNALEMENTS DE VIOLATION:\nE-mail: [abuse@entreprise.de]\nUrgent: 24-72 heures\n\nINCIDENTS DE S\u00c9CURIT\u00c9:\nE-mail: [security@entreprise.de]\nT\u00e9l\u00e9phone: +49 172 8443861\n\nAPPELS:\nE-mail: [appeals@entreprise.de]\nD\u00e9lai: 30 jours depuis la suspension\n\nSUPPORT G\u00c9N\u00c9RAL:\nE-mail: [support@entreprise.de]\n\nDPO:\nE-mail: dpo@mm-logistic.eu\n\nCOURRIER OFFICIEL:\nMar Group (Genton Maliqi)\nPfädlistraße 10, 79576 Weil am Rhein, Germany\nAllemagne\n\nDROIT DE PLAINTE:\nVous pouvez d\u00e9poser des plaintes aupr\u00e8s d\'autorit\u00e9s de surveillance comme BfDI (pour la vie priv\u00e9e) ou la police (pour les crimes).',
    },
  },
};
