/**
 * Intellectual Property Protection Notice
 *
 * Protects the MM Logistic platform under:
 * - German Copyright Act (UrhG) §§ 2, 69a–69g (software as literary work)
 * - EU Directive 2009/24/EC (legal protection of computer programs)
 * - EU Directive 2001/29/EC (InfoSoc — harmonisation of copyright)
 * - German Trade Secret Act (GeschGehG) for business logic & algorithms
 * - German Act against Unfair Competition (UWG) § 4 No. 3 (parasitic copying)
 *
 * Operator: Genton Maliqi, trading as "Mar Group" (EI, France),
 * operating from Weil am Rhein, Germany. Jurisdiction: Landgericht
 * Freiburg im Breisgau.
 */

export const ipProtection = {
  // ============================================================
  // ALBANIAN (SQ)
  // ============================================================
  sq: {
    shortTitle: 'Mbrojtja IP',
    title: 'Mbrojtja e Pronesise Intelektuale',
    subtitle: 'Njoftim ligjor per mbrojtjen e platformes MM Logistic, kodit burimor, logjikes se biznesit dhe te gjitha aseteve dixhitale.',
    intro: 'Platforma MM Logistic — duke perfshire kodin burimor, arkitekturen e softuerit, strukturen e bazes se te dhenave, nderlidhjet e API-ve, dizajnin e nderfaces se perdoruesit, logjiken e biznesit dhe te gjitha komponentet shoqeruese — eshte veper origjinale e krijuar ekskluzivisht nga Mar Group (Genton Maliqi, EI). Asnje pjese e kesaj platforme nuk eshte kopjuar ose rrjedhur nga asnje pale e trete. Kjo veper mbrohet nga ligji gjerman dhe evropian i te drejtave te autorit, ligji i sekreteve tregtare dhe ligji kunder konkurrences se pandershme. Cdo kopjim, riprodhim ose perdorim i paautorizuar do te ndiqet me te gjitha mjetet ligjore te disponueshme.',
    lastUpdated: '27 Maj 2026',
    version: 'Versioni 1.0',

    section1: {
      title: 'Deklarata e origjinalitetit',
      body: 'Platforma MM Logistic eshte projektuar, zhvilluar dhe ndertuar teresiisht nga Mar Group (Genton Maliqi, Entrepreneur individuel, regjistruar ne France, me adrese operuese ne Weil am Rhein, Gjermani).\n\nKjo platforme perfshin:\n\n\u2022 Mbi 50 funksione serverless (Edge Functions) per logjistike, flotila, kontabilitet, njoftime dhe integrime me paleta te treta\n\u2022 Mbi 100 migrime te bazes se te dhenave me izolim te plote te qiraxhinjve (multi-tenant)\n\u2022 Arkitekture me shume role (super_admin, company_admin, logistics_admin, depot_worker, driver)\n\u2022 Perkthim i plote ne 4 gjuhe (shqip, anglisht, gjermanisht, frengjisht)\n\u2022 Module per menaxhimin e flotes, depove, riparime, sortim paletash, kontabilitet me DATEV/SAF-T, HR, GPS ne kohe reale, dhe me shume\n\nAsnje pjese e kodit, logjikes, dizajnit ose arkitektures nuk eshte kopjuar nga asnje burim i trete. E gjithe puna perfaqeson krijimtari origjinale te pavarur.',
    },
    section2: {
      title: 'Baza ligjore e mbrojtjes',
      body: 'Platforma MM Logistic mbrohet nga korniza te shumta ligjore:\n\n(a) LIGJI GJERMAN I TE DREJTAVE TE AUTORIT (UrhG)\nProgramet kompjuterike mbrohen si vepra letrare sipas § 2 paragrafit 1 nr. 1 dhe §§ 69a–69g UrhG. Kjo mbrojtje shtrihet ne kodin burimor, kodin e kompiluar, materialin e dizajnit pergatitor dhe dokumentacionin.\n\n(b) DIREKTIVA E BE-se 2009/24/KE\nOfron mbrojtje te harmonizuar per programet kompjuterike ne te gjithe Bashkimin Europian, duke perfshire mbrojtje kunder riprodhimit, pershtatjes dhe shperndarjes se paautorizuar.\n\n(c) DIREKTIVA E BE-se 2001/29/KE (InfoSoc)\nHarmonizon aspekte te te drejtave te autorit dhe te drejtave te lidhura ne shoqerine e informacionit.\n\n(d) LIGJI GJERMAN I SEKRETEVE TREGTARE (GeschGehG)\nLogjika e biznesit, algoritmet, skjemat e bazes se te dhenave dhe njohurite e proceseve te platformes perbejne sekrete tregtare te mbrojtura sipas GeschGehG, i cili zbaton Direktiven e BE-se (BE) 2016/943.\n\n(e) LIGJI GJERMAN KUNDER KONKURRENCES SE PANDERSHME (UWG)\n§ 4 nr. 3 UWG ndalon kopjimin parazitar te arritjeve tregtare. Kopjimi i karakteristikave, rrjedhave te punes ose arkitektures se platformes mund te perbeje konkurrence te pandershme edhe nese kopja nuk eshte identike.',
    },
    section3: {
      title: 'Fusha e mbrojtjes',
      body: 'Asetet e meposhtme mbrohen plotesisht sipas ligjeve te permendura me siper:\n\n\u2022 KODI BURIMOR — Te gjitha skedaret TypeScript, React, SQL dhe Deno qe perbejne aplikacionin front-end dhe funksionet back-end\n\u2022 ARKITEKTURA E BAZES SE TE DHENAVE — Skjemat, migracimet, politikat e sigurise ne nivel rreshti (RLS) dhe logjika e izolimit te qiraxhinjve\n\u2022 LOGJIKA E BIZNESIT — Algoritmet per menaxhimin e stokut, rrjedhjet e punes se dorezimit, motoret e perputhshmerise, llogaritjet e kontabilitetit, optimizimi i rrugeve\n\u2022 DIZAJNI I NDERFACES SE PERDORUESIT — Faqosjet, komponentet, sistemet e dizajnit vizual, animacionet dhe nderveprimi\n\u2022 DIZAJNI I API-ve — Strukturat endpoint, formatet e kerkesave/pergjigjeve, mekanizmat e autentikimit\n\u2022 DOKUMENTACIONI — Dokumentacioni teknik, udhezimet e perdoruesit, shenimet e migrimit dhe materialet e brendshme te procesit\n\u2022 PERKTHIMET — Permbajtja e lokalizuar ne katermit gjuhet e mbeshtetura\n\u2022 ASETET VIZUALE — Logot, ikonat, imazhet dhe elementet e markimit',
    },
    section4: {
      title: 'Veprime te ndaluara',
      body: 'Veprimet e meposhtme jane rreptesisht te ndaluara pa autorizim te shkruar paraprak nga Mar Group:\n\n(1) KOPJIM DHE RIPRODHIM\n\u2022 Kopjimi, kllonimi ose duplimi i plote ose i pjesshem i platformes ose komponenteve te saj\n\u2022 Krijimi i platformave qe imitojne funksionalitetin, rrjedhjet e punes ose arkitekturen\n\u2022 Nxjerrja e kodit burimor, skjemave te bazes se te dhenave ose logjikes se biznesit\n\n(2) INXHINIERI MBRAPSHT\n\u2022 Dekompilimi, zberthimi ose inxhinieria mbrapsht e cdo komponenti te platformes\n\u2022 Perjashtim: § 69e UrhG lejon dekompilimin vetem per qellime nderveprimi, nen kushte te rrepta\n\n(3) VEPRA DERIVATE\n\u2022 Krijimi i softuereve te reja te bazuara ne logjiken, dizajnin ose arkitekturen e platformes\n\u2022 Adaptimi ose modifikimi i komponenteve te nxjerra per perdorim ne produkte te tjera\n\n(4) NXJERRJA E PAAUTORIZUAR\n\u2022 Scraping i strukturave, shablloneve ose organizimit te platformes\n\u2022 Nxjerrja e automatizuar e skjemave te bazes se te dhenave, konfigurimit te API-ve ose artefakteve te ndertimit\n\n(5) PERDORIM TREGTAR\n\u2022 Rishitja, nen-licencimi ose shperndarja e cdo elementi te nxjerre\n\u2022 Ofrimi i sherbimeve te bazuara ne kodin ose logjiken e nxjerre',
    },
    section5: {
      title: 'Investimi ne zhvillim dhe vleresimi',
      body: 'Platforma MM Logistic perfaqeson nje investim te konsiderueshem zhvillimi te bazuar ne tarifat e tregut gjerman per zhvillimin e softuerit SaaS me stack te plote:\n\n\u2022 TARIFA E TREGUT: Zhvilluesit senior full-stack ne Gjermani fitojne EUR 120–180 ne ore. Arkitektet e specializuar ne SaaS paguhen EUR 150–220 ne ore.\n\u2022 FUSHA E PROJEKTIT: Platforma perfshin menaxhim te flotes, kontabilitet, operacione deposh, HR, njoftime push, perputhshmeri, e-fatura, eksportime DATEV/SAF-T, gjurnim GPS ne kohe reale, planifikim rrugesh, rrjedhje dorezimi, palet account, dhe me shume.\n\u2022 VLERA E ZHVILLIMIT: Bazuar ne volumin e kodit (mbi 200 skedare te komponenteve front-end, mbi 100 migrime te bazes se te dhenave, mbi 50 funksione edge, 4 gjuhe te plota), vlera totale e zhvillimit sipas tarifave te tregut gjerman vlersohet te jete mbi EUR 250,000 (dyqind e pesedhjete mije euro).\n\nKjo vlere formon bazen per llogaritjen e demshperblimit ne rastin e shkeljes.',
    },
    section6: {
      title: 'Pasojat e shkeljes',
      body: 'Cdo shkelje e te drejtave te pronesise intelektuale te pershkruara ne kete njoftim do te ndiqet me rreptesi. Pasojat perfshijne:\n\n(a) NDERPRERJA DHE PUSHIMI\nDo te leshohet menjehere nje shkrese ligjore nderprerje-dhe-pushimi (Abmahnung) me nje klauzole denimore kontraktuale.\n\n(b) DENIMI KONTRAKTOR (Vertragsstrafe)\nDenimi minimal kontraktor eshte EUR 100,000 (njeqind mije euro) per shkelje. Kjo eshte proporcionale me vleren e asetit te mbrojtur (mbi EUR 250,000) dhe eshte e zbatueshme sipas § 339 te Kodit Civil Gjerman (BGB).\n\n(c) PROCEDURA CIVILE\n\u2022 Padia per demshperblim sipas § 97 UrhG (e drejta e autorit) dhe § 10 GeschGehG (sekretet tregtare)\n\u2022 Demshperblimi llogaritet nga: (i) demet aktuale te pesuar, (ii) fitimet e shkelesit, ose (iii) analogjia e licences — cilado qe eshte me e larte\n\u2022 Kerkese per urdher perkohshem (einstweilige Verfuegung) ne gjykaten kompetente rajonale\n\n(d) NDJEKJA PENALE\n\u2022 Shkelja e qellimshme e te drejtave te autorit denohet me burgim deri ne 3 vjet ose gjobe sipas § 106 UrhG\n\u2022 Per shkelje ne shkalle tregtare, denimi rritet deri ne 5 vjet burgim sipas § 108a UrhG\n\u2022 Shkarja e sekreteve tregtare denohet sipas § 23 GeschGehG\n\n(e) MASAT KUFITARE\nNe rastet nderkufitare brenda BE-se, zbatimi sigurohet permes Rregullores (BE) 1215/2012 (Brukseli Ia) per njohjen dhe zbatimin e vendimeve gjyqesore.',
    },
    section7: {
      title: 'Juridiksioni dhe ligji i zbatueshem',
      body: 'LIGJI I ZBATUESHEM\nKjo njoftim mbrojtjeje dhe cdo mosmarreveshje qe rrjedh nga shkelja e te drejtave te pronesise intelektuale rregullohet ekskluzivisht nga ligji gjerman.\n\nJURIDIKSIONI\nGjykata kompetente ekskluzive eshte Landgericht Freiburg im Breisgau (Gjykata Rajonale e Freiburgut), Baden-Wuerttemberg, Gjermani. Per shkelesit jashte Gjermanise brenda BE-se, zbatohet Rregullorja (BE) 1215/2012 (Brukseli Ia).\n\nZBATIMI NDERKOMBETAR\nPer shkelesit jashte BE-se, Mar Group rezervon te drejten te nise procedura ne cdo juridiksion ku ka ndodhur shkelja, ne perputhje me traktatet nderkombetare te zbatueshme (Konventa e Bernes, Marreveshja TRIPS).',
    },
    section8: {
      title: 'Raportimi i shkeljeve',
      body: 'Nese keni dijeni per kopjim, riprodhim ose perdorim te paautorizuar te platformes MM Logistic ose komponenteve te saj, ju lutemi raportoni menjehere:\n\nMar Group (Genton Maliqi)\nPfaedlistrasse 10\n79576 Weil am Rhein, Gjermani\n\nEmail: info@mm-logistic.eu\nTelefon: +49 172 8443861\n\nTe gjitha raportimet trajtohen ne menyre konfidenciale. Ne rezervojme te drejten te nisim veprime ligjore pa njoftim te metejshem ndaj shkelesve.',
    },
    section9: {
      title: 'Ndryshimet ne kete njoftim',
      body: 'Mar Group rezervon te drejten te perditesoje kete njoftim mbrojtjeje te pronesise intelektuale ne cdo kohe. Ndryshimet hyjne ne fuqi menjehere pas publikimit ne platforme. Versioni me i fundit eshte gjithmone i disponueshem ne kete URL.\n\nData e hyrjes ne fuqi: 27 Maj 2026.',
    },
  },

  // ============================================================
  // ENGLISH (EN)
  // ============================================================
  en: {
    shortTitle: 'IP Protection',
    title: 'Intellectual Property Protection',
    subtitle: 'Legal notice regarding the protection of the MM Logistic platform, source code, business logic, and all digital assets.',
    intro: 'The MM Logistic platform — including its source code, software architecture, database structure, API integrations, user interface design, business logic, and all accompanying components — is an original work created exclusively by Mar Group (Genton Maliqi, EI). No part of this platform has been copied from or derived from any third party. This work is protected under German and European copyright law, trade secret law, and unfair competition law. Any unauthorized copying, reproduction, or use will be pursued with all available legal remedies.',
    lastUpdated: '27 May 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Declaration of originality',
      body: 'The MM Logistic platform has been entirely designed, developed, and built by Mar Group (Genton Maliqi, Entrepreneur individuel, registered in France, with operating address in Weil am Rhein, Germany).\n\nThis platform includes:\n\n\u2022 Over 50 serverless functions (Edge Functions) for logistics, fleet, accounting, notifications, and third-party integrations\n\u2022 Over 100 database migrations with full multi-tenant isolation\n\u2022 Multi-role architecture (super_admin, company_admin, logistics_admin, depot_worker, driver)\n\u2022 Complete translations in 4 languages (Albanian, English, German, French)\n\u2022 Modules for fleet management, depot operations, pallet repair, sorting, accounting with DATEV/SAF-T, HR, real-time GPS tracking, and more\n\nNo part of the code, logic, design, or architecture has been copied from any third-party source. All work represents independent original creation.',
    },
    section2: {
      title: 'Legal basis for protection',
      body: 'The MM Logistic platform is protected under multiple legal frameworks:\n\n(a) GERMAN COPYRIGHT ACT (UrhG)\nComputer programs are protected as literary works under Section 2(1) No. 1 and Sections 69a–69g UrhG. This protection extends to source code, compiled code, preparatory design material, and documentation.\n\n(b) EU DIRECTIVE 2009/24/EC\nProvides harmonised protection for computer programs across the European Union, including protection against unauthorized reproduction, adaptation, and distribution.\n\n(c) EU DIRECTIVE 2001/29/EC (InfoSoc)\nHarmonises certain aspects of copyright and related rights in the information society.\n\n(d) GERMAN TRADE SECRET ACT (GeschGehG)\nThe platform\'s business logic, algorithms, database schemas, and process know-how constitute trade secrets protected under the GeschGehG, which implements EU Directive (EU) 2016/943.\n\n(e) GERMAN ACT AGAINST UNFAIR COMPETITION (UWG)\nSection 4 No. 3 UWG prohibits parasitic copying of commercial achievements. Copying the platform\'s features, workflows, or architecture may constitute unfair competition even where the copy is not identical.',
    },
    section3: {
      title: 'Scope of protection',
      body: 'The following assets are fully protected under the laws cited above:\n\n\u2022 SOURCE CODE — All TypeScript, React, SQL, and Deno files comprising the front-end application and back-end functions\n\u2022 DATABASE ARCHITECTURE — Schemas, migrations, row-level security (RLS) policies, and tenant isolation logic\n\u2022 BUSINESS LOGIC — Algorithms for stock management, delivery workflows, compliance engines, accounting calculations, route optimisation\n\u2022 USER INTERFACE DESIGN — Layouts, components, visual design systems, animations, and interactions\n\u2022 API DESIGN — Endpoint structures, request/response formats, authentication mechanisms\n\u2022 DOCUMENTATION — Technical documentation, user guides, migration notes, and internal process materials\n\u2022 TRANSLATIONS — Localised content across all four supported languages\n\u2022 VISUAL ASSETS — Logos, icons, images, and branding elements',
    },
    section4: {
      title: 'Prohibited actions',
      body: 'The following actions are strictly prohibited without prior written authorisation from Mar Group:\n\n(1) COPYING AND REPRODUCTION\n\u2022 Full or partial copying, cloning, or duplication of the platform or its components\n\u2022 Creating platforms that imitate the functionality, workflows, or architecture\n\u2022 Extracting source code, database schemas, or business logic\n\n(2) REVERSE ENGINEERING\n\u2022 Decompiling, disassembling, or reverse-engineering any platform component\n\u2022 Exception: Section 69e UrhG permits decompilation solely for interoperability purposes, under strict conditions\n\n(3) DERIVATIVE WORKS\n\u2022 Creating new software based on the platform\'s logic, design, or architecture\n\u2022 Adapting or modifying extracted components for use in other products\n\n(4) UNAUTHORIZED EXTRACTION\n\u2022 Scraping of platform structures, templates, or organisation\n\u2022 Automated extraction of database schemas, API configurations, or build artefacts\n\n(5) COMMERCIAL USE\n\u2022 Reselling, sublicensing, or distributing any extracted element\n\u2022 Offering services based on extracted code or logic',
    },
    section5: {
      title: 'Development investment and valuation',
      body: 'The MM Logistic platform represents a substantial development investment based on German market rates for full-stack SaaS development:\n\n\u2022 MARKET RATE: Senior full-stack developers in Germany command EUR 120\u2013180 per hour. Specialised SaaS architects are billed at EUR 150\u2013220 per hour.\n\u2022 PROJECT SCOPE: The platform encompasses fleet management, accounting, depot operations, HR, push notifications, compliance, e-invoicing, DATEV/SAF-T exports, real-time GPS tracking, route planning, delivery workflows, pallet accounts, and more.\n\u2022 DEVELOPMENT VALUE: Based on the code volume (over 200 front-end component files, over 100 database migrations, over 50 edge functions, 4 complete languages), the total development value at German market rates is estimated to exceed EUR 250,000 (two hundred and fifty thousand euros).\n\nThis value forms the basis for damages calculation in the event of infringement.',
    },
    section6: {
      title: 'Consequences of infringement',
      body: 'Any violation of the intellectual property rights described in this notice will be vigorously pursued. Consequences include:\n\n(a) CEASE AND DESIST\nAn immediate cease-and-desist letter (Abmahnung) will be issued containing a contractual penalty clause.\n\n(b) CONTRACTUAL PENALTY (Vertragsstrafe)\nThe minimum contractual penalty is EUR 100,000 (one hundred thousand euros) per infringement. This is proportionate to the value of the protected asset (exceeding EUR 250,000) and is enforceable under Section 339 of the German Civil Code (BGB).\n\n(c) CIVIL PROCEEDINGS\n\u2022 Action for damages under Section 97 UrhG (copyright) and Section 10 GeschGehG (trade secrets)\n\u2022 Damages are calculated by: (i) actual losses suffered, (ii) infringer\'s profits, or (iii) licence analogy \u2014 whichever is highest\n\u2022 Application for a preliminary injunction (einstweilige Verf\u00fcgung) at the competent regional court\n\n(d) CRIMINAL PROSECUTION\n\u2022 Wilful copyright infringement is punishable by up to 3 years\' imprisonment or a fine under Section 106 UrhG\n\u2022 For commercial-scale infringement, the penalty increases to up to 5 years\' imprisonment under Section 108a UrhG\n\u2022 Trade secret misappropriation is punishable under Section 23 GeschGehG\n\n(e) CROSS-BORDER MEASURES\nIn cross-border cases within the EU, enforcement is secured through Regulation (EU) 1215/2012 (Brussels Ia) for the recognition and enforcement of court judgments.',
    },
    section7: {
      title: 'Jurisdiction and applicable law',
      body: 'APPLICABLE LAW\nThis protection notice and any disputes arising from intellectual property infringement are governed exclusively by German law.\n\nJURISDICTION\nThe exclusive competent court is the Landgericht Freiburg im Breisgau (Regional Court of Freiburg), Baden-W\u00fcrttemberg, Germany. For infringers outside Germany but within the EU, Regulation (EU) 1215/2012 (Brussels Ia) applies.\n\nINTERNATIONAL ENFORCEMENT\nFor infringers outside the EU, Mar Group reserves the right to initiate proceedings in any jurisdiction where the infringement has occurred, in accordance with applicable international treaties (Berne Convention, TRIPS Agreement).',
    },
    section8: {
      title: 'Reporting infringements',
      body: 'If you become aware of unauthorized copying, reproduction, or use of the MM Logistic platform or any of its components, please report it immediately:\n\nMar Group (Genton Maliqi)\nPf\u00e4dlistra\u00dfe 10\n79576 Weil am Rhein, Germany\n\nEmail: info@mm-logistic.eu\nPhone: +49 172 8443861\n\nAll reports are treated confidentially. We reserve the right to initiate legal action without further notice against infringers.',
    },
    section9: {
      title: 'Amendments to this notice',
      body: 'Mar Group reserves the right to update this intellectual property protection notice at any time. Changes take effect immediately upon publication on the platform. The latest version is always available at this URL.\n\nEffective date: 27 May 2026.',
    },
  },

  // ============================================================
  // GERMAN (DE)
  // ============================================================
  de: {
    shortTitle: 'IP-Schutz',
    title: 'Schutz des geistigen Eigentums',
    subtitle: 'Rechtlicher Hinweis zum Schutz der MM Logistic-Plattform, des Quellcodes, der Gesch\u00e4ftslogik und aller digitalen Verm\u00f6genswerte.',
    intro: 'Die MM Logistic-Plattform \u2014 einschlie\u00dflich ihres Quellcodes, der Softwarearchitektur, der Datenbankstruktur, der API-Integrationen, des User-Interface-Designs, der Gesch\u00e4ftslogik und aller begleitenden Komponenten \u2014 ist ein Originalwerk, das ausschlie\u00dflich von Mar Group (Genton Maliqi, EI) erstellt wurde. Kein Teil dieser Plattform wurde von Dritten kopiert oder abgeleitet. Dieses Werk ist durch deutsches und europ\u00e4isches Urheberrecht, Gesch\u00e4ftsgeheimnisrecht und Lauterkeitsrecht gesch\u00fctzt. Jede unbefugte Vervielf\u00e4ltigung, Reproduktion oder Nutzung wird mit allen verf\u00fcgbaren rechtlichen Mitteln verfolgt.',
    lastUpdated: '27. Mai 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Erkl\u00e4rung der Originalit\u00e4t',
      body: 'Die MM Logistic-Plattform wurde vollst\u00e4ndig von Mar Group (Genton Maliqi, Entrepreneur individuel, registriert in Frankreich, mit Betriebsadresse in Weil am Rhein, Deutschland) entworfen, entwickelt und gebaut.\n\nDiese Plattform umfasst:\n\n\u2022 \u00dcber 50 Serverless-Funktionen (Edge Functions) f\u00fcr Logistik, Flotte, Buchhaltung, Benachrichtigungen und Drittanbieter-Integrationen\n\u2022 \u00dcber 100 Datenbankmigrationen mit vollst\u00e4ndiger Mandantenisolierung\n\u2022 Multi-Rollen-Architektur (super_admin, company_admin, logistics_admin, depot_worker, driver)\n\u2022 Vollst\u00e4ndige \u00dcbersetzungen in 4 Sprachen (Albanisch, Englisch, Deutsch, Franz\u00f6sisch)\n\u2022 Module f\u00fcr Flottenmanagement, Lagerbetrieb, Palettenreparatur, Sortierung, Buchhaltung mit DATEV/SAF-T, HR, Echtzeit-GPS-Tracking und mehr\n\nKein Teil des Codes, der Logik, des Designs oder der Architektur wurde aus Drittquellen kopiert. S\u00e4mtliche Arbeit stellt unabh\u00e4ngige Originalsch\u00f6pfung dar.',
    },
    section2: {
      title: 'Rechtsgrundlage des Schutzes',
      body: 'Die MM Logistic-Plattform ist durch mehrere Rechtsrahmen gesch\u00fctzt:\n\n(a) URHEBERRECHTSGESETZ (UrhG)\nComputerprogramme sind als Sprachwerke gem\u00e4\u00df \u00a7 2 Abs. 1 Nr. 1 und \u00a7\u00a7 69a\u201369g UrhG gesch\u00fctzt. Dieser Schutz erstreckt sich auf den Quellcode, kompilierten Code, vorbereitendes Entwurfsmaterial und Dokumentation.\n\n(b) EU-RICHTLINIE 2009/24/EG\nBietet harmonisierten Schutz f\u00fcr Computerprogramme in der gesamten Europ\u00e4ischen Union, einschlie\u00dflich Schutz gegen unbefugte Vervielf\u00e4ltigung, Bearbeitung und Verbreitung.\n\n(c) EU-RICHTLINIE 2001/29/EG (InfoSoc)\nHarmonisiert bestimmte Aspekte des Urheberrechts und verwandter Schutzrechte in der Informationsgesellschaft.\n\n(d) GESCH\u00c4FTSGEHEIMNISGESETZ (GeschGehG)\nDie Gesch\u00e4ftslogik, Algorithmen, Datenbankschemata und Prozess-Know-how der Plattform stellen Gesch\u00e4ftsgeheimnisse dar, die nach dem GeschGehG gesch\u00fctzt sind, welches die EU-Richtlinie (EU) 2016/943 umsetzt.\n\n(e) GESETZ GEGEN DEN UNLAUTEREN WETTBEWERB (UWG)\n\u00a7 4 Nr. 3 UWG verbietet die vermeidbare Herkunftst\u00e4uschung durch Nachahmung. Das Kopieren der Funktionen, Arbeitsabl\u00e4ufe oder Architektur der Plattform kann unlauteren Wettbewerb darstellen, auch wenn die Kopie nicht identisch ist.',
    },
    section3: {
      title: 'Schutzumfang',
      body: 'Die folgenden Verm\u00f6genswerte sind nach den oben genannten Gesetzen vollst\u00e4ndig gesch\u00fctzt:\n\n\u2022 QUELLCODE \u2014 Alle TypeScript-, React-, SQL- und Deno-Dateien, die die Frontend-Anwendung und Backend-Funktionen bilden\n\u2022 DATENBANKARCHITEKTUR \u2014 Schemata, Migrationen, Row-Level-Security-Richtlinien (RLS) und Mandantenisolierungslogik\n\u2022 GESCH\u00c4FTSLOGIK \u2014 Algorithmen f\u00fcr Bestandsmanagement, Lieferabl\u00e4ufe, Compliance-Engines, Buchhaltungsberechnungen, Routenoptimierung\n\u2022 USER-INTERFACE-DESIGN \u2014 Layouts, Komponenten, visuelle Designsysteme, Animationen und Interaktionen\n\u2022 API-DESIGN \u2014 Endpunktstrukturen, Anfrage-/Antwortformate, Authentifizierungsmechanismen\n\u2022 DOKUMENTATION \u2014 Technische Dokumentation, Benutzerhandb\u00fccher, Migrationsnotizen und interne Prozessmaterialien\n\u2022 \u00dcBERSETZUNGEN \u2014 Lokalisierte Inhalte in allen vier unterst\u00fctzten Sprachen\n\u2022 VISUELLE ASSETS \u2014 Logos, Icons, Bilder und Branding-Elemente',
    },
    section4: {
      title: 'Verbotene Handlungen',
      body: 'Die folgenden Handlungen sind ohne vorherige schriftliche Genehmigung von Mar Group strengstens untersagt:\n\n(1) KOPIEREN UND VERVIELF\u00c4LTIGEN\n\u2022 Vollst\u00e4ndiges oder teilweises Kopieren, Klonen oder Duplizieren der Plattform oder ihrer Komponenten\n\u2022 Erstellen von Plattformen, die Funktionalit\u00e4t, Arbeitsabl\u00e4ufe oder Architektur imitieren\n\u2022 Extrahieren von Quellcode, Datenbankschemata oder Gesch\u00e4ftslogik\n\n(2) REVERSE ENGINEERING\n\u2022 Dekompilieren, Disassemblieren oder Reverse-Engineering von Plattformkomponenten\n\u2022 Ausnahme: \u00a7 69e UrhG erlaubt Dekompilierung ausschlie\u00dflich zu Interoperabilit\u00e4tszwecken unter strengen Bedingungen\n\n(3) ABGELEITETE WERKE\n\u2022 Erstellen neuer Software basierend auf der Logik, dem Design oder der Architektur der Plattform\n\u2022 Anpassen oder Modifizieren extrahierter Komponenten zur Verwendung in anderen Produkten\n\n(4) UNBEFUGTE EXTRAKTION\n\u2022 Scraping von Plattformstrukturen, Vorlagen oder Organisation\n\u2022 Automatisierte Extraktion von Datenbankschemata, API-Konfigurationen oder Build-Artefakten\n\n(5) KOMMERZIELLE NUTZUNG\n\u2022 Weiterverkauf, Unterlizenzierung oder Verbreitung extrahierter Elemente\n\u2022 Anbieten von Dienstleistungen basierend auf extrahiertem Code oder extrahierter Logik',
    },
    section5: {
      title: 'Entwicklungsinvestition und Bewertung',
      body: 'Die MM Logistic-Plattform repr\u00e4sentiert eine erhebliche Entwicklungsinvestition basierend auf deutschen Markts\u00e4tzen f\u00fcr Full-Stack-SaaS-Entwicklung:\n\n\u2022 MARKTSATZ: Senior Full-Stack-Entwickler in Deutschland verlangen EUR 120\u2013180 pro Stunde. Spezialisierte SaaS-Architekten werden mit EUR 150\u2013220 pro Stunde abgerechnet.\n\u2022 PROJEKTUMFANG: Die Plattform umfasst Flottenmanagement, Buchhaltung, Lagerbetrieb, HR, Push-Benachrichtigungen, Compliance, E-Rechnungen, DATEV/SAF-T-Exporte, Echtzeit-GPS-Tracking, Routenplanung, Lieferabl\u00e4ufe, Palettenkonten und mehr.\n\u2022 ENTWICKLUNGSWERT: Basierend auf dem Codevolumen (\u00fcber 200 Frontend-Komponentendateien, \u00fcber 100 Datenbankmigrationen, \u00fcber 50 Edge-Funktionen, 4 vollst\u00e4ndige Sprachen) wird der Gesamtentwicklungswert zu deutschen Markts\u00e4tzen auf \u00fcber EUR 250.000 (zweihundertf\u00fcnfzigtausend Euro) gesch\u00e4tzt.\n\nDieser Wert bildet die Grundlage f\u00fcr die Schadensberechnung im Falle einer Rechtsverletzung.',
    },
    section6: {
      title: 'Folgen einer Rechtsverletzung',
      body: 'Jeder Versto\u00df gegen die in diesem Hinweis beschriebenen Rechte des geistigen Eigentums wird konsequent verfolgt. Die Folgen umfassen:\n\n(a) UNTERLASSUNG\nEs wird unverz\u00fcglich eine Abmahnung mit Vertragsstrafenklausel ausgesprochen.\n\n(b) VERTRAGSSTRAFE\nDie Mindestvertragsstrafe betr\u00e4gt EUR 100.000 (einhunderttausend Euro) pro Versto\u00df. Dies ist verh\u00e4ltnism\u00e4\u00dfig zum Wert des gesch\u00fctzten Gutes (\u00fcber EUR 250.000) und gem\u00e4\u00df \u00a7 339 BGB durchsetzbar.\n\n(c) ZIVILRECHTLICHE VERFAHREN\n\u2022 Schadensersatzklage gem\u00e4\u00df \u00a7 97 UrhG (Urheberrecht) und \u00a7 10 GeschGehG (Gesch\u00e4ftsgeheimnisse)\n\u2022 Schadensberechnung nach: (i) tats\u00e4chlich erlittenem Schaden, (ii) Verletzergewinn oder (iii) Lizenzanalogie \u2014 je nachdem, was am h\u00f6chsten ist\n\u2022 Antrag auf einstweilige Verf\u00fcgung beim zust\u00e4ndigen Landgericht\n\n(d) STRAFRECHTLICHE VERFOLGUNG\n\u2022 Vors\u00e4tzliche Urheberrechtsverletzung wird mit Freiheitsstrafe bis zu 3 Jahren oder Geldstrafe gem\u00e4\u00df \u00a7 106 UrhG bestraft\n\u2022 Bei gewerbs- oder bandm\u00e4\u00dfiger Begehung erh\u00f6ht sich die Strafe auf bis zu 5 Jahre gem\u00e4\u00df \u00a7 108a UrhG\n\u2022 Gesch\u00e4ftsgeheimnisverrat ist strafbar nach \u00a7 23 GeschGehG\n\n(e) GRENZ\u00dcBERSCHREITENDE MASSNAHMEN\nIn grenz\u00fcberschreitenden F\u00e4llen innerhalb der EU wird die Durchsetzung durch die Verordnung (EU) 1215/2012 (Br\u00fcssel Ia) zur Anerkennung und Vollstreckung gerichtlicher Entscheidungen gesichert.',
    },
    section7: {
      title: 'Gerichtsstand und anwendbares Recht',
      body: 'ANWENDBARES RECHT\nDieser Schutzhinweis und alle Streitigkeiten aus der Verletzung geistiger Eigentumsrechte unterliegen ausschlie\u00dflich deutschem Recht.\n\nGERICHTSSTAND\nAusschlie\u00dflich zust\u00e4ndiges Gericht ist das Landgericht Freiburg im Breisgau, Baden-W\u00fcrttemberg, Deutschland. F\u00fcr Verletzer au\u00dferhalb Deutschlands, aber innerhalb der EU, gilt die Verordnung (EU) 1215/2012 (Br\u00fcssel Ia).\n\nINTERNATIONALE DURCHSETZUNG\nF\u00fcr Verletzer au\u00dferhalb der EU beh\u00e4lt sich Mar Group das Recht vor, Verfahren in jeder Gerichtsbarkeit einzuleiten, in der die Verletzung stattgefunden hat, in \u00dcbereinstimmung mit anwendbaren internationalen Vertr\u00e4gen (Berner \u00dcbereinkunft, TRIPS-\u00dcbereinkommen).',
    },
    section8: {
      title: 'Meldung von Rechtsverletzungen',
      body: 'Wenn Sie Kenntnis von unbefugtem Kopieren, Reproduzieren oder Nutzen der MM Logistic-Plattform oder ihrer Komponenten erlangen, melden Sie dies bitte umgehend:\n\nMar Group (Genton Maliqi)\nPf\u00e4dlistra\u00dfe 10\n79576 Weil am Rhein, Deutschland\n\nE-Mail: info@mm-logistic.eu\nTelefon: +49 172 8443861\n\nAlle Meldungen werden vertraulich behandelt. Wir behalten uns vor, ohne weitere Ank\u00fcndigung rechtliche Schritte gegen Verletzer einzuleiten.',
    },
    section9: {
      title: '\u00c4nderungen dieses Hinweises',
      body: 'Mar Group beh\u00e4lt sich das Recht vor, diesen Hinweis zum Schutz geistigen Eigentums jederzeit zu aktualisieren. \u00c4nderungen treten unmittelbar nach Ver\u00f6ffentlichung auf der Plattform in Kraft. Die jeweils aktuelle Version ist stets unter dieser URL verf\u00fcgbar.\n\nDatum des Inkrafttretens: 27. Mai 2026.',
    },
  },

  // ============================================================
  // FRENCH (FR)
  // ============================================================
  fr: {
    shortTitle: 'Protection PI',
    title: 'Protection de la Propri\u00e9t\u00e9 Intellectuelle',
    subtitle: 'Avis juridique concernant la protection de la plateforme MM Logistic, du code source, de la logique m\u00e9tier et de tous les actifs num\u00e9riques.',
    intro: 'La plateforme MM Logistic \u2014 y compris son code source, son architecture logicielle, sa structure de base de donn\u00e9es, ses int\u00e9grations API, sa conception d\'interface utilisateur, sa logique m\u00e9tier et tous ses composants associ\u00e9s \u2014 est une \u0153uvre originale cr\u00e9\u00e9e exclusivement par Mar Group (Genton Maliqi, EI). Aucune partie de cette plateforme n\'a \u00e9t\u00e9 copi\u00e9e ou d\u00e9riv\u00e9e d\'un tiers. Cette \u0153uvre est prot\u00e9g\u00e9e par le droit d\'auteur allemand et europ\u00e9en, le droit des secrets d\'affaires et le droit de la concurrence d\u00e9loyale. Toute copie, reproduction ou utilisation non autoris\u00e9e sera poursuivie par tous les moyens juridiques disponibles.',
    lastUpdated: '27 mai 2026',
    version: 'Version 1.0',

    section1: {
      title: 'D\u00e9claration d\'originalit\u00e9',
      body: 'La plateforme MM Logistic a \u00e9t\u00e9 enti\u00e8rement con\u00e7ue, d\u00e9velopp\u00e9e et construite par Mar Group (Genton Maliqi, Entrepreneur individuel, immatricul\u00e9 en France, avec adresse d\'exploitation \u00e0 Weil am Rhein, Allemagne).\n\nCette plateforme comprend :\n\n\u2022 Plus de 50 fonctions serverless (Edge Functions) pour la logistique, la flotte, la comptabilit\u00e9, les notifications et les int\u00e9grations tierces\n\u2022 Plus de 100 migrations de base de donn\u00e9es avec isolation compl\u00e8te multi-locataires\n\u2022 Architecture multi-r\u00f4les (super_admin, company_admin, logistics_admin, depot_worker, driver)\n\u2022 Traductions compl\u00e8tes en 4 langues (albanais, anglais, allemand, fran\u00e7ais)\n\u2022 Modules de gestion de flotte, op\u00e9rations d\'entrep\u00f4t, r\u00e9paration de palettes, tri, comptabilit\u00e9 avec DATEV/SAF-T, RH, suivi GPS en temps r\u00e9el, et plus\n\nAucune partie du code, de la logique, du design ou de l\'architecture n\'a \u00e9t\u00e9 copi\u00e9e d\'une source tierce. L\'ensemble du travail repr\u00e9sente une cr\u00e9ation originale ind\u00e9pendante.',
    },
    section2: {
      title: 'Base juridique de la protection',
      body: 'La plateforme MM Logistic est prot\u00e9g\u00e9e par plusieurs cadres juridiques :\n\n(a) LOI ALLEMANDE SUR LE DROIT D\'AUTEUR (UrhG)\nLes programmes informatiques sont prot\u00e9g\u00e9s en tant qu\'\u0153uvres litt\u00e9raires en vertu de l\'article 2(1) n\u00b0 1 et des articles 69a\u201369g UrhG. Cette protection s\'\u00e9tend au code source, au code compil\u00e9, au mat\u00e9riel de conception pr\u00e9paratoire et \u00e0 la documentation.\n\n(b) DIRECTIVE UE 2009/24/CE\nFournit une protection harmonis\u00e9e des programmes informatiques dans l\'ensemble de l\'Union europ\u00e9enne, y compris la protection contre la reproduction, l\'adaptation et la distribution non autoris\u00e9es.\n\n(c) DIRECTIVE UE 2001/29/CE (InfoSoc)\nHarmonise certains aspects du droit d\'auteur et des droits voisins dans la soci\u00e9t\u00e9 de l\'information.\n\n(d) LOI ALLEMANDE SUR LES SECRETS D\'AFFAIRES (GeschGehG)\nLa logique m\u00e9tier, les algorithmes, les sch\u00e9mas de base de donn\u00e9es et le savoir-faire de la plateforme constituent des secrets d\'affaires prot\u00e9g\u00e9s par le GeschGehG, qui transpose la Directive (UE) 2016/943.\n\n(e) LOI ALLEMANDE CONTRE LA CONCURRENCE D\u00c9LOYALE (UWG)\nL\'article 4 n\u00b0 3 UWG interdit la copie parasitaire de r\u00e9alisations commerciales. Copier les fonctionnalit\u00e9s, les flux de travail ou l\'architecture de la plateforme peut constituer une concurrence d\u00e9loyale m\u00eame lorsque la copie n\'est pas identique.',
    },
    section3: {
      title: 'Port\u00e9e de la protection',
      body: 'Les actifs suivants sont enti\u00e8rement prot\u00e9g\u00e9s en vertu des lois cit\u00e9es ci-dessus :\n\n\u2022 CODE SOURCE \u2014 Tous les fichiers TypeScript, React, SQL et Deno composant l\'application front-end et les fonctions back-end\n\u2022 ARCHITECTURE DE BASE DE DONN\u00c9ES \u2014 Sch\u00e9mas, migrations, politiques de s\u00e9curit\u00e9 au niveau des lignes (RLS) et logique d\'isolation des locataires\n\u2022 LOGIQUE M\u00c9TIER \u2014 Algorithmes de gestion des stocks, flux de livraison, moteurs de conformit\u00e9, calculs comptables, optimisation d\'itin\u00e9raires\n\u2022 CONCEPTION DE L\'INTERFACE UTILISATEUR \u2014 Mises en page, composants, syst\u00e8mes de design visuel, animations et interactions\n\u2022 CONCEPTION D\'API \u2014 Structures de points de terminaison, formats de requ\u00eate/r\u00e9ponse, m\u00e9canismes d\'authentification\n\u2022 DOCUMENTATION \u2014 Documentation technique, guides utilisateur, notes de migration et mat\u00e9riaux de processus internes\n\u2022 TRADUCTIONS \u2014 Contenu localis\u00e9 dans les quatre langues prises en charge\n\u2022 ACTIFS VISUELS \u2014 Logos, ic\u00f4nes, images et \u00e9l\u00e9ments de marque',
    },
    section4: {
      title: 'Actions interdites',
      body: 'Les actions suivantes sont strictement interdites sans autorisation \u00e9crite pr\u00e9alable de Mar Group :\n\n(1) COPIE ET REPRODUCTION\n\u2022 Copie, clonage ou duplication totale ou partielle de la plateforme ou de ses composants\n\u2022 Cr\u00e9ation de plateformes imitant la fonctionnalit\u00e9, les flux de travail ou l\'architecture\n\u2022 Extraction du code source, des sch\u00e9mas de base de donn\u00e9es ou de la logique m\u00e9tier\n\n(2) R\u00c9TRO-ING\u00c9NIERIE\n\u2022 D\u00e9compilation, d\u00e9sassemblage ou r\u00e9tro-ing\u00e9nierie de tout composant de la plateforme\n\u2022 Exception : l\'article 69e UrhG autorise la d\u00e9compilation uniquement \u00e0 des fins d\'interop\u00e9rabilit\u00e9, sous des conditions strictes\n\n(3) \u0152UVRES D\u00c9RIV\u00c9ES\n\u2022 Cr\u00e9ation de nouveaux logiciels bas\u00e9s sur la logique, le design ou l\'architecture de la plateforme\n\u2022 Adaptation ou modification de composants extraits pour utilisation dans d\'autres produits\n\n(4) EXTRACTION NON AUTORIS\u00c9E\n\u2022 Scraping des structures, mod\u00e8les ou organisation de la plateforme\n\u2022 Extraction automatis\u00e9e de sch\u00e9mas de base de donn\u00e9es, configurations API ou artefacts de compilation\n\n(5) UTILISATION COMMERCIALE\n\u2022 Revente, sous-licence ou distribution de tout \u00e9l\u00e9ment extrait\n\u2022 Offre de services bas\u00e9s sur le code ou la logique extraits',
    },
    section5: {
      title: 'Investissement de d\u00e9veloppement et valorisation',
      body: 'La plateforme MM Logistic repr\u00e9sente un investissement de d\u00e9veloppement substantiel bas\u00e9 sur les tarifs du march\u00e9 allemand pour le d\u00e9veloppement SaaS full-stack :\n\n\u2022 TARIF DU MARCH\u00c9 : Les d\u00e9veloppeurs full-stack seniors en Allemagne facturent EUR 120\u2013180 de l\'heure. Les architectes SaaS sp\u00e9cialis\u00e9s sont factur\u00e9s EUR 150\u2013220 de l\'heure.\n\u2022 P\u00c9RIM\u00c8TRE DU PROJET : La plateforme couvre la gestion de flotte, la comptabilit\u00e9, les op\u00e9rations d\'entrep\u00f4t, les RH, les notifications push, la conformit\u00e9, la facturation \u00e9lectronique, les exports DATEV/SAF-T, le suivi GPS en temps r\u00e9el, la planification d\'itin\u00e9raires, les flux de livraison, les comptes palettes, et plus.\n\u2022 VALEUR DE D\u00c9VELOPPEMENT : Bas\u00e9 sur le volume de code (plus de 200 fichiers de composants front-end, plus de 100 migrations de base de donn\u00e9es, plus de 50 fonctions edge, 4 langues compl\u00e8tes), la valeur totale de d\u00e9veloppement aux tarifs du march\u00e9 allemand est estim\u00e9e \u00e0 plus de EUR 250 000 (deux cent cinquante mille euros).\n\nCette valeur constitue la base du calcul des dommages en cas de violation.',
    },
    section6: {
      title: 'Cons\u00e9quences d\'une violation',
      body: 'Toute violation des droits de propri\u00e9t\u00e9 intellectuelle d\u00e9crits dans cet avis sera vigoureusement poursuivie. Les cons\u00e9quences comprennent :\n\n(a) MISE EN DEMEURE\nUne mise en demeure imm\u00e9diate (Abmahnung) sera \u00e9mise contenant une clause de p\u00e9nalit\u00e9 contractuelle.\n\n(b) P\u00c9NALIT\u00c9 CONTRACTUELLE (Vertragsstrafe)\nLa p\u00e9nalit\u00e9 contractuelle minimale est de EUR 100 000 (cent mille euros) par violation. Ceci est proportionn\u00e9 \u00e0 la valeur de l\'actif prot\u00e9g\u00e9 (d\u00e9passant EUR 250 000) et est ex\u00e9cutoire en vertu de l\'article 339 du Code civil allemand (BGB).\n\n(c) PROC\u00c9DURE CIVILE\n\u2022 Action en dommages-int\u00e9r\u00eats en vertu de l\'article 97 UrhG (droit d\'auteur) et de l\'article 10 GeschGehG (secrets d\'affaires)\n\u2022 Les dommages sont calcul\u00e9s selon : (i) les pertes r\u00e9elles subies, (ii) les b\u00e9n\u00e9fices du contrevenant, ou (iii) l\'analogie de licence \u2014 selon le montant le plus \u00e9lev\u00e9\n\u2022 Demande de mesure provisoire (einstweilige Verf\u00fcgung) aupr\u00e8s du tribunal r\u00e9gional comp\u00e9tent\n\n(d) POURSUITES P\u00c9NALES\n\u2022 La violation intentionnelle du droit d\'auteur est passible d\'une peine d\'emprisonnement allant jusqu\'\u00e0 3 ans ou d\'une amende en vertu de l\'article 106 UrhG\n\u2022 Pour les violations \u00e0 \u00e9chelle commerciale, la peine est port\u00e9e \u00e0 5 ans d\'emprisonnement en vertu de l\'article 108a UrhG\n\u2022 Le d\u00e9tournement de secrets d\'affaires est punissable en vertu de l\'article 23 GeschGehG\n\n(e) MESURES TRANSFRONTALI\u00c8RES\nDans les cas transfrontaliers au sein de l\'UE, l\'ex\u00e9cution est assur\u00e9e par le R\u00e8glement (UE) 1215/2012 (Bruxelles Ia) pour la reconnaissance et l\'ex\u00e9cution des d\u00e9cisions judiciaires.',
    },
    section7: {
      title: 'Juridiction et droit applicable',
      body: 'DROIT APPLICABLE\nCet avis de protection et tout litige d\u00e9coulant de la violation de droits de propri\u00e9t\u00e9 intellectuelle sont r\u00e9gis exclusivement par le droit allemand.\n\nJURIDICTION\nLe tribunal exclusivement comp\u00e9tent est le Landgericht Freiburg im Breisgau (Tribunal r\u00e9gional de Fribourg), Bade-Wurtemberg, Allemagne. Pour les contrevenants hors d\'Allemagne mais au sein de l\'UE, le R\u00e8glement (UE) 1215/2012 (Bruxelles Ia) s\'applique.\n\nEX\u00c9CUTION INTERNATIONALE\nPour les contrevenants hors de l\'UE, Mar Group se r\u00e9serve le droit d\'engager des proc\u00e9dures dans toute juridiction o\u00f9 la violation a eu lieu, conform\u00e9ment aux trait\u00e9s internationaux applicables (Convention de Berne, Accord sur les ADPIC).',
    },
    section8: {
      title: 'Signalement des violations',
      body: 'Si vous avez connaissance d\'une copie, reproduction ou utilisation non autoris\u00e9e de la plateforme MM Logistic ou de l\'un de ses composants, veuillez le signaler imm\u00e9diatement :\n\nMar Group (Genton Maliqi)\nPf\u00e4dlistra\u00dfe 10\n79576 Weil am Rhein, Allemagne\n\nEmail : info@mm-logistic.eu\nT\u00e9l\u00e9phone : +49 172 8443861\n\nTous les signalements sont trait\u00e9s de mani\u00e8re confidentielle. Nous nous r\u00e9servons le droit d\'engager des poursuites judiciaires sans autre pr\u00e9avis contre les contrevenants.',
    },
    section9: {
      title: 'Modifications de cet avis',
      body: 'Mar Group se r\u00e9serve le droit de mettre \u00e0 jour cet avis de protection de la propri\u00e9t\u00e9 intellectuelle \u00e0 tout moment. Les modifications prennent effet imm\u00e9diatement apr\u00e8s publication sur la plateforme. La version la plus r\u00e9cente est toujours disponible \u00e0 cette URL.\n\nDate d\'entr\u00e9e en vigueur : 27 mai 2026.',
    },
  },
};
