/**
 * Refund Policy + Widerrufsbelehrung (Right of Withdrawal)
 *
 * For B2B SaaS, refunds are governed by contract (the AGB).
 * For B2C scenarios (consumers), German law requires a Widerrufsbelehrung
 * (statutory withdrawal notice) under §§ 312g, 355-356 BGB - 14 day cooling-off period.
 *
 * Even pure B2B SaaS often offers some refund policy for goodwill
 * (e.g. pro-rata refunds, trial extensions) to build trust.
 *
 * Legal basis:
 * - B2B: BGB §§ 305-310 (Standard Terms), HGB
 * - B2C: BGB §§ 312g, 355-356 (Withdrawal Right)
 * - EU Directive 2011/83/EU (Consumer Rights)
 */

export const refund = {
  // ============================================================
  // ALBANIAN (SQ)
  // ============================================================
  sq: {
    shortTitle: 'Rimbursimi',
    title: 'Politika e Rimbursimit dhe e Drejta e Terheqjes',
    subtitle: 'Politika jone e rimbursimit dhe e drejta juaj statutore e terheqjes (Widerrufsbelehrung) sipas ligjit gjerman.',
    intro: 'Kjo politike pershkruan kushtet ne te cilat ofroni rimbursime dhe te drejten tuaj statutore te terheqjes sipas ligjit gjerman. Per klientet biznesi (B2B), zbatohen vetëm politikat e brendshme te rimbursimit. Per konsumatoret (B2C - persona privat qe perdorin sherbimin per qellime jashte aktivitetit te tyre profesional), zbatohet edhe e drejta statutore e terheqjes sipas \u00a7\u00a7 312g, 355 BGB.',
    lastUpdated: '15 Maj 2026',
    version: 'Versioni 1.0',

    section1: {
      title: 'Konsumatoret kunder klienteve biznesi',
      body: 'PER TE PERCAKTUAR TE DREJTAT TUAJA TE RIMBURSIMIT, FILLIMISHT KUPTONI STATUSIN TUAJ LIGJOR:\n\nKLIENT BIZNESI (B2B - \u00a7 14 BGB):\nNese perdorni sherbimin per qellime te aktivitetit profesional/biznesor:\n\u2022 Nuk keni te drejten statutore te terheqjes\n\u2022 Zbatohen vetem politikat e meposhtme te rimbursimit\n\u2022 Sherbimi destinohet kryesisht per ju\n\nKONSUMATOR (B2C - \u00a7 13 BGB):\nNese perdorni sherbimin si person privat per qellime jashte aktivitetit profesional:\n\u2022 Keni te drejten statutore te terheqjes 14 dite (Widerrufsrecht)\n\u2022 Zbatohen kushte shtese te mbrojtjes\n\u2022 Shih seksionin "Widerrufsbelehrung" me poshte\n\nNe shumicen e rasteve, perdoruesit e platformes [EMRI I PLATFORMES] jane klient biznesi, sepse platforma eshte e dedikuar per logjistike profesionale. Megjithate, do te respektohet statusi i individit nese kerkohet.',
    },
    section2: {
      title: 'Politika kryesore e rimbursimit',
      body: 'PROVA FALAS:\nOfrojme 14 dite prove falas per perdorues te rinj. Gjate kesaj periudhe:\n\u2022 Mund ta perfundoni ne cdo kohe pa kosto\n\u2022 Nuk ka faturim automatik gjate periudhes\n\u2022 Pas periudhes, kalim ne planin e zgjedhur (kerkohet konfirmim)\n\nMUAJI I PARE - GARANCION I KENAQESISE:\nNese ne 30 ditet e para te abonimit te paguar nuk jeni te kenaqur me sherbimin, ofrojme:\n\u2022 Rimbursim te plote 100% pa pyetje\n\u2022 Aktivizim deri ne nje kerkesa permes e-mail brenda 30 ditesh\n\u2022 Procesim brenda 14 ditesh nga aprovimi\n\nKUSHTE PER GARANCION:\n\u2022 Vlen vetem per blerjen e pare te planit\n\u2022 Nuk vlen per upgrade ose downgrade\n\u2022 Nuk vlen per perdorues qe kane perdorur me shume se 50% te kuotes\n\u2022 Eshte nje here per klient\n\nABONIMET MUJORE (PAS MUAJIT TE PARE):\n\u2022 Anulim me efekt ne fund te periudhes aktuale\n\u2022 Akses i plote deri ne fund te ciklit te paguar\n\u2022 Pa rimbursim pro-rata per periudhen e mbetur\n\nABONIMET VJETORE:\n\u2022 Anulim me efekt ne fund te vitit kontraktor\n\u2022 Rimbursim pro-rata vetem ne raste te vecanta (shih seksionin "Rrethana te vecanta")',
    },
    section3: {
      title: 'WIDERRUFSBELEHRUNG (E drejta statutore e terheqjes - B2C)',
      body: 'KETO TE DREJTA APLIKOHEN VETEM PER KONSUMATORET (\u00a7 13 BGB).\n\nE DREJTA E TERHEQJES:\nKeni te drejten te terhiqeni nga kjo kontrate brenda 14 diteve pa dhene asnje arsye.\n\nAFATI I TERHEQJES:\nAfati i terheqjes \u00ebshte 14 dite nga dita e lidhjes se kontrates.\n\nUSHTRIMI I TE DREJTES SE TERHEQJES:\nPer te ushtruar te drejten tuaj te terheqjes, duhet te na informoni:\n\n[EMRI I KOMPANISE]\n[Adresa e plote]\nE-mail: [widerruf@kompani.de]\nTelefon: [+49 XXX XXXXXXX]\n\nMe nje deklarate te qarte (p.sh. nje leter te derguar nepermjet postes ose e-mailit) per vendimin tuaj per te terhequr nga kjo kontrate.\n\nMund te perdorni formularin shembull te terheqjes te bashkengjitur ne fund te kesaj politike, por nuk eshte e detyrueshme.\n\nPER TE RESPEKTUAR AFATIN E TERHEQJES, eshte e mjaftueshme qe te dergoni komunikimin per ushtrimin e te drejtes se terheqjes para skadimit te periudhes se terheqjes.\n\nPASOJAT E TERHEQJES:\nNese terhiqeni nga kjo kontrate, do te ju rimbursojme te gjitha pagesat qe kemi marre nga ju, perfshire kostot e transportit (me perjashtim te kostove shtese qe rrjedhin nga zgjedhja juaj per nje mode tjeter dorezimi nga moda standarte me e leverdishme), pa vonese te panevojshme dhe ne cdo rast jo me vone se 14 dite nga dita ne te cilen kemi marre njoftim per terheqjen tuaj nga kjo kontrate.\n\nPer rimbursim, do te perdorim te njejten mode pagese qe keni perdorur per transaksionin origjinal, pervecese nese keni pajtuar shprehimisht ndryshe; ne asnje rast nuk do te ngarkoheni me tarifa per kete rimbursim.',
    },
    section4: {
      title: 'PERJASHTIM I TE DREJTES SE TERHEQJES PER SHERBIME DIGJITALE',
      body: 'PA HUMBJE TE TE DREJTAVE TUAJA:\n\nSipas \u00a7 356 par. 4 BGB, e drejta e terheqjes mund te humbasi para skadimit te periudhes se terheqjes nese:\n\n1. Sherbimi eshte ekzekutuar plotesisht para skadimit te 14 diteve\n2. Keni dhene pelqim te qarte paraprak\n3. Keni konfirmuar pelqimin per pranimin e ekzekutimit pas humbjes se te drejtes se terheqjes\n\nKJO ZBATOHET NESE:\n\u2022 Aktivizoni nje plan te paguar dhe nisni perdorimin\n\u2022 Bashkangjisni pelqim te qarte gjate aktivizimit\n\u2022 Konfirmoni kuptimin se nuk do te keni me te drejten e terheqjes\n\nNE NJOFTOJME ME PELQIM TE QARTE:\nGjate aktivizimit te planit te paguar, ju shfaqim:\n\u2705 Checkbox: "Pajtohem qe ekzekutimi i sherbimit te filloje menjehere"\n\u2705 Checkbox: "Pranoj qe e drejta ime e terheqjes 14-ditore eshte humbur kur sherbimi eshte ekzekutuar plotesisht"\n\nNESE NUK PAJTOHENI:\n\u2022 Ruajme te drejten tuaj te terheqjes 14-ditore\n\u2022 Sherbimi nuk aktivizohet ende\n\u2022 Pas 14 diteve, sherbimi aktivizohet automatikisht (osa ju anuloni)',
    },
    section5: {
      title: 'Rrethana te vecanta per rimbursim',
      body: 'NE RAST TE KETYRE RRETHANAVE TE VECANTA, OFROJME RIMBURSIM EDHE JASHTE GARANCISE 30-DITORE:\n\n1. PROBLEMET TEKNIKE PER ME SHUME SE 7 DITE NGRADHAZI:\n\u2022 Sherbimi i pamundur per perdorim per shume se 7 dite\n\u2022 Per shkak te problemeve teknike tona (jo te internetit tuaj)\n\u2022 Pas raportimit dhe deshtimit te zgjidhjes\n\nKompensimi: Pro-rata refund per kohen e padisponueshme + 1 muaj falas\n\n2. NDRYSHIME MATERIALE NEGATIVE NE SHERBIM:\nNese hiqim funksione kryesore qe keni perdorur:\n\u2022 Njoftim paraprak 30 dite\n\u2022 E drejta per perfundim pa kosto\n\u2022 Rimbursim pro-rata per periudhen e mbetur\n\n3. NDRYSHIME NE CMIM:\nNese ngrejme cmimin gjate kontrates aktive:\n\u2022 Njoftim paraprak 60 dite\n\u2022 Cmimi i vjeter aplikohet deri ne fund te vitit\n\u2022 Mund te perfundoni pa kosto\n\u2022 Pa rimbursim pro-rata (nuk eshte gabim juaji)\n\n4. PEZULLIMI I LLOGARISE PA SHKELJE:\nNese pezullojme llogarine tuaj gabimisht:\n\u2022 Rimbursim i plote per kohen e pezullimit\n\u2022 Restorim i te gjitha funksioneve\n\u2022 Mundesi shtese si kompensim\n\n5. FALIMENTIMI OSE MBYLLJA E SHERBIMIT:\nNese duhet te mbyllim sherbimin:\n\u2022 Njoftim 90 dite paraprakisht\n\u2022 Eksport i te dhenave i lehtesuar\n\u2022 Rimbursim pro-rata per periudhen e mbetur\n\u2022 Mbeshtetje per migrim te sherbimit',
    },
    section6: {
      title: 'Pa rimbursim ne keto raste',
      body: 'RIMBURSIMI NUK DISPONOHET NE KETO RRETHANA:\n\n1. PASI TE KETE KALUAR PERIUDHA E GARANCISE 30-DITORE\nPer abonime mujore, anulimi ka efekt ne fund te muajit aktual.\nPer abonime vjetore, anulimi ka efekt ne fund te vitit kontraktor.\n\n2. SHKELJE TE AGB OSE AUP\nNese llogaria pezullohet ose perfundohet per shkelje:\n\u2022 Nuk ka rimbursim per periudhen e mbetur\n\u2022 Pagimi i mbetur eshte ende i detyrueshem\n\u2022 Pa-disponueshmeria nuk konsiderohet defekt i sherbimit\n\n3. PERFUNDIM I JASHTEZAKONSHEM NGA NA\nPer shkelje katastrofike (CSAM, terrorizem, mashtrim):\n\u2022 Asnje rimbursim\n\u2022 Akses i menjehershem i bllokuar\n\u2022 Veprime ligjore mund te ndiqen\n\n4. PERDORIM I PLOTE I SHERBIMIT\nNese keni perdorur funksionet kryesore te sherbimit ne menyre te plote:\n\u2022 Ngarkim shumice dergesa\n\u2022 Eksport te shumeta DATEV\n\u2022 Perdorim API mbi 80% te kuotes\nNuk konsiderohet "te pakenaqur" me sherbimin.\n\n5. KAPELE PROBLEMI INTERNET\nNese problemi vjen nga lidhja juaj e internetit, ofruesi juaj, ose pajisja:\n\u2022 Nuk eshte pergjegjesi e jone\n\u2022 Pa rimbursim\n\u2022 Mund te ofrojme keshilla teknike\n\n6. SUPER USAGE TE TARIFAVE\nNese keni tejkaluar kuoten e planit dhe paguar tarifa shtese:\n\u2022 Tarifat shtese jane te pa-rimbursueshme\n\u2022 Ofrojme keshilla per plan me te mire',
    },
    section7: {
      title: 'Si te kerkoni rimbursim',
      body: 'PROCESI I KERKESES PER RIMBURSIM:\n\nHAPI 1: KONTAKT FILLESTAR\nE-mail: [refund@kompani.de]\nObjekti: "Kerkese per rimbursim - [Numri i llogarise]"\n\nINFORMACIONI I NEVOJSHEM:\n\u2022 Emri dhe email i regjistruar\n\u2022 Numri i llogarise / ID e kompanise\n\u2022 Plani aktiv dhe data e aktivizimit\n\u2022 Arsyeja e kerkeses (per garancion 30-ditor mjafton "i pa-kenaqur")\n\u2022 Numri i fatures qe doni te rimburson\n\nHAPI 2: KONFIRMIM I MARRJES\nDo te konfirmojme marrjen brenda 24 oresh.\n\nHAPI 3: VERIFIKIM\nVerifikim brenda 3 ditesh pune:\n\u2022 Konfirmim i statusit te llogarise\n\u2022 Verifikim i kushteve\n\u2022 Nese aplikohet ndonje perjashtim\n\nHAPI 4: APROVIM OSE REFUZIM\nNjoftim me arsye me shkrim brenda 7 ditesh pune.\n\nHAPI 5: EKZEKUTIM\nNese aprovohet:\n\u2022 Procesim brenda 14 diteve\n\u2022 Pagesa permes te njejtes mode si pagesa origjinale\n\u2022 Konfirmim me e-mail kur eshte procesuar\n\u2022 Mund te marre 5-10 dite shtese deri ne llogarinë tuaj\n\nNESE REFUZOHET:\n\u2022 Arsye e qarte me shkrim\n\u2022 Sugjerime alternative (eshte e mundur upgrade/downgrade falas, etj.)\n\u2022 Mundesi apelimi tek [appeals@kompani.de]',
    },
    section8: {
      title: 'Tarifat dhe ngarkesat shtese',
      body: 'TARIFAT QE NUK JANE TE RIMBURSUESHME:\n\n1. KOSTOT E APLIKIMIT (kur aplikohen)\nNese keni aplikuar per nje plan special qe kerkon dokumentacion shtese:\n\u2022 Kostoja e verifikimit eshte e pa-rimbursueshme\n\u2022 Edhe nese aplikimi refuzohet\n\n2. NGARKESAT SHTESE\nPer perdorim mbi planin:\n\u2022 Bandwidth mbi limit\n\u2022 Storage mbi limit\n\u2022 API calls mbi limit\nKeto tarifa janë konsumuese dhe te pa-rimbursueshme.\n\n3. SHERBIMET PROFESIONALE\n\u2022 Trajnime te personalizuara\n\u2022 Konsulence implementimi\n\u2022 Customizim\nKeto ne baze "pre-paid" pa rimbursim pas fillimit te punes.\n\n4. KOSTOT E PALES SE TRETE\nNese plani perfshin sherbime te paleve te treta:\n\u2022 Marketplaces (Shopify, etj.)\n\u2022 Sherbim domain-i\n\u2022 SMS / Push notifications\nKeto i nenshtrohen politikave te ofruesit perkates.\n\nTARIFAT QE RIMBURSOHEN AUTOMATIKISHT:\n\n1. DUBLIKIME TE FATURAVE\nNese faturoheni dy here per gabim tonin:\n\u2022 Rimbursim automatik\n\u2022 Brenda 7 ditesh\n\u2022 Pa nevoje kerkese\n\n2. PEZULLIM ANE GABUAR\nNese pezullimi tregon te jete gabim:\n\u2022 Rimbursim per kohen e pezulluar\n\u2022 Bonus 1 muaj falas\n\u2022 Plus pergjegjesia per dem te mundshem',
    },
    section9: {
      title: 'Anulimi i abonimit (jo rimbursim)',
      body: 'PER TE ANULUAR ABONIMIN TUAJ (PA KERKUAR RIMBURSIM):\n\nABONIM MUJOR:\n1. Settings → Subscription\n2. Klikoni "Anulo abonimin"\n3. Konfirmoni vendimin\n4. Akses i plote deri ne fund te muajit aktual\n5. Pa faturime te ardhshme\n\nABONIM VJETOR:\n1. Settings → Subscription\n2. Klikoni "Anulo abonimin"\n3. Zgjidhni mode anulimi:\n   - Anulim ne fund te vitit (akses i plote deri atehere)\n   - Anulim i menjehershem (pa rimbursim pro-rata)\n4. Konfirmoni vendimin\n\nPAS ANULIMIT:\n\u2022 Pranoni email konfirmimi\n\u2022 30 dite per eksport te te dhenave\n\u2022 90 dite backup ne arkiva te ngrira\n\u2022 Pas 90 ditesh: fshirje permanente\n\nMUND TE RIAKTIVIZONI:\nBrenda 30 diteve nga anulimi:\n\u2022 Akses te plote i te dhenave tuaja\n\u2022 Mund te ndryshoni plan\n\u2022 Mund te aktivizoni nje plan tjeter\n\nPAS 30 DITESH:\nDuhet te krijoni llogari te re. Te dhenat mund te jene te pa-rikuperueshme.',
    },
    section10: {
      title: 'Formulari Shembull i Terheqjes (B2C)',
      body: 'FORMULAR SHEMBULL I TERHEQJES\n(Plotesoni dhe dergoni kete formular vetëm nese deshironi te terhiqeni nga kontrata)\n\nDREJTUAR:\n[EMRI I KOMPANISE]\n[Adresa e plote]\nE-mail: [widerruf@kompani.de]\n\nSHKAK:\nMe kete deklarate, une / ne (*) terhiqem / terhiqemi (*) nga kontrata e lidhur per blerjen e sherbimeve te meposhtme (*):\n\n_______________________________________________\n[Pershkrim i sherbimit / planit te abonimit]\n_______________________________________________\n\nDATA E POROSISE: __________________________\nDATA E PRANIMIT: __________________________\n\nEMRI I KONSUMATORIT/EVE: ___________________\n\nADRESA E KONSUMATORIT/EVE: ________________\n_______________________________________________\n\nNUMRI I LLOGARISE / ID: ____________________\n\nNENSHKRIMI I KONSUMATORIT/EVE: _____________\n(vetëm per komunikim me shkrim ne leter)\n\nDATA: __________________________________\n\n(*) Fshini sipas rastit\n\n--- FUND I FORMULARIT ---\n\nKy formular nuk eshte i detyrueshem - mund te perdorni cdo deklarate te qarte (e-mail, leter, formular online) qe tregon vendimin tuaj per t\'u terhequr.',
    },
    section11: {
      title: 'Pagesat dhe rimbursimet',
      body: 'METODAT E PAGESES TE PRANUARA:\n\u2022 Karte krediti (Visa, Mastercard, American Express)\n\u2022 Karte debiti (Maestro, V-Pay)\n\u2022 SEPA Direct Debit (BE)\n\u2022 PayPal\n\u2022 Bank transfer (vetem per plane enterprise)\n\u2022 Apple Pay / Google Pay (ne disa raste)\n\nMODA E RIMBURSIMIT:\nRimbursimet behen ne te njejten mode si pagesa origjinale:\n\u2022 Karte → Karte (5-10 dite pune deri ne llogari)\n\u2022 SEPA → SEPA (3-5 dite pune)\n\u2022 PayPal → PayPal (24-48 ore)\n\u2022 Bank transfer → Bank transfer (5-7 dite pune)\n\nNDARJA E PAGESES:\nNese paguani me metoda te ndryshme per nje abonim, do te rimburson ne proporcion sipas metodes origjinale.\n\nMONEDHA:\n\u2022 EUR si standard\n\u2022 Mund te ofroni USD ose GBP per kliente nderkombetare\n\u2022 Rimbursimi behet ne te njejten monedhe si pagesa origjinale\n\u2022 Asnje tarife per ndryshime te kursit te kembimit\n\nFATURIM:\n\u2022 Faturat fiskale dergohen elektronikisht (PDF + XRechnung)\n\u2022 Rimbursimi krijon "Gutschrift" (note kredit)\n\u2022 Te gjitha transaksionet regjistrohen ne audit log\n\u2022 Kontabiliteti yne respekton standarde GoBD',
    },
    section12: {
      title: 'Mosmarreveshje dhe arbitrazh',
      body: 'NESE NUK PAJTONI ME VENDIMIN E RIMBURSIMIT:\n\nHAPI 1: APELIM I BRENDSHEM\nE-mail: [appeals@kompani.de]\nMe shpjegim te ri dhe evidenca:\n\u2022 Review nga ekip i pavarur\n\u2022 Pergjigje me shkrim brenda 14 ditesh\n\u2022 Vendim final me arsye\n\nHAPI 2: ZGJIDHJE ALTERNATIVE TE MOSMARREVESHJEVE (ADR)\nPer konsumatoret B2C ne BE:\nKomisioni Evropian ofron nje platforme online:\nhttps://ec.europa.eu/consumers/odr/\n\nNe NUK marrim pjese ne procedura arbitrazhi te detyrueshme me konsumatorin, pervec nese rregullohet ndryshe ligjerisht.\n\nHAPI 3: GJYKATA\nNese deshironi te ndjekni rrugen gjyqesore:\n\u2022 Per klientet biznesi (B2B): juridiksioni [QYTETI I REGJISTRIMIT], Gjermania\n\u2022 Per konsumatoret (B2C): juridiksioni i vendit tuaj te jetes (sipas Rregullores BR\u00fcssel I)\n\u2022 Ligji i zbatueshem: ligji gjerman per kontratat e lidhura ne Gjermani\n\nVERTETIM I TRANSPARENT:\nE-mail-ndertimin dhe komunikimi ruhen me audit log per qellime ligjore. Ne shtetin gjerman, kjo eshte e detyrueshme sipas GoBD.',
    },
    section13: {
      title: 'Pyetjet me te shpeshta',
      body: 'P: A mund te rimburson nese kam paguar per 1 vit por po e perdor vetem 2 muaj?\nP: Vetem nese jeni brenda 30-ditore te aktivizimit ose ka rrethana te vecanta (problem teknik, etj.). Pas kesaj, vetem anulim per fund vit kontraktor.\n\nP: Sa kohe duhet per rimbursimin?\nP: 14 dite per aprovim + 5-10 dite per procesim + 1-3 dite per shfaqje ne llogarine tuaj = ~20-25 dite total.\n\nP: A mund te zevendesoj planin tim?\nP: Po, mund te upgrade-ni ne cdo kohe (diferenca paguhet pro-rata) ose downgrade-ni ne fund te ciklit aktual.\n\nP: A e humb pelqimin te dhenat nese rimburson?\nP: Jo, te dhenat ruhen per 30 dite te shkarkim + 90 dite backup. Mund t\'i rikuperoni nese riaktiviz oni.\n\nP: Cfare ndodh me faturen e shenjuara ne kontabilitet?\nP: Krijohet nje "Gutschrift" (note kredit) qe anulon faturen origjinale. Ju derjojme dokument te dyte fiskal.\n\nP: A mund te kerkoj rimbursim per add-on apo super-usage?\nP: Per add-on (sherbime shtese, modulet premium) jo - jane konsumuese. Per super-usage automatik (overage charges) varion.\n\nP: A mund te trasnsferoj llogarine ne nje person tjeter?\nP: Po, me njoftim me shkrim dhe konfirmim te marresit. Tarifa: €50 (nje here). Kontakto [billing@kompani.de].\n\nP: Cfare ndodh nese kompania ime falimenton?\nP: Mund te keni te drejten te perfundoni dhe te merrni rimbursim pro-rata. Kontakto me dokumentim ligjor te falimentimit.',
    },
    section14: {
      title: 'Ndryshimet ne politiken e rimbursimit',
      body: 'KJO POLITIKE MUND TE PERDITESOHET PER TE REFLEKTUAR:\n\u2022 Ndryshime ligjore (\u00a7\u00a7 312g, 355 BGB, EU Directive 2011/83)\n\u2022 Ndryshime ne praktiken tone te biznesit\n\u2022 Feedback nga klientet\n\u2022 Permiresime te transparences\n\nKOMUNIKIMI I NDRYSHIMEVE:\n\u2022 E-mail tek perdoruesit aktiv 30 dite paraprakisht\n\u2022 Banner ne platforme\n\u2022 Datestamp i perditesuar lart ne dokument\n\nMBROJTJA E TE DREJTAVE EKZISTUESE:\nNdryshimet NUK ndikojne kontratat ekzistuese - vetëm te rejat:\n\u2022 Plani juaj aktual ruan rregullat origjinale deri ne fund\n\u2022 Te drejta te garantuara nuk hiqen retroaktivisht\n\u2022 Permiresimet aplikohen automatikisht\n\nMUND TE PERFUNDONI:\nNese nuk pajtoni me ndryshimet:\n\u2022 30 dite per perfundim pa kosto shtese\n\u2022 Rimbursim pro-rata per ndryshime negative\n\u2022 Eksport i te dhenave i lehtesuar',
    },
    section15: {
      title: 'Kontakti',
      body: 'PYETJE PER RIMBURSIM:\nE-mail: [refund@kompani.de]\nPergjigja brenda 24 oresh.\n\nWIDERRUF (TERHEQJE B2C):\nE-mail: [widerruf@kompani.de]\nPosta: [Adresa e plote], dep. "Widerruf"\n\nFATURIM:\nE-mail: [billing@kompani.de]\nPyetje per fatura, ndryshim metode pagese, etj.\n\nAPELIME:\nE-mail: [appeals@kompani.de]\nAfat: 30 dite nga vendimi origjinal\n\nMBESHTETJE TE PERGJITHSHME:\nE-mail: [support@kompani.de]\nLive chat: brenda platformes (ore pune)\n\nPER PROBLEME LIGJORE:\nE-mail: [legal@kompani.de]\n\nPOSTA OFICIALE:\n[EMRI I KOMPANISE]\n[Adresa e plote]\nGjermania\nTelefon: [+49 XXX XXXXXXX]\n\nORE PUNE:\nE Hena - E Premte: 09:00 - 17:00 CET\n(emergjenca: 24/7 permes formularit online)',
    },
  },

  // ============================================================
  // ENGLISH (EN)
  // ============================================================
  en: {
    shortTitle: 'Refunds',
    title: 'Refund Policy and Right of Withdrawal',
    subtitle: 'Our refund policy and your statutory right of withdrawal (Widerrufsbelehrung) under German law.',
    intro: 'This policy describes the conditions under which we provide refunds and your statutory right of withdrawal under German law. For business customers (B2B), only our internal refund policies apply. For consumers (B2C - private persons using the service for purposes outside their professional activity), the statutory right of withdrawal under \u00a7\u00a7 312g, 355 BGB also applies.',
    lastUpdated: '15 May 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Consumers vs Business Customers',
      body: 'TO DETERMINE YOUR REFUND RIGHTS, FIRST UNDERSTAND YOUR LEGAL STATUS:\n\nBUSINESS CUSTOMER (B2B - \u00a7 14 BGB):\nIf you use the service for professional/business activity purposes:\n\u2022 You do not have the statutory right of withdrawal\n\u2022 Only the refund policies below apply\n\u2022 The service is primarily intended for you\n\nCONSUMER (B2C - \u00a7 13 BGB):\nIf you use the service as a private person for purposes outside professional activity:\n\u2022 You have the 14-day statutory right of withdrawal (Widerrufsrecht)\n\u2022 Additional protection conditions apply\n\u2022 See "Widerrufsbelehrung" section below\n\nIn most cases, [PLATFORM NAME] users are business customers since the platform is dedicated to professional logistics. However, individual status will be respected if claimed.',
    },
    section2: {
      title: 'Main refund policy',
      body: 'FREE TRIAL:\nWe offer a 14-day free trial for new users. During this period:\n\u2022 You can cancel at any time at no cost\n\u2022 No automatic billing during the period\n\u2022 After the period, transition to chosen plan (confirmation required)\n\nFIRST MONTH - SATISFACTION GUARANTEE:\nIf in the first 30 days of paid subscription you are not satisfied with the service, we offer:\n\u2022 100% full refund no questions asked\n\u2022 Activation via email request within 30 days\n\u2022 Processing within 14 days of approval\n\nCONDITIONS FOR GUARANTEE:\n\u2022 Applies only to first plan purchase\n\u2022 Does not apply to upgrade or downgrade\n\u2022 Does not apply to users who have used more than 50% of quota\n\u2022 Once per customer\n\nMONTHLY SUBSCRIPTIONS (AFTER FIRST MONTH):\n\u2022 Cancellation effective at end of current period\n\u2022 Full access until end of paid cycle\n\u2022 No pro-rata refund for remaining period\n\nANNUAL SUBSCRIPTIONS:\n\u2022 Cancellation effective at end of contract year\n\u2022 Pro-rata refund only in special circumstances (see "Special Circumstances")',
    },
    section3: {
      title: 'WIDERRUFSBELEHRUNG (Statutory Right of Withdrawal - B2C)',
      body: 'THESE RIGHTS APPLY ONLY TO CONSUMERS (\u00a7 13 BGB).\n\nRIGHT OF WITHDRAWAL:\nYou have the right to withdraw from this contract within 14 days without giving any reason.\n\nWITHDRAWAL PERIOD:\nThe withdrawal period is 14 days from the day of the conclusion of the contract.\n\nEXERCISING THE RIGHT OF WITHDRAWAL:\nTo exercise your right of withdrawal, you must inform us:\n\n[COMPANY NAME]\n[Full address]\nE-mail: [widerruf@company.de]\nPhone: [+49 XXX XXXXXXX]\n\nBy means of a clear statement (e.g. a letter sent by post or e-mail) of your decision to withdraw from this contract.\n\nYou may use the model withdrawal form attached at the end of this policy, but this is not mandatory.\n\nTO MEET THE WITHDRAWAL DEADLINE, it is sufficient that you send the communication concerning the exercise of the right of withdrawal before the withdrawal period has expired.\n\nEFFECTS OF WITHDRAWAL:\nIf you withdraw from this contract, we will reimburse you all payments received from you, including delivery costs (with the exception of supplementary costs resulting from your choice of a type of delivery other than the cheapest standard delivery), without undue delay and in any event no later than 14 days from the day on which we are informed of your decision to withdraw from this contract.\n\nFor reimbursement, we will use the same means of payment that you used for the initial transaction, unless you have expressly agreed otherwise; in no case will you be charged any fees for this reimbursement.',
    },
    section4: {
      title: 'EXCLUSION OF WITHDRAWAL RIGHT FOR DIGITAL SERVICES',
      body: 'WITHOUT LOSING YOUR RIGHTS:\n\nUnder \u00a7 356 par. 4 BGB, the right of withdrawal may lapse before the end of the withdrawal period if:\n\n1. The service has been fully performed before the 14-day expiry\n2. You have given explicit prior consent\n3. You have confirmed consent for the performance acceptance after losing the withdrawal right\n\nTHIS APPLIES IF:\n\u2022 You activate a paid plan and start using it\n\u2022 You provide clear consent during activation\n\u2022 You confirm understanding that you will no longer have the right of withdrawal\n\nWE NOTIFY WITH CLEAR CONSENT:\nDuring paid plan activation, we display:\n\u2705 Checkbox: "I agree that service execution begins immediately"\n\u2705 Checkbox: "I acknowledge that my 14-day withdrawal right is lost when the service is fully performed"\n\nIF YOU DO NOT AGREE:\n\u2022 Your 14-day right of withdrawal is preserved\n\u2022 Service is not activated yet\n\u2022 After 14 days, service is automatically activated (unless you cancel)',
    },
    section5: {
      title: 'Special circumstances for refund',
      body: 'IN THESE SPECIAL CIRCUMSTANCES, WE OFFER REFUNDS EVEN OUTSIDE THE 30-DAY GUARANTEE:\n\n1. TECHNICAL PROBLEMS FOR MORE THAN 7 CONSECUTIVE DAYS:\n\u2022 Service unusable for more than 7 days\n\u2022 Due to our technical problems (not your internet)\n\u2022 After reporting and failed resolution\n\nCompensation: Pro-rata refund for downtime + 1 month free\n\n2. NEGATIVE MATERIAL CHANGES TO SERVICE:\nIf we remove main functions you have used:\n\u2022 30-day advance notice\n\u2022 Right to terminate without cost\n\u2022 Pro-rata refund for remaining period\n\n3. PRICE CHANGES:\nIf we raise the price during active contract:\n\u2022 60-day advance notice\n\u2022 Old price applies until end of year\n\u2022 You may terminate without cost\n\u2022 No pro-rata refund (not your fault)\n\n4. ACCOUNT SUSPENSION WITHOUT VIOLATION:\nIf we suspend your account mistakenly:\n\u2022 Full refund for suspension time\n\u2022 Restoration of all functions\n\u2022 Additional opportunity as compensation\n\n5. BANKRUPTCY OR SERVICE CLOSURE:\nIf we have to close the service:\n\u2022 90-day advance notice\n\u2022 Facilitated data export\n\u2022 Pro-rata refund for remaining period\n\u2022 Support for service migration',
    },
    section6: {
      title: 'No refund in these cases',
      body: 'REFUND NOT AVAILABLE IN THESE CIRCUMSTANCES:\n\n1. AFTER THE 30-DAY GUARANTEE PERIOD\nFor monthly subscriptions, cancellation effective at end of current month.\nFor annual subscriptions, cancellation effective at end of contract year.\n\n2. AGB OR AUP VIOLATIONS\nIf account suspended or terminated for violation:\n\u2022 No refund for remaining period\n\u2022 Remaining payment still due\n\u2022 Unavailability not considered service defect\n\n3. EXTRAORDINARY TERMINATION BY US\nFor catastrophic violations (CSAM, terrorism, fraud):\n\u2022 No refund\n\u2022 Immediate access blocked\n\u2022 Legal action may follow\n\n4. FULL USE OF SERVICE\nIf you have fully used main service functions:\n\u2022 Bulk delivery uploads\n\u2022 Multiple DATEV exports\n\u2022 API use above 80% of quota\nNot considered "unhappy" with service.\n\n5. INTERNET CONNECTION PROBLEMS\nIf the problem comes from your internet connection, provider, or device:\n\u2022 Not our responsibility\n\u2022 No refund\n\u2022 We can offer technical advice\n\n6. OVERAGE CHARGES\nIf you have exceeded plan quota and paid extra fees:\n\u2022 Extra fees are non-refundable\n\u2022 We offer better plan advice',
    },
    section7: {
      title: 'How to request refund',
      body: 'REFUND REQUEST PROCESS:\n\nSTEP 1: INITIAL CONTACT\nE-mail: [refund@company.de]\nSubject: "Refund request - [Account number]"\n\nREQUIRED INFORMATION:\n\u2022 Registered name and email\n\u2022 Account number / company ID\n\u2022 Active plan and activation date\n\u2022 Reason for request (for 30-day guarantee "dissatisfied" is enough)\n\u2022 Invoice number you want refunded\n\nSTEP 2: RECEIPT CONFIRMATION\nWe confirm receipt within 24 hours.\n\nSTEP 3: VERIFICATION\nVerification within 3 business days:\n\u2022 Account status confirmation\n\u2022 Conditions verification\n\u2022 If any exclusion applies\n\nSTEP 4: APPROVAL OR REJECTION\nNotification with written reason within 7 business days.\n\nSTEP 5: EXECUTION\nIf approved:\n\u2022 Processing within 14 days\n\u2022 Payment via same method as original payment\n\u2022 Email confirmation when processed\n\u2022 May take 5-10 additional days to appear in your account\n\nIF REJECTED:\n\u2022 Clear written reason\n\u2022 Alternative suggestions (free upgrade/downgrade possible, etc.)\n\u2022 Appeal possibility to [appeals@company.de]',
    },
    section8: {
      title: 'Fees and additional charges',
      body: 'NON-REFUNDABLE FEES:\n\n1. APPLICATION COSTS (when applicable)\nIf you applied for a special plan requiring additional documentation:\n\u2022 Verification cost is non-refundable\n\u2022 Even if application rejected\n\n2. OVERAGE CHARGES\nFor plan exceedance:\n\u2022 Bandwidth over limit\n\u2022 Storage over limit\n\u2022 API calls over limit\nThese charges are consumable and non-refundable.\n\n3. PROFESSIONAL SERVICES\n\u2022 Custom training\n\u2022 Implementation consulting\n\u2022 Customization\nThese on "pre-paid" basis with no refund after work begins.\n\n4. THIRD-PARTY COSTS\nIf plan includes third-party services:\n\u2022 Marketplaces (Shopify, etc.)\n\u2022 Domain service\n\u2022 SMS / Push notifications\nThese are subject to respective provider policies.\n\nAUTOMATICALLY REFUNDED FEES:\n\n1. DUPLICATE INVOICES\nIf billed twice by our mistake:\n\u2022 Automatic refund\n\u2022 Within 7 days\n\u2022 No need to request\n\n2. WRONGFUL SUSPENSION\nIf suspension proves to be wrong:\n\u2022 Refund for suspended time\n\u2022 Bonus 1 month free\n\u2022 Plus liability for possible damage',
    },
    section9: {
      title: 'Subscription cancellation (not refund)',
      body: 'TO CANCEL YOUR SUBSCRIPTION (WITHOUT REQUESTING REFUND):\n\nMONTHLY SUBSCRIPTION:\n1. Settings → Subscription\n2. Click "Cancel subscription"\n3. Confirm decision\n4. Full access until end of current month\n5. No future billing\n\nANNUAL SUBSCRIPTION:\n1. Settings → Subscription\n2. Click "Cancel subscription"\n3. Choose cancellation mode:\n   - Cancel at end of year (full access until then)\n   - Immediate cancellation (no pro-rata refund)\n4. Confirm decision\n\nAFTER CANCELLATION:\n\u2022 Receive confirmation email\n\u2022 30 days for data export\n\u2022 90 days backup in frozen archives\n\u2022 After 90 days: permanent deletion\n\nYOU CAN REACTIVATE:\nWithin 30 days of cancellation:\n\u2022 Full access to your data\n\u2022 Can change plan\n\u2022 Can activate different plan\n\nAFTER 30 DAYS:\nYou must create new account. Data may be unrecoverable.',
    },
    section10: {
      title: 'Model Withdrawal Form (B2C)',
      body: 'MODEL WITHDRAWAL FORM\n(Complete and return this form only if you wish to withdraw from the contract)\n\nTO:\n[COMPANY NAME]\n[Full address]\nE-mail: [widerruf@company.de]\n\nDECLARATION:\nI/We (*) hereby give notice that I/we (*) withdraw from my/our (*) contract of sale of the following goods (*)/for the provision of the following service (*):\n\n_______________________________________________\n[Description of service / subscription plan]\n_______________________________________________\n\nORDERED ON: __________________________\nRECEIVED ON: __________________________\n\nNAME OF CONSUMER(S): ___________________\n\nADDRESS OF CONSUMER(S): ________________\n_______________________________________________\n\nACCOUNT NUMBER / ID: ____________________\n\nSIGNATURE OF CONSUMER(S): _____________\n(only if this form is notified on paper)\n\nDATE: __________________________________\n\n(*) Delete as appropriate\n\n--- END OF FORM ---\n\nThis form is not mandatory - you can use any clear statement (email, letter, online form) indicating your decision to withdraw.',
    },
    section11: {
      title: 'Payments and refunds',
      body: 'ACCEPTED PAYMENT METHODS:\n\u2022 Credit card (Visa, Mastercard, American Express)\n\u2022 Debit card (Maestro, V-Pay)\n\u2022 SEPA Direct Debit (EU)\n\u2022 PayPal\n\u2022 Bank transfer (only for enterprise plans)\n\u2022 Apple Pay / Google Pay (in some cases)\n\nREFUND METHOD:\nRefunds are made in the same method as original payment:\n\u2022 Card → Card (5-10 business days to account)\n\u2022 SEPA → SEPA (3-5 business days)\n\u2022 PayPal → PayPal (24-48 hours)\n\u2022 Bank transfer → Bank transfer (5-7 business days)\n\nPAYMENT SPLITTING:\nIf you pay with different methods for one subscription, we refund proportionally based on original method.\n\nCURRENCY:\n\u2022 EUR as standard\n\u2022 May offer USD or GBP for international customers\n\u2022 Refund made in same currency as original payment\n\u2022 No exchange rate change fees\n\nINVOICING:\n\u2022 Fiscal invoices sent electronically (PDF + XRechnung)\n\u2022 Refund creates "Gutschrift" (credit note)\n\u2022 All transactions logged in audit log\n\u2022 Our accounting respects GoBD standards',
    },
    section12: {
      title: 'Disputes and arbitration',
      body: 'IF YOU DISAGREE WITH REFUND DECISION:\n\nSTEP 1: INTERNAL APPEAL\nE-mail: [appeals@company.de]\nWith new explanation and evidence:\n\u2022 Review by independent team\n\u2022 Written response within 14 days\n\u2022 Final decision with reasoning\n\nSTEP 2: ALTERNATIVE DISPUTE RESOLUTION (ADR)\nFor B2C consumers in EU:\nEuropean Commission provides online platform:\nhttps://ec.europa.eu/consumers/odr/\n\nWe DO NOT participate in mandatory consumer arbitration procedures, unless legally regulated otherwise.\n\nSTEP 3: COURT\nIf you wish to follow legal path:\n\u2022 For business customers (B2B): jurisdiction [CITY OF REGISTRATION], Germany\n\u2022 For consumers (B2C): jurisdiction of your home country (per Br\u00fcssel I Regulation)\n\u2022 Applicable law: German law for contracts concluded in Germany\n\nTRANSPARENT EVIDENCE:\nE-mail building and communication are stored with audit log for legal purposes. In Germany, this is mandatory under GoBD.',
    },
    section13: {
      title: 'Frequently Asked Questions',
      body: 'Q: Can I refund if I paid for 1 year but only used 2 months?\nA: Only if you are within 30-days of activation or special circumstances apply (technical problem, etc.). After that, only cancellation for end of contract year.\n\nQ: How long does refund take?\nA: 14 days for approval + 5-10 days for processing + 1-3 days to appear in account = ~20-25 days total.\n\nQ: Can I change my plan?\nA: Yes, you can upgrade anytime (difference paid pro-rata) or downgrade at end of current cycle.\n\nQ: Do I lose data if I refund?\nA: No, data is retained for 30 days export + 90 days backup. You can recover if reactivating.\n\nQ: What happens with invoices in accounting?\nA: A "Gutschrift" (credit note) is created cancelling original invoice. We send you a second fiscal document.\n\nQ: Can I refund add-on or overage?\nA: For add-on (additional services, premium modules) no - they are consumable. For automatic overage charges (overage charges) varies.\n\nQ: Can I transfer account to another person?\nA: Yes, with written notification and recipient confirmation. Fee: €50 (one-time). Contact [billing@company.de].\n\nQ: What if my company goes bankrupt?\nA: You may have right to terminate and receive pro-rata refund. Contact with legal bankruptcy documentation.',
    },
    section14: {
      title: 'Changes to refund policy',
      body: 'THIS POLICY MAY BE UPDATED TO REFLECT:\n\u2022 Legal changes (\u00a7\u00a7 312g, 355 BGB, EU Directive 2011/83)\n\u2022 Changes in our business practice\n\u2022 Customer feedback\n\u2022 Transparency improvements\n\nCOMMUNICATION OF CHANGES:\n\u2022 Email to active users 30 days in advance\n\u2022 Platform banner\n\u2022 Updated datestamp at top of document\n\nPROTECTION OF EXISTING RIGHTS:\nChanges do NOT affect existing contracts - only new ones:\n\u2022 Your current plan retains original rules until end\n\u2022 Guaranteed rights not removed retroactively\n\u2022 Improvements applied automatically\n\nYOU CAN TERMINATE:\nIf you do not agree with changes:\n\u2022 30 days for termination at no additional cost\n\u2022 Pro-rata refund for negative changes\n\u2022 Facilitated data export',
    },
    section15: {
      title: 'Contact',
      body: 'REFUND QUESTIONS:\nE-mail: [refund@company.de]\nResponse within 24 hours.\n\nWIDERRUF (B2C WITHDRAWAL):\nE-mail: [widerruf@company.de]\nMail: [Full address], dept. "Widerruf"\n\nBILLING:\nE-mail: [billing@company.de]\nQuestions about invoices, payment method change, etc.\n\nAPPEALS:\nE-mail: [appeals@company.de]\nDeadline: 30 days from original decision\n\nGENERAL SUPPORT:\nE-mail: [support@company.de]\nLive chat: within platform (business hours)\n\nFOR LEGAL ISSUES:\nE-mail: [legal@company.de]\n\nOFFICIAL MAIL:\n[COMPANY NAME]\n[Full address]\nGermany\nPhone: [+49 XXX XXXXXXX]\n\nBUSINESS HOURS:\nMonday - Friday: 09:00 - 17:00 CET\n(emergencies: 24/7 via online form)',
    },
  },

  // ============================================================
  // GERMAN (DE) - canonical legal version
  // ============================================================
  de: {
    shortTitle: 'R\u00fcckerstattung',
    title: 'R\u00fcckerstattungsrichtlinie und Widerrufsrecht',
    subtitle: 'Unsere R\u00fcckerstattungsrichtlinie und Ihr gesetzliches Widerrufsrecht (Widerrufsbelehrung) nach deutschem Recht.',
    intro: 'Diese Richtlinie beschreibt die Bedingungen, unter denen wir R\u00fcckerstattungen gew\u00e4hren, und Ihr gesetzliches Widerrufsrecht nach deutschem Recht. F\u00fcr Gesch\u00e4ftskunden (B2B) gelten nur unsere internen R\u00fcckerstattungsrichtlinien. F\u00fcr Verbraucher (B2C - Privatpersonen, die den Dienst f\u00fcr Zwecke au\u00dferhalb ihrer beruflichen T\u00e4tigkeit nutzen) gilt auch das gesetzliche Widerrufsrecht nach \u00a7\u00a7 312g, 355 BGB.',
    lastUpdated: '15. Mai 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Verbraucher gegen Gesch\u00e4ftskunden',
      body: 'UM IHRE R\u00dcCKERSTATTUNGSRECHTE ZU BESTIMMEN, VERSTEHEN SIE ZUERST IHREN RECHTSSTATUS:\n\nGESCH\u00c4FTSKUNDE (B2B - \u00a7 14 BGB):\nWenn Sie den Dienst f\u00fcr berufliche/gesch\u00e4ftliche T\u00e4tigkeitszwecke nutzen:\n\u2022 Sie haben kein gesetzliches Widerrufsrecht\n\u2022 Nur die folgenden R\u00fcckerstattungsrichtlinien gelten\n\u2022 Der Dienst ist haupts\u00e4chlich f\u00fcr Sie bestimmt\n\nVERBRAUCHER (B2C - \u00a7 13 BGB):\nWenn Sie den Dienst als Privatperson f\u00fcr Zwecke au\u00dferhalb beruflicher T\u00e4tigkeit nutzen:\n\u2022 Sie haben das 14-t\u00e4gige gesetzliche Widerrufsrecht\n\u2022 Zus\u00e4tzliche Schutzbedingungen gelten\n\u2022 Siehe Abschnitt "Widerrufsbelehrung" unten\n\nIn den meisten F\u00e4llen sind [PLATTFORMNAME]-Nutzer Gesch\u00e4ftskunden, da die Plattform f\u00fcr professionelle Logistik bestimmt ist. Der individuelle Status wird jedoch respektiert, wenn beansprucht.',
    },
    section2: {
      title: 'Hauptr\u00fcckerstattungsrichtlinie',
      body: 'KOSTENLOSE TESTPHASE:\nWir bieten 14 Tage kostenlose Testphase f\u00fcr neue Nutzer. W\u00e4hrend dieser Zeit:\n\u2022 Sie k\u00f6nnen jederzeit kostenlos k\u00fcndigen\n\u2022 Keine automatische Abrechnung w\u00e4hrend der Periode\n\u2022 Nach der Periode \u00dcbergang zum gew\u00e4hlten Plan (Best\u00e4tigung erforderlich)\n\nERSTE MONAT - ZUFRIEDENHEITSGARANTIE:\nWenn Sie in den ersten 30 Tagen des bezahlten Abonnements nicht zufrieden sind, bieten wir:\n\u2022 100% volle R\u00fcckerstattung ohne Fragen\n\u2022 Aktivierung per E-Mail-Anfrage innerhalb von 30 Tagen\n\u2022 Bearbeitung innerhalb von 14 Tagen nach Genehmigung\n\nBEDINGUNGEN F\u00dcR GARANTIE:\n\u2022 Gilt nur f\u00fcr den ersten Plankauf\n\u2022 Gilt nicht f\u00fcr Upgrade oder Downgrade\n\u2022 Gilt nicht f\u00fcr Nutzer, die mehr als 50% der Quote verwendet haben\n\u2022 Einmal pro Kunde\n\nMONATLICHE ABONNEMENTS (NACH ERSTEM MONAT):\n\u2022 K\u00fcndigung mit Wirkung zum Ende der aktuellen Periode\n\u2022 Vollst\u00e4ndiger Zugang bis zum Ende des bezahlten Zyklus\n\u2022 Keine anteilige R\u00fcckerstattung f\u00fcr verbleibende Periode\n\nJ\u00c4HRLICHE ABONNEMENTS:\n\u2022 K\u00fcndigung mit Wirkung zum Ende des Vertragsjahres\n\u2022 Anteilige R\u00fcckerstattung nur in besonderen Umst\u00e4nden (siehe "Besondere Umst\u00e4nde")',
    },
    section3: {
      title: 'WIDERRUFSBELEHRUNG (Gesetzliches Widerrufsrecht - B2C)',
      body: 'DIESE RECHTE GELTEN NUR F\u00dcR VERBRAUCHER (\u00a7 13 BGB).\n\nWIDERRUFSRECHT:\nSie haben das Recht, binnen 14 Tagen ohne Angabe von Gr\u00fcnden diesen Vertrag zu widerrufen.\n\nWIDERRUFSFRIST:\nDie Widerrufsfrist betr\u00e4gt 14 Tage ab dem Tag des Vertragsabschlusses.\n\nAUS\u00dcBUNG DES WIDERRUFSRECHTS:\nUm Ihr Widerrufsrecht auszu\u00fcben, m\u00fcssen Sie uns informieren:\n\n[FIRMENNAME]\n[Vollst\u00e4ndige Anschrift]\nE-Mail: [widerruf@firma.de]\nTelefon: [+49 XXX XXXXXXX]\n\nMittels einer eindeutigen Erkl\u00e4rung (z. B. ein mit der Post versandter Brief oder E-Mail) \u00fcber Ihren Entschluss, diesen Vertrag zu widerrufen.\n\nSie k\u00f6nnen das beigef\u00fcgte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.\n\nZUR WAHRUNG DER WIDERRUFSFRIST reicht es aus, dass Sie die Mitteilung \u00fcber die Aus\u00fcbung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.\n\nFOLGEN DES WIDERRUFS:\nWenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschlie\u00dflich der Lieferkosten (mit Ausnahme der zus\u00e4tzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, g\u00fcnstigste Standardlieferung gew\u00e4hlt haben), unverz\u00fcglich und sp\u00e4testens binnen vierzehn Tagen ab dem Tag zur\u00fcckzuzahlen, an dem die Mitteilung \u00fcber Ihren Widerruf dieses Vertrags bei uns eingegangen ist.\n\nF\u00fcr diese R\u00fcckzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der urspr\u00fcnglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdr\u00fccklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser R\u00fcckzahlung Entgelte berechnet.',
    },
    section4: {
      title: 'AUSSCHLUSS DES WIDERRUFSRECHTS BEI DIGITALEN DIENSTEN',
      body: 'OHNE VERLUST IHRER RECHTE:\n\nNach \u00a7 356 Abs. 4 BGB kann das Widerrufsrecht vor Ablauf der Widerrufsfrist erl\u00f6schen, wenn:\n\n1. Der Dienst vor Ablauf der 14 Tage vollst\u00e4ndig erbracht wurde\n2. Sie ausdr\u00fccklich vorher zugestimmt haben\n3. Sie die Zustimmung zur Annahme der Leistung nach dem Verlust des Widerrufsrechts best\u00e4tigt haben\n\nDIES GILT, WENN:\n\u2022 Sie einen bezahlten Plan aktivieren und mit der Nutzung beginnen\n\u2022 Sie w\u00e4hrend der Aktivierung klare Zustimmung geben\n\u2022 Sie das Verst\u00e4ndnis best\u00e4tigen, dass Sie das Widerrufsrecht verlieren\n\nWIR INFORMIEREN MIT KLARER ZUSTIMMUNG:\nBei der Aktivierung eines bezahlten Plans zeigen wir:\n\u2705 Checkbox: "Ich stimme zu, dass die Dienstausf\u00fchrung sofort beginnt"\n\u2705 Checkbox: "Ich erkenne an, dass mein 14-t\u00e4giges Widerrufsrecht erlischt, wenn der Dienst vollst\u00e4ndig erbracht wird"\n\nWENN SIE NICHT ZUSTIMMEN:\n\u2022 Ihr 14-t\u00e4giges Widerrufsrecht bleibt erhalten\n\u2022 Dienst ist noch nicht aktiviert\n\u2022 Nach 14 Tagen wird der Dienst automatisch aktiviert (au\u00dfer Sie k\u00fcndigen)',
    },
    section5: {
      title: 'Besondere Umst\u00e4nde f\u00fcr R\u00fcckerstattung',
      body: 'IN DIESEN BESONDEREN UMST\u00c4NDEN BIETEN WIR R\u00dcCKERSTATTUNGEN AUCH AUSSERHALB DER 30-TAGE-GARANTIE:\n\n1. TECHNISCHE PROBLEME F\u00dcR MEHR ALS 7 AUFEINANDERFOLGENDE TAGE:\n\u2022 Dienst f\u00fcr mehr als 7 Tage unbrauchbar\n\u2022 Aufgrund unserer technischen Probleme (nicht Ihres Internets)\n\u2022 Nach Meldung und fehlgeschlagener L\u00f6sung\n\nEntsch\u00e4digung: Anteilige R\u00fcckerstattung f\u00fcr Ausfallzeit + 1 Monat kostenlos\n\n2. NEGATIVE WESENTLICHE \u00c4NDERUNGEN AM DIENST:\nWenn wir Hauptfunktionen entfernen, die Sie genutzt haben:\n\u2022 30-Tage-Vorank\u00fcndigung\n\u2022 Recht auf K\u00fcndigung ohne Kosten\n\u2022 Anteilige R\u00fcckerstattung f\u00fcr verbleibende Periode\n\n3. PREIS\u00c4NDERUNGEN:\nWenn wir den Preis w\u00e4hrend des aktiven Vertrags erh\u00f6hen:\n\u2022 60-Tage-Vorank\u00fcndigung\n\u2022 Alter Preis gilt bis Ende des Jahres\n\u2022 Sie k\u00f6nnen ohne Kosten k\u00fcndigen\n\u2022 Keine anteilige R\u00fcckerstattung (nicht Ihre Schuld)\n\n4. KONTOSPERRE OHNE VERSTOSS:\nWenn wir Ihr Konto irrt\u00fcmlich sperren:\n\u2022 Volle R\u00fcckerstattung f\u00fcr Sperrzeit\n\u2022 Wiederherstellung aller Funktionen\n\u2022 Zus\u00e4tzliche Gelegenheit als Entsch\u00e4digung\n\n5. INSOLVENZ ODER DIENSTSCHLIESSUNG:\nWenn wir den Dienst schlie\u00dfen m\u00fcssen:\n\u2022 90-Tage-Vorank\u00fcndigung\n\u2022 Erleichterte Datenexport\n\u2022 Anteilige R\u00fcckerstattung f\u00fcr verbleibende Periode\n\u2022 Unterst\u00fctzung bei Service-Migration',
    },
    section6: {
      title: 'Keine R\u00fcckerstattung in diesen F\u00e4llen',
      body: 'R\u00dcCKERSTATTUNG NICHT VERF\u00dcGBAR IN DIESEN UMST\u00c4NDEN:\n\n1. NACH DER 30-TAGE-GARANTIEPERIODE\nF\u00fcr monatliche Abonnements wirkt K\u00fcndigung zum Ende des aktuellen Monats.\nF\u00fcr j\u00e4hrliche Abonnements wirkt K\u00fcndigung zum Ende des Vertragsjahres.\n\n2. AGB- ODER AUP-VERST\u00d6SSE\nWenn das Konto wegen Versto\u00dfes gesperrt oder beendet wird:\n\u2022 Keine R\u00fcckerstattung f\u00fcr verbleibende Periode\n\u2022 Verbleibende Zahlung ist noch f\u00e4llig\n\u2022 Nichtverf\u00fcgbarkeit gilt nicht als Service-Defekt\n\n3. AUSSERORDENTLICHE BEENDIGUNG DURCH UNS\nF\u00fcr katastrophale Verst\u00f6\u00dfe (CSAM, Terrorismus, Betrug):\n\u2022 Keine R\u00fcckerstattung\n\u2022 Sofortiger Zugriff blockiert\n\u2022 Rechtliche Schritte k\u00f6nnen folgen\n\n4. VOLLST\u00c4NDIGE NUTZUNG DES DIENSTES\nWenn Sie die Hauptfunktionen des Dienstes vollst\u00e4ndig genutzt haben:\n\u2022 Massen-Lieferungs-Uploads\n\u2022 Mehrere DATEV-Exporte\n\u2022 API-Nutzung \u00fcber 80% der Quote\nNicht als "unzufrieden" mit dem Service betrachtet.\n\n5. INTERNETVERBINDUNGSPROBLEME\nWenn das Problem von Ihrer Internetverbindung, Ihrem Anbieter oder Ger\u00e4t kommt:\n\u2022 Nicht unsere Verantwortung\n\u2022 Keine R\u00fcckerstattung\n\u2022 Wir k\u00f6nnen technischen Rat anbieten\n\n6. ZUSATZGEB\u00dcHREN\nWenn Sie Planquote \u00fcberschritten und zus\u00e4tzliche Geb\u00fchren bezahlt haben:\n\u2022 Zus\u00e4tzliche Geb\u00fchren sind nicht erstattungsf\u00e4hig\n\u2022 Wir bieten Rat zu besserem Plan',
    },
    section7: {
      title: 'Wie Sie R\u00fcckerstattung beantragen',
      body: 'R\u00dcCKERSTATTUNGSANFRAGE-PROZESS:\n\nSCHRITT 1: ERSTKONTAKT\nE-Mail: [refund@firma.de]\nBetreff: "R\u00fcckerstattungsanfrage - [Kontonummer]"\n\nERFORDERLICHE INFORMATIONEN:\n\u2022 Registrierter Name und E-Mail\n\u2022 Kontonummer / Firmen-ID\n\u2022 Aktiver Plan und Aktivierungsdatum\n\u2022 Grund der Anfrage (f\u00fcr 30-Tage-Garantie reicht "unzufrieden")\n\u2022 Rechnungsnummer, die zur\u00fcckerstattet werden soll\n\nSCHRITT 2: EMPFANGSBEST\u00c4TIGUNG\nWir best\u00e4tigen den Empfang innerhalb von 24 Stunden.\n\nSCHRITT 3: VERIFIKATION\nVerifikation innerhalb von 3 Werktagen:\n\u2022 Kontostatus-Best\u00e4tigung\n\u2022 Bedingungs-Verifikation\n\u2022 Wenn ein Ausschluss gilt\n\nSCHRITT 4: GENEHMIGUNG ODER ABLEHNUNG\nBenachrichtigung mit schriftlicher Begr\u00fcndung innerhalb von 7 Werktagen.\n\nSCHRITT 5: AUSF\u00dcHRUNG\nWenn genehmigt:\n\u2022 Bearbeitung innerhalb von 14 Tagen\n\u2022 Zahlung \u00fcber dieselbe Methode wie urspr\u00fcngliche Zahlung\n\u2022 E-Mail-Best\u00e4tigung bei Bearbeitung\n\u2022 Kann 5-10 zus\u00e4tzliche Tage dauern, bis es auf Ihrem Konto erscheint\n\nWENN ABGELEHNT:\n\u2022 Klare schriftliche Begr\u00fcndung\n\u2022 Alternative Vorschl\u00e4ge (kostenloses Upgrade/Downgrade m\u00f6glich usw.)\n\u2022 Einspruchsm\u00f6glichkeit an [appeals@firma.de]',
    },
    section8: {
      title: 'Geb\u00fchren und zus\u00e4tzliche Kosten',
      body: 'NICHT ERSTATTUNGSF\u00c4HIGE GEB\u00dcHREN:\n\n1. BEWERBUNGSKOSTEN (wenn anwendbar)\nWenn Sie sich f\u00fcr einen Sonderplan beworben haben, der zus\u00e4tzliche Dokumentation erfordert:\n\u2022 Verifikationskosten sind nicht erstattungsf\u00e4hig\n\u2022 Auch bei abgelehnter Bewerbung\n\n2. ZUSATZGEB\u00dcHREN\nF\u00fcr Plan\u00fcberschreitung:\n\u2022 Bandbreite \u00fcber Limit\n\u2022 Storage \u00fcber Limit\n\u2022 API-Calls \u00fcber Limit\nDiese Geb\u00fchren sind verbrauchbar und nicht erstattungsf\u00e4hig.\n\n3. PROFESSIONELLE DIENSTLEISTUNGEN\n\u2022 Ma\u00dfgeschneiderte Schulungen\n\u2022 Implementierungsberatung\n\u2022 Anpassung\nDiese auf "Vorauszahlungs"-Basis ohne R\u00fcckerstattung nach Arbeitsbeginn.\n\n4. KOSTEN DRITTER\nWenn Plan Dienste Dritter umfasst:\n\u2022 Marketplaces (Shopify usw.)\n\u2022 Domain-Service\n\u2022 SMS / Push-Benachrichtigungen\nDiese unterliegen den jeweiligen Anbieter-Richtlinien.\n\nAUTOMATISCH ERSTATTETE GEB\u00dcHREN:\n\n1. DUPLIZIERTE RECHNUNGEN\nBei doppelter Abrechnung durch unseren Fehler:\n\u2022 Automatische R\u00fcckerstattung\n\u2022 Innerhalb von 7 Tagen\n\u2022 Ohne Anfrage erforderlich\n\n2. UNRECHTM\u00c4SSIGE SPERRE\nWenn sich Sperre als falsch erweist:\n\u2022 R\u00fcckerstattung f\u00fcr gesperrte Zeit\n\u2022 Bonus 1 Monat kostenlos\n\u2022 Plus Haftung f\u00fcr m\u00f6glichen Schaden',
    },
    section9: {
      title: 'Abonnementk\u00fcndigung (keine R\u00fcckerstattung)',
      body: 'UM IHR ABONNEMENT ZU K\u00dcNDIGEN (OHNE R\u00dcCKERSTATTUNG ZU BEANTRAGEN):\n\nMONATSABONNEMENT:\n1. Einstellungen → Abonnement\n2. Klicken Sie "Abonnement k\u00fcndigen"\n3. Entscheidung best\u00e4tigen\n4. Vollst\u00e4ndiger Zugang bis Ende des aktuellen Monats\n5. Keine zuk\u00fcnftige Abrechnung\n\nJAHRESABONNEMENT:\n1. Einstellungen → Abonnement\n2. Klicken Sie "Abonnement k\u00fcndigen"\n3. K\u00fcndigungsmodus w\u00e4hlen:\n   - K\u00fcndigung am Jahresende (voller Zugang bis dahin)\n   - Sofortige K\u00fcndigung (keine anteilige R\u00fcckerstattung)\n4. Entscheidung best\u00e4tigen\n\nNACH K\u00dcNDIGUNG:\n\u2022 Best\u00e4tigungs-E-Mail erhalten\n\u2022 30 Tage f\u00fcr Datenexport\n\u2022 90 Tage Backup in eingefrorenen Archiven\n\u2022 Nach 90 Tagen: permanente L\u00f6schung\n\nSIE K\u00d6NNEN REAKTIVIEREN:\nInnerhalb von 30 Tagen nach K\u00fcndigung:\n\u2022 Voller Zugang zu Ihren Daten\n\u2022 Plan \u00e4nderbar\n\u2022 Anderen Plan aktivieren m\u00f6glich\n\nNACH 30 TAGEN:\nSie m\u00fcssen ein neues Konto erstellen. Daten k\u00f6nnen unwiederbringlich sein.',
    },
    section10: {
      title: 'Muster-Widerrufsformular (B2C)',
      body: 'MUSTER-WIDERRUFSFORMULAR\n(Wenn Sie den Vertrag widerrufen wollen, dann f\u00fcllen Sie bitte dieses Formular aus und senden Sie es zur\u00fcck)\n\nAN:\n[FIRMENNAME]\n[Vollst\u00e4ndige Anschrift]\nE-Mail: [widerruf@firma.de]\n\nERKL\u00c4RUNG:\nHiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag \u00fcber den Kauf der folgenden Dienstleistung (*):\n\n_______________________________________________\n[Beschreibung des Service / Abonnement-Plans]\n_______________________________________________\n\nBESTELLT AM: __________________________\nERHALTEN AM: __________________________\n\nNAME DES/DER VERBRAUCHER(S): _____________\n\nANSCHRIFT DES/DER VERBRAUCHER(S): __________\n_______________________________________________\n\nKONTONUMMER / ID: ____________________\n\nUNTERSCHRIFT DES/DER VERBRAUCHER(S): _________\n(nur bei Mitteilung auf Papier)\n\nDATUM: __________________________________\n\n(*) Unzutreffendes streichen\n\n--- ENDE DES FORMULARS ---\n\nDieses Formular ist nicht vorgeschrieben - Sie k\u00f6nnen jede eindeutige Erkl\u00e4rung (E-Mail, Brief, Online-Formular) verwenden, die Ihren Entschluss zum Widerruf angibt.',
    },
    section11: {
      title: 'Zahlungen und R\u00fcckerstattungen',
      body: 'AKZEPTIERTE ZAHLUNGSMETHODEN:\n\u2022 Kreditkarte (Visa, Mastercard, American Express)\n\u2022 Debitkarte (Maestro, V-Pay)\n\u2022 SEPA-Lastschrift (EU)\n\u2022 PayPal\n\u2022 Bank\u00fcberweisung (nur f\u00fcr Enterprise-Pl\u00e4ne)\n\u2022 Apple Pay / Google Pay (in einigen F\u00e4llen)\n\nR\u00dcCKERSTATTUNGSMETHODE:\nR\u00fcckerstattungen erfolgen in derselben Methode wie urspr\u00fcngliche Zahlung:\n\u2022 Karte → Karte (5-10 Werktage bis Konto)\n\u2022 SEPA → SEPA (3-5 Werktage)\n\u2022 PayPal → PayPal (24-48 Stunden)\n\u2022 Bank\u00fcberweisung → Bank\u00fcberweisung (5-7 Werktage)\n\nZAHLUNGSAUFTEILUNG:\nWenn Sie mit verschiedenen Methoden f\u00fcr ein Abonnement zahlen, erstatten wir proportional basierend auf urspr\u00fcnglicher Methode.\n\nW\u00c4HRUNG:\n\u2022 EUR als Standard\n\u2022 USD oder GBP f\u00fcr internationale Kunden m\u00f6glich\n\u2022 R\u00fcckerstattung in derselben W\u00e4hrung wie urspr\u00fcngliche Zahlung\n\u2022 Keine Wechselkurs\u00e4nderungsgeb\u00fchren\n\nRECHNUNGSSTELLUNG:\n\u2022 Steuerliche Rechnungen elektronisch gesendet (PDF + XRechnung)\n\u2022 R\u00fcckerstattung erstellt "Gutschrift"\n\u2022 Alle Transaktionen im Audit-Log protokolliert\n\u2022 Unsere Buchhaltung respektiert GoBD-Standards',
    },
    section12: {
      title: 'Streitigkeiten und Schiedsverfahren',
      body: 'WENN SIE MIT R\u00dcCKERSTATTUNGSENTSCHEIDUNG NICHT EINVERSTANDEN SIND:\n\nSCHRITT 1: INTERNER EINSPRUCH\nE-Mail: [appeals@firma.de]\nMit neuer Erkl\u00e4rung und Beweisen:\n\u2022 \u00dcberpr\u00fcfung durch unabh\u00e4ngiges Team\n\u2022 Schriftliche Antwort innerhalb von 14 Tagen\n\u2022 Endg\u00fcltige Entscheidung mit Begr\u00fcndung\n\nSCHRITT 2: ALTERNATIVE STREITBEILEGUNG (ADR)\nF\u00fcr B2C-Verbraucher in der EU:\nEurop\u00e4ische Kommission bietet Online-Plattform:\nhttps://ec.europa.eu/consumers/odr/\n\nWir NEHMEN NICHT an verpflichtenden Verbraucherschiedsverfahren teil, au\u00dfer es ist gesetzlich anders geregelt.\n\nSCHRITT 3: GERICHT\nWenn Sie den Rechtsweg verfolgen wollen:\n\u2022 F\u00fcr Gesch\u00e4ftskunden (B2B): Gerichtsstand [STADT DER REGISTRIERUNG], Deutschland\n\u2022 F\u00fcr Verbraucher (B2C): Gerichtsstand Ihres Wohnsitzlandes (gem\u00e4\u00df Br\u00fcssel-I-Verordnung)\n\u2022 Anwendbares Recht: deutsches Recht f\u00fcr in Deutschland geschlossene Vertr\u00e4ge\n\nTRANSPARENTE BEWEISE:\nE-Mail-Aufbau und Kommunikation werden mit Audit-Log f\u00fcr rechtliche Zwecke gespeichert. In Deutschland ist dies nach GoBD vorgeschrieben.',
    },
    section13: {
      title: 'H\u00e4ufig gestellte Fragen',
      body: 'F: Kann ich erstatten, wenn ich f\u00fcr 1 Jahr bezahlt habe, aber nur 2 Monate genutzt habe?\nA: Nur wenn Sie innerhalb von 30 Tagen nach Aktivierung sind oder besondere Umst\u00e4nde vorliegen (technisches Problem usw.). Danach nur K\u00fcndigung zum Vertragsjahresende.\n\nF: Wie lange dauert die R\u00fcckerstattung?\nA: 14 Tage f\u00fcr Genehmigung + 5-10 Tage f\u00fcr Bearbeitung + 1-3 Tage bis es auf Konto erscheint = ~20-25 Tage gesamt.\n\nF: Kann ich meinen Plan \u00e4ndern?\nA: Ja, Sie k\u00f6nnen jederzeit upgraden (Differenz anteilig bezahlt) oder zum Ende des aktuellen Zyklus downgraden.\n\nF: Verliere ich Daten, wenn ich erstatten lasse?\nA: Nein, Daten werden f\u00fcr 30 Tage Export + 90 Tage Backup aufbewahrt. Sie k\u00f6nnen sich erholen, wenn Sie reaktivieren.\n\nF: Was passiert mit Rechnungen in der Buchhaltung?\nA: Eine "Gutschrift" wird erstellt, die die urspr\u00fcngliche Rechnung storniert. Wir senden Ihnen ein zweites steuerliches Dokument.\n\nF: Kann ich Add-on oder Zusatzkosten erstatten?\nA: F\u00fcr Add-ons (zus\u00e4tzliche Dienste, Premium-Module) nein - sie sind verbrauchbar. F\u00fcr automatische Zusatzkosten variiert es.\n\nF: Kann ich Konto auf eine andere Person \u00fcbertragen?\nA: Ja, mit schriftlicher Mitteilung und Empf\u00e4nger-Best\u00e4tigung. Geb\u00fchr: €50 (einmalig). Kontaktieren Sie [billing@firma.de].\n\nF: Was, wenn meine Firma insolvent wird?\nA: Sie k\u00f6nnen das Recht haben, zu k\u00fcndigen und anteilige R\u00fcckerstattung zu erhalten. Kontaktieren Sie uns mit rechtlicher Insolvenz-Dokumentation.',
    },
    section14: {
      title: '\u00c4nderungen der R\u00fcckerstattungsrichtlinie',
      body: 'DIESE RICHTLINIE KANN AKTUALISIERT WERDEN, UM FOLGENDES WIDERZUSPIEGELN:\n\u2022 Rechts\u00e4nderungen (\u00a7\u00a7 312g, 355 BGB, EU-Richtlinie 2011/83)\n\u2022 \u00c4nderungen in unserer Gesch\u00e4ftspraxis\n\u2022 Kundenfeedback\n\u2022 Transparenzverbesserungen\n\nKOMMUNIKATION DER \u00c4NDERUNGEN:\n\u2022 E-Mail an aktive Nutzer 30 Tage im Voraus\n\u2022 Plattform-Banner\n\u2022 Aktualisierter Datumsstempel oben im Dokument\n\nSCHUTZ DER BESTEHENDEN RECHTE:\n\u00c4nderungen ber\u00fchren NICHT bestehende Vertr\u00e4ge - nur neue:\n\u2022 Ihr aktueller Plan beh\u00e4lt urspr\u00fcngliche Regeln bis zum Ende\n\u2022 Garantierte Rechte werden nicht r\u00fcckwirkend entfernt\n\u2022 Verbesserungen automatisch angewendet\n\nSIE K\u00d6NNEN K\u00dcNDIGEN:\nWenn Sie mit den \u00c4nderungen nicht zustimmen:\n\u2022 30 Tage f\u00fcr K\u00fcndigung ohne zus\u00e4tzliche Kosten\n\u2022 Anteilige R\u00fcckerstattung f\u00fcr negative \u00c4nderungen\n\u2022 Erleichterte Datenexport',
    },
    section15: {
      title: 'Kontakt',
      body: 'R\u00dcCKERSTATTUNGSFRAGEN:\nE-Mail: [refund@firma.de]\nAntwort innerhalb von 24 Stunden.\n\nWIDERRUF (B2C):\nE-Mail: [widerruf@firma.de]\nPost: [Vollst\u00e4ndige Anschrift], Abt. "Widerruf"\n\nRECHNUNGSSTELLUNG:\nE-Mail: [billing@firma.de]\nFragen zu Rechnungen, Zahlungsmethoden\u00e4nderung usw.\n\nEINSPR\u00dcCHE:\nE-Mail: [appeals@firma.de]\nFrist: 30 Tage ab urspr\u00fcnglicher Entscheidung\n\nALLGEMEINER SUPPORT:\nE-Mail: [support@firma.de]\nLive-Chat: innerhalb der Plattform (Gesch\u00e4ftszeiten)\n\nF\u00dcR RECHTLICHE FRAGEN:\nE-Mail: [legal@firma.de]\n\nOFFIZIELLE POST:\n[FIRMENNAME]\n[Vollst\u00e4ndige Anschrift]\nDeutschland\nTelefon: [+49 XXX XXXXXXX]\n\nGESCH\u00c4FTSZEITEN:\nMontag - Freitag: 09:00 - 17:00 MEZ\n(Notf\u00e4lle: 24/7 \u00fcber Online-Formular)',
    },
  },

  // ============================================================
  // FRENCH (FR)
  // ============================================================
  fr: {
    shortTitle: 'Remboursement',
    title: 'Politique de Remboursement et Droit de R\u00e9tractation',
    subtitle: 'Notre politique de remboursement et votre droit l\u00e9gal de r\u00e9tractation (Widerrufsbelehrung) selon le droit allemand.',
    intro: 'Cette politique d\u00e9crit les conditions dans lesquelles nous offrons des remboursements et votre droit l\u00e9gal de r\u00e9tractation selon le droit allemand. Pour les clients commerciaux (B2B), seules nos politiques internes de remboursement s\'appliquent. Pour les consommateurs (B2C - personnes priv\u00e9es utilisant le service \u00e0 des fins en dehors de leur activit\u00e9 professionnelle), le droit l\u00e9gal de r\u00e9tractation selon \u00a7\u00a7 312g, 355 BGB s\'applique \u00e9galement.',
    lastUpdated: '15 mai 2026',
    version: 'Version 1.0',

    section1: {
      title: 'Consommateurs versus clients commerciaux',
      body: 'POUR D\u00c9TERMINER VOS DROITS DE REMBOURSEMENT, COMPRENEZ D\'ABORD VOTRE STATUT L\u00c9GAL:\n\nCLIENT COMMERCIAL (B2B - \u00a7 14 BGB):\nSi vous utilisez le service \u00e0 des fins d\'activit\u00e9 professionnelle/commerciale:\n\u2022 Vous n\'avez pas le droit l\u00e9gal de r\u00e9tractation\n\u2022 Seules les politiques de remboursement ci-dessous s\'appliquent\n\u2022 Le service est principalement destin\u00e9 \u00e0 vous\n\nCONSOMMATEUR (B2C - \u00a7 13 BGB):\nSi vous utilisez le service en tant que personne priv\u00e9e \u00e0 des fins en dehors de l\'activit\u00e9 professionnelle:\n\u2022 Vous avez le droit l\u00e9gal de r\u00e9tractation de 14 jours\n\u2022 Des conditions de protection suppl\u00e9mentaires s\'appliquent\n\u2022 Voir la section "Widerrufsbelehrung" ci-dessous\n\nDans la plupart des cas, les utilisateurs de [NOM DE LA PLATEFORME] sont des clients commerciaux car la plateforme est d\u00e9di\u00e9e \u00e0 la logistique professionnelle. Cependant, le statut individuel sera respect\u00e9 si revendiqu\u00e9.',
    },
    section2: {
      title: 'Politique principale de remboursement',
      body: 'ESSAI GRATUIT:\nNous offrons 14 jours d\'essai gratuit pour les nouveaux utilisateurs. Pendant cette p\u00e9riode:\n\u2022 Vous pouvez annuler \u00e0 tout moment sans frais\n\u2022 Pas de facturation automatique pendant la p\u00e9riode\n\u2022 Apr\u00e8s la p\u00e9riode, transition vers le plan choisi (confirmation requise)\n\nPREMIER MOIS - GARANTIE DE SATISFACTION:\nSi dans les 30 premiers jours d\'abonnement pay\u00e9 vous n\'\u00eates pas satisfait du service, nous offrons:\n\u2022 Remboursement complet de 100% sans questions\n\u2022 Activation par e-mail dans les 30 jours\n\u2022 Traitement dans les 14 jours suivant l\'approbation\n\nCONDITIONS POUR LA GARANTIE:\n\u2022 S\'applique uniquement au premier achat de plan\n\u2022 Ne s\'applique pas \u00e0 l\'upgrade ou downgrade\n\u2022 Ne s\'applique pas aux utilisateurs ayant utilis\u00e9 plus de 50% du quota\n\u2022 Une fois par client\n\nABONNEMENTS MENSUELS (APR\u00c8S LE PREMIER MOIS):\n\u2022 Annulation effective \u00e0 la fin de la p\u00e9riode actuelle\n\u2022 Acc\u00e8s complet jusqu\'\u00e0 la fin du cycle pay\u00e9\n\u2022 Pas de remboursement au prorata pour la p\u00e9riode restante\n\nABONNEMENTS ANNUELS:\n\u2022 Annulation effective \u00e0 la fin de l\'ann\u00e9e contractuelle\n\u2022 Remboursement au prorata uniquement dans des circonstances sp\u00e9ciales (voir "Circonstances Sp\u00e9ciales")',
    },
    section3: {
      title: 'WIDERRUFSBELEHRUNG (Droit l\u00e9gal de r\u00e9tractation - B2C)',
      body: 'CES DROITS S\'APPLIQUENT UNIQUEMENT AUX CONSOMMATEURS (\u00a7 13 BGB).\n\nDROIT DE R\u00c9TRACTATION:\nVous avez le droit de vous r\u00e9tracter de ce contrat dans un d\u00e9lai de 14 jours sans donner de raison.\n\nP\u00c9RIODE DE R\u00c9TRACTATION:\nLa p\u00e9riode de r\u00e9tractation est de 14 jours \u00e0 partir du jour de la conclusion du contrat.\n\nEXERCICE DU DROIT DE R\u00c9TRACTATION:\nPour exercer votre droit de r\u00e9tractation, vous devez nous informer:\n\n[NOM DE L\'ENTREPRISE]\n[Adresse compl\u00e8te]\nE-mail: [widerruf@entreprise.de]\nT\u00e9l\u00e9phone: [+49 XXX XXXXXXX]\n\nPar une d\u00e9claration claire (par exemple une lettre envoy\u00e9e par la poste ou e-mail) de votre d\u00e9cision de vous r\u00e9tracter de ce contrat.\n\nVous pouvez utiliser le formulaire mod\u00e8le de r\u00e9tractation joint \u00e0 la fin de cette politique, mais ce n\'est pas obligatoire.\n\nPOUR RESPECTER LE D\u00c9LAI DE R\u00c9TRACTATION, il suffit que vous envoyiez la communication concernant l\'exercice du droit de r\u00e9tractation avant l\'expiration de la p\u00e9riode de r\u00e9tractation.\n\nEFFETS DE LA R\u00c9TRACTATION:\nSi vous vous r\u00e9tractez de ce contrat, nous vous rembourserons tous les paiements re\u00e7us de vous, y compris les frais de livraison (\u00e0 l\'exception des co\u00fbts suppl\u00e9mentaires r\u00e9sultant de votre choix d\'un mode de livraison autre que le mode standard le moins co\u00fbteux), sans retard ind\u00fb et au plus tard 14 jours apr\u00e8s le jour o\u00f9 nous avons \u00e9t\u00e9 inform\u00e9s de votre d\u00e9cision de vous r\u00e9tracter de ce contrat.\n\nPour le remboursement, nous utiliserons le m\u00eame moyen de paiement que celui utilis\u00e9 pour la transaction originale, sauf accord expr\u00e8s contraire; en aucun cas vous ne serez factur\u00e9 de frais pour ce remboursement.',
    },
    section4: {
      title: 'EXCLUSION DU DROIT DE R\u00c9TRACTATION POUR SERVICES NUM\u00c9RIQUES',
      body: 'SANS PERTE DE VOS DROITS:\n\nSelon \u00a7 356 par. 4 BGB, le droit de r\u00e9tractation peut expirer avant la fin de la p\u00e9riode de r\u00e9tractation si:\n\n1. Le service a \u00e9t\u00e9 enti\u00e8rement ex\u00e9cut\u00e9 avant l\'expiration des 14 jours\n2. Vous avez donn\u00e9 un consentement explicite pr\u00e9alable\n3. Vous avez confirm\u00e9 le consentement \u00e0 l\'acceptation de l\'ex\u00e9cution apr\u00e8s la perte du droit de r\u00e9tractation\n\nCECI S\'APPLIQUE SI:\n\u2022 Vous activez un plan pay\u00e9 et commencez \u00e0 l\'utiliser\n\u2022 Vous donnez un consentement clair lors de l\'activation\n\u2022 Vous confirmez la compr\u00e9hension que vous n\'aurez plus le droit de r\u00e9tractation\n\nNOUS NOTIFIONS AVEC CONSENTEMENT CLAIR:\nLors de l\'activation du plan pay\u00e9, nous affichons:\n\u2705 Case \u00e0 cocher: "J\'accepte que l\'ex\u00e9cution du service commence imm\u00e9diatement"\n\u2705 Case \u00e0 cocher: "Je reconnais que mon droit de r\u00e9tractation de 14 jours est perdu lorsque le service est enti\u00e8rement ex\u00e9cut\u00e9"\n\nSI VOUS N\'\u00caTES PAS D\'ACCORD:\n\u2022 Votre droit de r\u00e9tractation de 14 jours est pr\u00e9serv\u00e9\n\u2022 Le service n\'est pas encore activ\u00e9\n\u2022 Apr\u00e8s 14 jours, le service est automatiquement activ\u00e9 (sauf si vous annulez)',
    },
    section5: {
      title: 'Circonstances sp\u00e9ciales pour remboursement',
      body: 'DANS CES CIRCONSTANCES SP\u00c9CIALES, NOUS OFFRONS DES REMBOURSEMENTS M\u00caME EN DEHORS DE LA GARANTIE DE 30 JOURS:\n\n1. PROBL\u00c8MES TECHNIQUES PENDANT PLUS DE 7 JOURS CONS\u00c9CUTIFS:\n\u2022 Service inutilisable pendant plus de 7 jours\n\u2022 En raison de nos probl\u00e8mes techniques (pas de votre internet)\n\u2022 Apr\u00e8s signalement et r\u00e9solution \u00e9chou\u00e9e\n\nCompensation: Remboursement au prorata pour le temps d\'indisponibilit\u00e9 + 1 mois gratuit\n\n2. CHANGEMENTS MAT\u00c9RIELS N\u00c9GATIFS AU SERVICE:\nSi nous supprimons des fonctions principales que vous avez utilis\u00e9es:\n\u2022 Pr\u00e9avis de 30 jours\n\u2022 Droit de r\u00e9siliation sans frais\n\u2022 Remboursement au prorata pour la p\u00e9riode restante\n\n3. CHANGEMENTS DE PRIX:\nSi nous augmentons le prix pendant le contrat actif:\n\u2022 Pr\u00e9avis de 60 jours\n\u2022 L\'ancien prix s\'applique jusqu\'\u00e0 la fin de l\'ann\u00e9e\n\u2022 Vous pouvez r\u00e9silier sans frais\n\u2022 Pas de remboursement au prorata (pas votre faute)\n\n4. SUSPENSION DE COMPTE SANS VIOLATION:\nSi nous suspendons votre compte par erreur:\n\u2022 Remboursement complet pour le temps de suspension\n\u2022 Restauration de toutes les fonctions\n\u2022 Opportunit\u00e9 suppl\u00e9mentaire en compensation\n\n5. FAILLITE OU FERMETURE DU SERVICE:\nSi nous devons fermer le service:\n\u2022 Pr\u00e9avis de 90 jours\n\u2022 Exportation de donn\u00e9es facilit\u00e9e\n\u2022 Remboursement au prorata pour la p\u00e9riode restante\n\u2022 Support pour la migration de service',
    },
    section6: {
      title: 'Aucun remboursement dans ces cas',
      body: 'REMBOURSEMENT NON DISPONIBLE DANS CES CIRCONSTANCES:\n\n1. APR\u00c8S LA P\u00c9RIODE DE GARANTIE DE 30 JOURS\nPour les abonnements mensuels, l\'annulation est effective \u00e0 la fin du mois actuel.\nPour les abonnements annuels, l\'annulation est effective \u00e0 la fin de l\'ann\u00e9e contractuelle.\n\n2. VIOLATIONS DES CGU OU PUA\nSi le compte est suspendu ou r\u00e9sili\u00e9 pour violation:\n\u2022 Pas de remboursement pour la p\u00e9riode restante\n\u2022 Paiement restant toujours d\u00fb\n\u2022 L\'indisponibilit\u00e9 n\'est pas consid\u00e9r\u00e9e comme un d\u00e9faut de service\n\n3. R\u00c9SILIATION EXTRAORDINAIRE PAR NOUS\nPour les violations catastrophiques (CSAM, terrorisme, fraude):\n\u2022 Aucun remboursement\n\u2022 Acc\u00e8s imm\u00e9diatement bloqu\u00e9\n\u2022 Action en justice peut suivre\n\n4. UTILISATION COMPL\u00c8TE DU SERVICE\nSi vous avez enti\u00e8rement utilis\u00e9 les fonctions principales du service:\n\u2022 T\u00e9l\u00e9chargements en masse de livraisons\n\u2022 Plusieurs exports DATEV\n\u2022 Utilisation API au-dessus de 80% du quota\nNon consid\u00e9r\u00e9 comme "insatisfait" du service.\n\n5. PROBL\u00c8MES DE CONNEXION INTERNET\nSi le probl\u00e8me vient de votre connexion internet, fournisseur ou appareil:\n\u2022 Pas notre responsabilit\u00e9\n\u2022 Pas de remboursement\n\u2022 Nous pouvons offrir des conseils techniques\n\n6. CO\u00dbTS DE D\u00c9PASSEMENT\nSi vous avez d\u00e9pass\u00e9 le quota du plan et pay\u00e9 des frais suppl\u00e9mentaires:\n\u2022 Les frais suppl\u00e9mentaires sont non remboursables\n\u2022 Nous offrons des conseils pour un meilleur plan',
    },
    section7: {
      title: 'Comment demander un remboursement',
      body: 'PROCESSUS DE DEMANDE DE REMBOURSEMENT:\n\n\u00c9TAPE 1: CONTACT INITIAL\nE-mail: [refund@entreprise.de]\nObjet: "Demande de remboursement - [Num\u00e9ro de compte]"\n\nINFORMATIONS REQUISES:\n\u2022 Nom et email enregistr\u00e9s\n\u2022 Num\u00e9ro de compte / ID d\'entreprise\n\u2022 Plan actif et date d\'activation\n\u2022 Raison de la demande (pour la garantie de 30 jours "insatisfait" suffit)\n\u2022 Num\u00e9ro de facture \u00e0 rembourser\n\n\u00c9TAPE 2: CONFIRMATION DE R\u00c9CEPTION\nNous confirmons la r\u00e9ception dans les 24 heures.\n\n\u00c9TAPE 3: V\u00c9RIFICATION\nV\u00e9rification dans les 3 jours ouvrables:\n\u2022 Confirmation du statut du compte\n\u2022 V\u00e9rification des conditions\n\u2022 Si une exclusion s\'applique\n\n\u00c9TAPE 4: APPROBATION OU REJET\nNotification avec raison \u00e9crite dans les 7 jours ouvrables.\n\n\u00c9TAPE 5: EX\u00c9CUTION\nSi approuv\u00e9:\n\u2022 Traitement dans les 14 jours\n\u2022 Paiement via la m\u00eame m\u00e9thode que le paiement original\n\u2022 Confirmation par e-mail lorsque trait\u00e9\n\u2022 Peut prendre 5-10 jours suppl\u00e9mentaires pour appara\u00eetre sur votre compte\n\nSI REJET\u00c9:\n\u2022 Raison \u00e9crite claire\n\u2022 Suggestions alternatives (upgrade/downgrade gratuit possible, etc.)\n\u2022 Possibilit\u00e9 d\'appel \u00e0 [appeals@entreprise.de]',
    },
    section8: {
      title: 'Frais et co\u00fbts suppl\u00e9mentaires',
      body: 'FRAIS NON REMBOURSABLES:\n\n1. CO\u00dbTS D\'APPLICATION (lorsque applicables)\nSi vous avez postul\u00e9 pour un plan sp\u00e9cial n\u00e9cessitant une documentation suppl\u00e9mentaire:\n\u2022 Le co\u00fbt de v\u00e9rification est non remboursable\n\u2022 M\u00eame si la demande est rejet\u00e9e\n\n2. CO\u00dbTS DE D\u00c9PASSEMENT\nPour d\u00e9passement de plan:\n\u2022 Bande passante au-dessus de la limite\n\u2022 Stockage au-dessus de la limite\n\u2022 Appels API au-dessus de la limite\nCes frais sont consommables et non remboursables.\n\n3. SERVICES PROFESSIONNELS\n\u2022 Formations personnalis\u00e9es\n\u2022 Conseil d\'impl\u00e9mentation\n\u2022 Personnalisation\nCes services sur base "pr\u00e9pay\u00e9e" sans remboursement apr\u00e8s le d\u00e9but du travail.\n\n4. CO\u00dbTS DE TIERS\nSi le plan inclut des services de tiers:\n\u2022 Marketplaces (Shopify, etc.)\n\u2022 Service de domaine\n\u2022 SMS / Notifications push\nCes services sont soumis aux politiques du fournisseur respectif.\n\nFRAIS AUTOMATIQUEMENT REMBOURS\u00c9S:\n\n1. FACTURES DUPLIQU\u00c9ES\nSi factur\u00e9 deux fois par notre erreur:\n\u2022 Remboursement automatique\n\u2022 Dans les 7 jours\n\u2022 Sans n\u00e9cessit\u00e9 de demande\n\n2. SUSPENSION INCORRECTE\nSi la suspension s\'av\u00e8re erron\u00e9e:\n\u2022 Remboursement pour le temps suspendu\n\u2022 Bonus 1 mois gratuit\n\u2022 Plus la responsabilit\u00e9 pour les dommages \u00e9ventuels',
    },
    section9: {
      title: 'Annulation d\'abonnement (pas de remboursement)',
      body: 'POUR ANNULER VOTRE ABONNEMENT (SANS DEMANDER DE REMBOURSEMENT):\n\nABONNEMENT MENSUEL:\n1. Param\u00e8tres → Abonnement\n2. Cliquez "Annuler l\'abonnement"\n3. Confirmez la d\u00e9cision\n4. Acc\u00e8s complet jusqu\'\u00e0 la fin du mois actuel\n5. Pas de facturation future\n\nABONNEMENT ANNUEL:\n1. Param\u00e8tres → Abonnement\n2. Cliquez "Annuler l\'abonnement"\n3. Choisissez le mode d\'annulation:\n   - Annulation en fin d\'ann\u00e9e (acc\u00e8s complet jusqu\'alors)\n   - Annulation imm\u00e9diate (pas de remboursement au prorata)\n4. Confirmez la d\u00e9cision\n\nAPR\u00c8S L\'ANNULATION:\n\u2022 Recevoir e-mail de confirmation\n\u2022 30 jours pour l\'exportation des donn\u00e9es\n\u2022 90 jours de sauvegarde dans des archives gel\u00e9es\n\u2022 Apr\u00e8s 90 jours: suppression permanente\n\nVOUS POUVEZ R\u00c9ACTIVER:\nDans les 30 jours suivant l\'annulation:\n\u2022 Acc\u00e8s complet \u00e0 vos donn\u00e9es\n\u2022 Peut changer de plan\n\u2022 Peut activer un autre plan\n\nAPR\u00c8S 30 JOURS:\nVous devez cr\u00e9er un nouveau compte. Les donn\u00e9es peuvent \u00eatre irr\u00e9cup\u00e9rables.',
    },
    section10: {
      title: 'Formulaire mod\u00e8le de r\u00e9tractation (B2C)',
      body: 'FORMULAIRE MOD\u00c8LE DE R\u00c9TRACTATION\n(Compl\u00e9tez et retournez ce formulaire uniquement si vous souhaitez vous r\u00e9tracter du contrat)\n\n\u00c0:\n[NOM DE L\'ENTREPRISE]\n[Adresse compl\u00e8te]\nE-mail: [widerruf@entreprise.de]\n\nD\u00c9CLARATION:\nJe/Nous (*) vous notifie/notifions par la pr\u00e9sente ma/notre (*) r\u00e9tractation du contrat portant sur la vente du bien (*)/pour la prestation du service (*) ci-dessous:\n\n_______________________________________________\n[Description du service / plan d\'abonnement]\n_______________________________________________\n\nCOMMAND\u00c9 LE: __________________________\nRE\u00c7U LE: __________________________\n\nNOM DU/DES CONSOMMATEUR(S): _____________\n\nADRESSE DU/DES CONSOMMATEUR(S): _________\n_______________________________________________\n\nNUM\u00c9RO DE COMPTE / ID: ____________________\n\nSIGNATURE DU/DES CONSOMMATEUR(S): _________\n(uniquement en cas de notification sur papier)\n\nDATE: __________________________________\n\n(*) Biffer la mention inutile\n\n--- FIN DU FORMULAIRE ---\n\nCe formulaire n\'est pas obligatoire - vous pouvez utiliser toute d\u00e9claration claire (e-mail, lettre, formulaire en ligne) indiquant votre d\u00e9cision de vous r\u00e9tracter.',
    },
    section11: {
      title: 'Paiements et remboursements',
      body: 'M\u00c9THODES DE PAIEMENT ACCEPT\u00c9ES:\n\u2022 Carte de cr\u00e9dit (Visa, Mastercard, American Express)\n\u2022 Carte de d\u00e9bit (Maestro, V-Pay)\n\u2022 Pr\u00e9l\u00e8vement SEPA (UE)\n\u2022 PayPal\n\u2022 Virement bancaire (uniquement pour les plans entreprise)\n\u2022 Apple Pay / Google Pay (dans certains cas)\n\nM\u00c9THODE DE REMBOURSEMENT:\nLes remboursements sont effectu\u00e9s avec la m\u00eame m\u00e9thode que le paiement original:\n\u2022 Carte → Carte (5-10 jours ouvrables jusqu\'au compte)\n\u2022 SEPA → SEPA (3-5 jours ouvrables)\n\u2022 PayPal → PayPal (24-48 heures)\n\u2022 Virement bancaire → Virement bancaire (5-7 jours ouvrables)\n\nDIVISION DU PAIEMENT:\nSi vous payez avec diff\u00e9rentes m\u00e9thodes pour un abonnement, nous remboursons proportionnellement selon la m\u00e9thode originale.\n\nDEVISE:\n\u2022 EUR comme standard\n\u2022 USD ou GBP possible pour les clients internationaux\n\u2022 Remboursement dans la m\u00eame devise que le paiement original\n\u2022 Aucun frais de changement de taux de change\n\nFACTURATION:\n\u2022 Factures fiscales envoy\u00e9es \u00e9lectroniquement (PDF + XRechnung)\n\u2022 Le remboursement cr\u00e9e une "Gutschrift" (note de cr\u00e9dit)\n\u2022 Toutes les transactions enregistr\u00e9es dans le journal d\'audit\n\u2022 Notre comptabilit\u00e9 respecte les normes GoBD',
    },
    section12: {
      title: 'Litiges et arbitrage',
      body: 'SI VOUS N\'\u00caTES PAS D\'ACCORD AVEC LA D\u00c9CISION DE REMBOURSEMENT:\n\n\u00c9TAPE 1: APPEL INTERNE\nE-mail: [appeals@entreprise.de]\nAvec nouvelle explication et preuves:\n\u2022 Examen par \u00e9quipe ind\u00e9pendante\n\u2022 R\u00e9ponse \u00e9crite dans les 14 jours\n\u2022 D\u00e9cision finale avec raisonnement\n\n\u00c9TAPE 2: R\u00c8GLEMENT ALTERNATIF DES LITIGES (RAL)\nPour les consommateurs B2C dans l\'UE:\nLa Commission europ\u00e9enne met \u00e0 disposition une plateforme en ligne:\nhttps://ec.europa.eu/consumers/odr/\n\nNous NE participons PAS aux proc\u00e9dures d\'arbitrage consommateur obligatoires, sauf disposition l\u00e9gale contraire.\n\n\u00c9TAPE 3: TRIBUNAL\nSi vous souhaitez suivre la voie l\u00e9gale:\n\u2022 Pour les clients commerciaux (B2B): juridiction [VILLE D\'ENREGISTREMENT], Allemagne\n\u2022 Pour les consommateurs (B2C): juridiction de votre pays de r\u00e9sidence (selon le R\u00e8glement Bruxelles I)\n\u2022 Droit applicable: droit allemand pour les contrats conclus en Allemagne\n\nPREUVES TRANSPARENTES:\nLa construction d\'e-mails et la communication sont stock\u00e9es avec journal d\'audit \u00e0 des fins l\u00e9gales. En Allemagne, c\'est obligatoire selon GoBD.',
    },
    section13: {
      title: 'Questions fr\u00e9quemment pos\u00e9es',
      body: 'Q: Puis-je rembourser si j\'ai pay\u00e9 pour 1 an mais je n\'utilise que 2 mois?\nR: Seulement si vous \u00eates dans les 30 jours suivant l\'activation ou si des circonstances sp\u00e9ciales s\'appliquent (probl\u00e8me technique, etc.). Apr\u00e8s cela, seulement annulation en fin d\'ann\u00e9e contractuelle.\n\nQ: Combien de temps prend le remboursement?\nR: 14 jours pour l\'approbation + 5-10 jours pour le traitement + 1-3 jours pour appara\u00eetre sur le compte = ~20-25 jours au total.\n\nQ: Puis-je changer mon plan?\nR: Oui, vous pouvez upgrader \u00e0 tout moment (diff\u00e9rence pay\u00e9e au prorata) ou downgrader \u00e0 la fin du cycle actuel.\n\nQ: Est-ce que je perds des donn\u00e9es si je rembourse?\nR: Non, les donn\u00e9es sont conserv\u00e9es pour 30 jours d\'exportation + 90 jours de sauvegarde. Vous pouvez r\u00e9cup\u00e9rer si vous r\u00e9activez.\n\nQ: Que se passe-t-il avec les factures en comptabilit\u00e9?\nR: Une "Gutschrift" (note de cr\u00e9dit) est cr\u00e9\u00e9e annulant la facture originale. Nous vous envoyons un deuxi\u00e8me document fiscal.\n\nQ: Puis-je rembourser un add-on ou un d\u00e9passement?\nR: Pour les add-ons (services suppl\u00e9mentaires, modules premium) non - ils sont consommables. Pour les frais de d\u00e9passement automatiques, cela varie.\n\nQ: Puis-je transf\u00e9rer un compte \u00e0 une autre personne?\nR: Oui, avec notification \u00e9crite et confirmation du destinataire. Frais: €50 (une fois). Contactez [billing@entreprise.de].\n\nQ: Que se passe-t-il si mon entreprise fait faillite?\nR: Vous pouvez avoir le droit de r\u00e9silier et recevoir un remboursement au prorata. Contactez avec documentation l\u00e9gale de faillite.',
    },
    section14: {
      title: 'Modifications de la politique de remboursement',
      body: 'CETTE POLITIQUE PEUT \u00caTRE MISE \u00c0 JOUR POUR REFL\u00c9TER:\n\u2022 Changements l\u00e9gaux (\u00a7\u00a7 312g, 355 BGB, Directive UE 2011/83)\n\u2022 Changements dans notre pratique commerciale\n\u2022 Feedback des clients\n\u2022 Am\u00e9liorations de la transparence\n\nCOMMUNICATION DES CHANGEMENTS:\n\u2022 E-mail aux utilisateurs actifs 30 jours \u00e0 l\'avance\n\u2022 Banni\u00e8re sur la plateforme\n\u2022 Horodatage mis \u00e0 jour en haut du document\n\nPROTECTION DES DROITS EXISTANTS:\nLes changements n\'affectent PAS les contrats existants - uniquement les nouveaux:\n\u2022 Votre plan actuel conserve les r\u00e8gles originales jusqu\'\u00e0 la fin\n\u2022 Les droits garantis ne sont pas supprim\u00e9s r\u00e9troactivement\n\u2022 Les am\u00e9liorations sont appliqu\u00e9es automatiquement\n\nVOUS POUVEZ R\u00c9SILIER:\nSi vous n\'\u00eates pas d\'accord avec les changements:\n\u2022 30 jours pour r\u00e9siliation sans frais suppl\u00e9mentaires\n\u2022 Remboursement au prorata pour changements n\u00e9gatifs\n\u2022 Exportation de donn\u00e9es facilit\u00e9e',
    },
    section15: {
      title: 'Contact',
      body: 'QUESTIONS DE REMBOURSEMENT:\nE-mail: [refund@entreprise.de]\nR\u00e9ponse dans les 24 heures.\n\nWIDERRUF (R\u00c9TRACTATION B2C):\nE-mail: [widerruf@entreprise.de]\nCourrier: [Adresse compl\u00e8te], d\u00e9pt. "Widerruf"\n\nFACTURATION:\nE-mail: [billing@entreprise.de]\nQuestions sur factures, changement de m\u00e9thode de paiement, etc.\n\nAPPELS:\nE-mail: [appeals@entreprise.de]\nD\u00e9lai: 30 jours depuis la d\u00e9cision originale\n\nSUPPORT G\u00c9N\u00c9RAL:\nE-mail: [support@entreprise.de]\nChat en direct: dans la plateforme (heures de bureau)\n\nPOUR PROBL\u00c8MES JURIDIQUES:\nE-mail: [legal@entreprise.de]\n\nCOURRIER OFFICIEL:\n[NOM DE L\'ENTREPRISE]\n[Adresse compl\u00e8te]\nAllemagne\nT\u00e9l\u00e9phone: [+49 XXX XXXXXXX]\n\nHEURES DE BUREAU:\nLundi - Vendredi: 09:00 - 17:00 CET\n(urgences: 24/7 via formulaire en ligne)',
    },
  },
};
