import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

/*
  Neural text-to-speech for the conversational assistant.

  Takes { text } from an authenticated user and returns spoken audio (audio/mpeg)
  generated by ElevenLabs, so the assistant sounds human instead of using the
  browser's robotic speech synthesis. The ElevenLabs API key and voice come from
  the super-admin-managed `ai_config` singleton (service-role only), never the
  client. If no key is configured the function returns 503 and the frontend
  falls back to the browser voice.

  Self-contained single file. verify_jwt is on, so only signed-in users reach it.
*/

const ELEVEN_URL = "https://api.elevenlabs.io/v1/text-to-speech";
const DEFAULT_VOICE = "JBFqnCBsd6RMkjVDRZzb"; // warm male "manager" voice
const MODEL = "eleven_multilingual_v2"; // supports sq / de / fr / en
const MAX_CHARS = 1200;

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey, apikey",
};

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { error: "Method not allowed" });

  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY");
  const service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !anon || !service) return json(500, { error: "Server misconfigured" });

  // Require a valid signed-in user (any authenticated account of a tenant).
  const auth = req.headers.get("Authorization") || req.headers.get("authorization") || "";
  if (!auth.toLowerCase().startsWith("bearer ")) return json(401, { error: "Missing bearer token" });
  const userClient = createClient(url, anon, { global: { headers: { Authorization: auth } }, auth: { persistSession: false } });
  const { data: u, error: uErr } = await userClient.auth.getUser();
  if (uErr || !u?.user) return json(401, { error: "Invalid session" });

  let body: { text?: string; voice_id?: string };
  try { body = await req.json(); } catch { return json(400, { error: "Invalid JSON" }); }
  const text = String(body?.text ?? "").trim().slice(0, MAX_CHARS);
  if (!text) return json(400, { error: "text required" });

  // Key + voice come from ai_config (service role), env as fallback.
  const admin = createClient(url, service, { auth: { persistSession: false } });
  const { data: cfg } = await admin.from("ai_config").select("elevenlabs_api_key, elevenlabs_voice_id, enabled").eq("id", true).maybeSingle();
  if (cfg && cfg.enabled === false) return json(503, { error: "Assistant disabled" });
  const apiKey = (cfg?.elevenlabs_api_key && cfg.elevenlabs_api_key.length > 0) ? cfg.elevenlabs_api_key : Deno.env.get("ELEVENLABS_API_KEY");
  if (!apiKey) return json(503, { error: "TTS not configured" });
  const voiceId = String(body?.voice_id || cfg?.elevenlabs_voice_id || Deno.env.get("ELEVENLABS_VOICE_ID") || DEFAULT_VOICE);

  try {
    const resp = await fetch(`${ELEVEN_URL}/${voiceId}?output_format=mp3_44100_128`, {
      method: "POST",
      headers: { "xi-api-key": apiKey, "content-type": "application/json", "accept": "audio/mpeg" },
      body: JSON.stringify({
        text,
        model_id: MODEL,
        voice_settings: { stability: 0.4, similarity_boost: 0.8, style: 0.15, use_speaker_boost: true },
      }),
    });
    if (!resp.ok) {
      console.error("elevenlabs error", resp.status, await resp.text());
      return json(502, { error: "TTS service error", detail: resp.status });
    }
    const audio = await resp.arrayBuffer();
    return new Response(audio, { status: 200, headers: { ...corsHeaders, "Content-Type": "audio/mpeg", "Cache-Control": "no-store" } });
  } catch (e) {
    console.error("tts failure", e);
    return json(500, { error: "TTS failed" });
  }
});
